### ISSUE TITLE
RetroArch closes with the Threaded Video option. driver gl and glcore 

### ISSUE THREAD

**Issue by alexb3d** [libretro/RetroArch#12245]
The problem happens with the GL and GLcore drivers, with Vulkan it works perfect,

In the PPA version it is activated without problems, when it is deactivated it closes RA.

In the Flatpak version the similar one, but RA closes when activating or deactivating it. I'm going to link to Flathub, although I guess it depends on this one.

RetroArch 1.9.1 / Ubuntu 20.04.2 / Core i7 3770 / Intel® HD Graphics 4000 (IVB GT2)

**Comment by twinaphex** [comment]
I have only seen this bug happen on Linux and with Intel HD GPUs like this (I have an Ivy Bridge laptop too with a HD 4000). I'm beginning to suspect it might be a driver bug?

**Comment by alexb3d** [comment]
I am testing with the latest update (1.9.5). Sorry I couldn't test before.

It is half corrected. In GL and GLcore it can be activated. But when disabled, RA closes.

**Comment by grant2258** [comment]
This only happens if a core is loaded for me else its fine.

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==7535==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f7dd4c4b0f7 bp 0x621004583100 sp 0x7ffd249f2628 T0)
==7535==The signal is caused by a READ memory access.
==7535==Hint: address points to the zero page.
    #0 0x7f7dd4c4b0f7 in XGetXCBConnection (/usr/lib/libX11-xcb.so.1+0x10f7)
    #1 0x7f7dbd0fc627  (/usr/lib/../lib/libGLX_mesa.so.0+0x37627)
    #2 0x7f7dbd103d1f  (/usr/lib/../lib/libGLX_mesa.so.0+0x3ed1f)
    #3 0x7f7dd10bdc18 in glXCreateWindow (/usr/lib/libGLX.so.0+0x19c18)
    #4 0x55ffc090165e in gfx_ctx_x_set_video_mode gfx/drivers_context/x_ctx.c:607
    #5 0x55ffc098503f in gl2_init gfx/drivers/gl.c:3669
    #6 0x55ffbfa6b9da in video_driver_init_internal /home/grant/Source/RetroArch/retroarch.c:30541
    #7 0x55ffbfa8e05b in drivers_init /home/grant/Source/RetroArch/retroarch.c:33264
    #8 0x55ffbfa778f1 in video_driver_reinit_context /home/grant/Source/RetroArch/retroarch.c:31439
    #9 0x55ffbfa77c24 in video_driver_reinit /home/grant/Source/RetroArch/retroarch.c:31451
    #10 0x55ffbf9a6908 in command_event_reinit /home/grant/Source/RetroArch/retroarch.c:13248
    #11 0x55ffbf9abe4c in command_event /home/grant/Source/RetroArch/retroarch.c:13884
    #12 0x55ffc05cabf4 in general_write_handler menu/menu_setting.c:7872
    #13 0x55ffc0599188 in setting_set_with_string_representation menu/menu_setting.c:1022
    #14 0x55ffc059d777 in setting_bool_action_toggle_default menu/menu_setting.c:1826
    #15 0x55ffc05bdb3e in menu_action_handle_setting menu/menu_setting.c:6714
    #16 0x55ffc05bee21 in menu_setting_set menu/menu_setting.c:6838
    #17 0x55ffc06fd5df in bind_right_generic menu/cbs/menu_cbs_right.c:939
    #18 0x55ffbf93c23a in generic_menu_entry_action /home/grant/Source/RetroArch/retroarch.c:2587
    #19 0x55ffc051fc90 in ozone_menu_entry_action menu/drivers/ozone/ozone.c:640
    #20 0x55ffbf94028f in menu_entry_action /home/grant/Source/RetroArch/retroarch.c:2853
    #21 0x55ffbf93630a in generic_menu_iterate /home/grant/Source/RetroArch/retroarch.c:2155
    #22 0x55ffbf952b85 in menu_driver_iterate /home/grant/Source/RetroArch/retroarch.c:4650
    #23 0x55ffbfab9eab in runloop_check_state /home/grant/Source/RetroArch/retroarch.c:37932
    #24 0x55ffbfac2756 in runloop_iterate /home/grant/Source/RetroArch/retroarch.c:38633
    #25 0x55ffbf9b9a0e in rarch_main /home/grant/Source/RetroArch/retroarch.c:15549
    #26 0x55ffbffcb370 in main ui/drivers/ui_qt.cpp:4307
    #27 0x7f7dd1f9eb24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
    #28 0x55ffbf90f66d in _start (/usr/local/bin/retroarch+0x4da366d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/libX11-xcb.so.1+0x10f7) in XGetXCBConnection
==7535==ABORTING
```

**Comment by grant2258** [comment]
ok have a fix for this seems destroying the display is causing the issues. If you really want to destroy it make sure you initialise again. Again I see no reason to destory the display itself but im no expert here is the patch https://github.com/grant2258/RetroArch/commit/87aa0c66e2bfeea083f01bc73c252b9f65497f74

**Comment by alexb3d** [comment]
It is working perfect with all video drivers.
Thank you!
