### ISSUE TITLE
30KHz ogg file as achievement unlock sound causes crash

### ISSUE THREAD

**Issue by Jamiras** [libretro/RetroArch#12593]
## Description

This specific sound file causes a coredump when played.

[unlock.zip](https://github.com/libretro/RetroArch/files/6737510/unlock.zip)

### Expected behavior

RetroArch does not crash 

### Actual behavior

RetroArch crashes. The stacktrace at the crash is in malloc:
```
#0  0x00007fffee2102b3 in _int_malloc (av=av@entry=0x7fffee566c40 <main_arena>, bytes=bytes@entry=16384) at malloc.c:3936
#1  0x00007fffee2123cd in __GI___libc_malloc (bytes=16384) at malloc.c:3075
#2  0x00007fffeedb9298 in operator new(unsigned long) () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fffd46f6c27 in  () at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#4  0x00007fffd46f6ba1 in  () at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#5  0x00007fffd46eacac in llvm::GVN::ValueTable::assignExpNewValueNum(llvm::GVN::Expression&) ()
    at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#6  0x00007fffd46e8dd4 in llvm::GVN::ValueTable::lookupOrAdd(llvm::Value*) ()
    at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#7  0x00007fffd46f18c9 in llvm::GVN::processInstruction(llvm::Instruction*) ()
    at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#8  0x00007fffd46f2b8b in llvm::GVN::processBlock(llvm::BasicBlock*) ()
    at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#9  0x00007fffd46ebb70 in llvm::GVN::runImpl(llvm::Function&, llvm::AssumptionCache&, llvm::DominatorTree&, llvm::TargetLibraryInfo const&, llvm::AAResults&, llvm::MemoryDependenceResults*, llvm::LoopInfo*, llvm::OptimizationRemarkEmitter*) () at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#10 0x00007fffd46f4b55 in  () at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#11 0x00007fffd3de2866 in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
    at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#12 0x00007fffd3de1f3e in llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) ()
    at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#13 0x00007fffd3de1ed6 in llvm::legacy::FunctionPassManager::run(llvm::Function&) ()
    at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#14 0x00007fffd3d64826 in LLVMRunFunctionPassManager () at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#15 0x00007fffd810ad20 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#16 0x00007fffd81689e8 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#17 0x00007fffd815cf18 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#18 0x00007fffd8148750 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#19 0x00007fffd7b76f2f in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#20 0x00007fffd7dab558 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#21 0x00007fffd7dab5f5 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#22 0x0000555555a5138d in gfx_display_gl_draw (draw=0x7fffffffccb0, data=0x5555568c22a0, video_width=879, video_height=672) at gfx/drivers_display/gfx_display_gl.c:248
#23 0x00005555559fc8dd in gfx_widgets_draw_icon (userdata=0x5555568c22a0, data_disp=0x555556766730 <rarch_st+141456>, video_width=879, video_height=672, icon_width=104, icon_height=104, texture=195, x=0, y=-91.210762, rotation=0, scale_factor=1, color=0x5555567406c0 <pure_white>)
    at gfx/gfx_widgets.c:715
#24 0x0000555555a07380 in gfx_widget_achievement_popup_frame (data=0x7fffffffd0f0, userdata=0x55555675f808 <rarch_st+113000>) at gfx/widgets/gfx_widget_achievement_popup.c:175
#25 0x00005555559fff6a in gfx_widgets_frame (data=0x7fffffffd0f0) at gfx/gfx_widgets.c:1831
#26 0x0000555555a4b8c3 in gl2_frame (data=0x5555568c22a0, frame=0x5555580e9540, frame_width=256, frame_height=224, frame_count=1018, pitch=512, msg=0x5555567b21e0 <video_driver_msg> "", video_info=0x7fffffffd0f0) at gfx/drivers/gl.c:3071
#27 0x000055555565f96e in video_driver_frame (data=0x5555580e9540, width=256, height=224, pitch=512)
    at retroarch.c:32255
#28 0x00007fffc2619526 in retro_run () at /home/brian/.config/retroarch/cores/fceumm_libretro.so
#29 0x0000555555670bcd in core_run () at retroarch.c:39749
```
As this seems unrelated to the sound file, I ran it through valgrind, which reported the following:
```
==14684== Thread 1:
==14684== Invalid write of size 4
==14684==    at 0x2ADD49: resampler_sinc_process_sse_kaiser (sinc_resampler.c:382)
==14684==    by 0x2E682F: audio_mixer_mix_ogg (audio_mixer.c:953)
==14684==    by 0x2E745F: audio_mixer_mix (audio_mixer.c:1211)
==14684==    by 0x20BF4C: audio_driver_flush (retroarch.c:28856)
==14684==    by 0x20C5D9: audio_driver_sample_batch (retroarch.c:29029)
==14684==    by 0x2FF69242: retro_run (in /home/brian/.config/retroarch/cores/fceumm_libretro.so)
==14684==    by 0x224BCC: core_run (retroarch.c:39749)
==14684==    by 0x223800: runloop_iterate (retroarch.c:39097)
==14684==    by 0x1EF38B: rarch_main (retroarch.c:15685)
==14684==    by 0x3E3581: main (ui_qt.cpp:4307)
==14684==  Address 0x21d90af8 is 0 bytes after a block of size 49,176 alloc'd
==14684==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14684==    by 0x253911: memalign_alloc (memalign.c:32)
==14684==    by 0x2E599B: audio_mixer_play_ogg (audio_mixer.c:540)
==14684==    by 0x2E638B: audio_mixer_play (audio_mixer.c:805)
==14684==    by 0x20D62D: audio_driver_mixer_play_stream_internal (retroarch.c:29507)
==14684==    by 0x20DE68: audio_driver_mixer_play_menu_sound (retroarch.c:29657)
==14684==    by 0xA1B725: rcheevos_async_award_achievement (cheevos.c:482)
==14684==    by 0xA1C96E: rcheevos_award_achievement (cheevos.c:909)
==14684==    by 0xA1DCB0: rcheevos_runtime_event_handler (cheevos.c:1509)
==14684==    by 0xA2D5C2: rc_runtime_do_frame (runtime.c:523)
==14684==    by 0xA1DED4: rcheevos_test (cheevos.c:1589)
==14684==    by 0x22385D: runloop_iterate (retroarch.c:39109)
==14684== 
==14684== Invalid write of size 4
==14684==    at 0x2ADD99: resampler_sinc_process_sse_kaiser (sinc_resampler.c:383)
==14684==    by 0x2E682F: audio_mixer_mix_ogg (audio_mixer.c:953)
==14684==    by 0x2E745F: audio_mixer_mix (audio_mixer.c:1211)
==14684==    by 0x20BF4C: audio_driver_flush (retroarch.c:28856)
==14684==    by 0x20C5D9: audio_driver_sample_batch (retroarch.c:29029)
==14684==    by 0x2FF69242: retro_run (in /home/brian/.config/retroarch/cores/fceumm_libretro.so)
==14684==    by 0x224BCC: core_run (retroarch.c:39749)
==14684==    by 0x223800: runloop_iterate (retroarch.c:39097)
==14684==    by 0x1EF38B: rarch_main (retroarch.c:15685)
==14684==    by 0x3E3581: main (ui_qt.cpp:4307)
==14684==  Address 0x21d90afc is 4 bytes after a block of size 49,176 alloc'd
==14684==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14684==    by 0x253911: memalign_alloc (memalign.c:32)
==14684==    by 0x2E599B: audio_mixer_play_ogg (audio_mixer.c:540)
==14684==    by 0x2E638B: audio_mixer_play (audio_mixer.c:805)
==14684==    by 0x20D62D: audio_driver_mixer_play_stream_internal (retroarch.c:29507)
==14684==    by 0x20DE68: audio_driver_mixer_play_menu_sound (retroarch.c:29657)
==14684==    by 0xA1B725: rcheevos_async_award_achievement (cheevos.c:482)
==14684==    by 0xA1C96E: rcheevos_award_achievement (cheevos.c:909)
==14684==    by 0xA1DCB0: rcheevos_runtime_event_handler (cheevos.c:1509)
==14684==    by 0xA2D5C2: rc_runtime_do_frame (runtime.c:523)
==14684==    by 0xA1DED4: rcheevos_test (cheevos.c:1589)
==14684==    by 0x22385D: runloop_iterate (retroarch.c:39109)
```
The only thing unusual about this sound file is that it's sample rate (30KHz) is lower than the default playback rate (48KHz). This causes the `bandwidth_mod` (downsampling rate) to be greater than 1. There's code in place to handle rates [less than 1.0](https://github.com/libretro/RetroArch/blob/c2a73a69215232f64ab20d28ed4ce68057d465c3/libretro-common/audio/resampler/drivers/sinc_resampler.c#L798-L802), but nothing for greater than 1.0.

As directed, I also tested the non-SSE code path, and saw similar results:
```
==4038== Thread 1:
==4038== Invalid write of size 4
==4038==    at 0x2AE9A3: resampler_sinc_process_c (sinc_resampler.c:575)
==4038==    by 0x2E67D3: audio_mixer_mix_ogg (audio_mixer.c:953)
==4038==    by 0x2E7403: audio_mixer_mix (audio_mixer.c:1211)
==4038==    by 0x20BF4C: audio_driver_flush (retroarch.c:28856)
==4038==    by 0x20C5D9: audio_driver_sample_batch (retroarch.c:29029)
==4038==    by 0x2FF69242: retro_run (in /home/brian/.config/retroarch/cores/fceumm_libretro.so)
```

From stepping through the code, my best guess is that there's a rounding error. [This line](https://github.com/libretro/RetroArch/blob/92a098ee02b713ad1507ed120b9d5c78405cce75/libretro-common/audio/resampler/drivers/sinc_resampler.c#L530) divides 16777216 by 1.5, resulting in 11184810.666666, which is rounded to 11184810. This seems to result in the loop running one too many times, and the write past the end of the buffer (as reported by valgrind).

I tried wrapping the division with `ceil`, but that doesn't prevent the crash. The only thing I've found that does seem to work is to allocate an extra entry [here](https://github.com/libretro/RetroArch/blob/92a098ee02b713ad1507ed120b9d5c78405cce75/libretro-common/audio/audio_mixer.c#L539-L541). `samples` is 12288 (8192*1.5, no rounding error). If I simply add 1 (12289), then everything works and valgrind is happy (at least around playing the audio sample). This doesn't feel like the best solution, but if the problem _is_ in `sinc_resampler.c`, it avoids duplicating the fix for each of the sinc implementations (they're all basically the same outer loop with slightly different optimizations of the innermost loop).

I brought up my findings in #programming on discord, and was directed to create an issue and ping @Themaister .

### Steps to reproduce the bug

* Place `unlock.ogg` in the `assets/sounds` folder
* Enable achievements, enable unlock sound, enable encore mode.
* Start a game with an easy to earn achievement - I like to use Super Mario Bros, where collecting the first mushroom triggers an achievement.
* Trigger the achievement
- RetroArch crashes

The provided sound file can also be used as a menu sound (i.e. `ok.ogg`), but that only seemed to crash for me about 60% of the time. It might be easier to test/reproduce there.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit

- RetroArch: 1.9.5 / 0785d4aa72

I also tried c01df07f3d on a suggestion from @twinaphex - the problem exists there too. I did not go back any farther to identify if there was ever a version where this sound file worked.

### Environment information

- OS: Ubuntu 18
- Compiler: make

**Comment by twinaphex** [comment]
Hi there @Jamiras , can you confirm if @jdgleaver 's PR fixed this?

https://github.com/libretro/RetroArch/pull/12921

**Comment by twinaphex** [comment]
@jdgleaver Can we consider this closed for now or are you not satisfied with the solution you made for it in order for us to consider it closed?

**Comment by jdgleaver** [comment]
@twinaphex Yes, I think we can say that https://github.com/libretro/RetroArch/pull/12987 closes this specific issue.

We still need a resampler expert to implement the 'proper' solution mentioned in that PR, but the mixer code should at least be safe for the time being.
