### ISSUE TITLE
Audio lost when core ouputs audio during drivers reinit

### ISSUE THREAD

**Issue by flyinghead** [libretro/RetroArch#12883]
There's a race condition when a core ouputs audio while a drivers reinit is happening. This can lead to audio being disabled.

Scenario:
1. RA deinit all drivers
2. core calls back `audio_driver_sample_batch` but the flush fails and `audio_driver_active` is set to false
3. RA doesn't init the audio driver because it's inactive

### core ###
```
#0  audio_driver_flush
    (p_rarch=0x555556412f60 <rarch_st>, slowmotion_ratio=3, audio_fastforward_mute=0x0, data=0x7fff62752980 <WriteSample(short, short)::Buffer>, samples=0x400, is_slowmotion=0x0, is_fastmotion=0x0) at retroarch.c:28257
#1  0x0000555555618522 in audio_driver_sample_batch (data=0x7fff62752980 <WriteSample(short, short)::Buffer>, frames=0x200)
    at retroarch.c:28406
#2  0x00007fff612e6942 in WriteSample(short, short) (r=<optimized out>, l=<optimized out>)
    at /home/raph/flycast-option/shell/libretro/audiostream.cpp:39
#3  0x00007fff6130e5ec in AICA_Sample() () at /home/raph/flycast-option/core/hw/aica/sgc_if.cpp:1536
```
### RA ###
```
(...)
#16 0x000055555561c89f in video_driver_init_internal
    (p_rarch=0x555556412f60 <rarch_st>, settings=0x7fffebff7010, video_is_threaded=0x7fffffff8cdb, verbosity_enabled=0x1)
    at retroarch.c:30286
#17 0x00005555556228bf in drivers_init (p_rarch=0x555556412f60 <rarch_st>, settings=0x7fffebff7010, flags=0x7ff, verbosity_enabled=0x1)
    at retroarch.c:33035
#18 0x000055555561eb31 in video_driver_reinit_context (p_rarch=0x555556412f60 <rarch_st>, settings=0x7fffebff7010, flags=0x7ff)
    at retroarch.c:31201
#19 0x000055555561ebb2 in video_driver_reinit (flags=0x7ff) at retroarch.c:31213
#20 0x00005555555f871d in command_event_reinit (p_rarch=0x555556412f60 <rarch_st>, flags=0x7ff) at retroarch.c:13409
#21 0x00005555555f99dd in command_event (cmd=CMD_EVENT_REINIT, data=0x0) at retroarch.c:14058
#22 0x00005555555fb64d in command_event (cmd=CMD_EVENT_FULLSCREEN_TOGGLE, data=0x0) at retroarch.c:14907
#23 0x000055555562cf8d in runloop_check_state (p_rarch=0x555556412f60 <rarch_st>, settings=0x7fffebff7010, current_time=0x228c20f2b74)
    at retroarch.c:37521
#24 0x000055555562fb67 in runloop_iterate () at retroarch.c:38573
#25 0x00005555555fcd95 in rarch_main (argc=0x2, argv=0x7fffffffdbf8, data=0x0) at retroarch.c:15748

```

**Comment by twinaphex** [comment]
I managed to reproduce this myself ,except with the PCSX2 core -

https://github.com/libretro/RetroArch/commit/d45945cda2765dbca3f3524e2c6cd52bce45a8fa

Let me know if this fixes things for you on Flycast with this game as well.

**Comment by twinaphex** [comment]
OK, I believe these two are a better fix put together -

https://github.com/libretro/RetroArch/commit/d429ecf304807f325dafc5310286d41243b4899a

https://github.com/libretro/RetroArch/commit/d2283a5237ed879d5b239708f13fcd2e0eb6dec7

**Comment by twinaphex** [comment]
I think this one has been resolved for now.
