### ISSUE TITLE
Crashing just after save state with saving save state thumbnails

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#13058]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Retroarch crashing just after save state. Save state saves as usual, but then Retroarch crashes.

### Expected behavior

Retroarch shouldn't crash.

### Actual behavior

Crash.

When running under GDB:

```
warning: Critical error detected c0000374

Thread 8 received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 21752.0x5e10]
0x00007ffefda41f00 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
(gdb) bt full
#0  0x00007ffefda41f00 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x00007ffefda45182 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#2  0x00007ffefda45d80 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#3  0x00007ffefd9fa0a7 in ntdll!memset () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#4  0x00007ffefd731cb3 in msvcrt!_setjmp ()
   from C:\Windows\system32\msvcrt.dll
No symbol table info available.
#5  0x00007ff6cb4774ab in scaler_ctx_gen_reset (ctx=0xed06faf6a0)
    at libretro-common/gfx/scaler/scaler.c:276
No locals.
#6  0x00007ff6cb47702a in scaler_ctx_gen_filter (ctx=0xed06faf6a0)
    at libretro-common/gfx/scaler/scaler.c:79
No locals.
#7  0x00007ff6cb475c3c in video_frame_convert_to_bgr24 (scaler=0xed06faf6a0,
    output=0xed0ed86040, input=0xed0c99c836, width=878, height=672,
    in_pitch=-2634) at ./libretro-common/include/gfx/video_frame.h:175
No locals.
#8  0x00007ff6cb475db6 in screenshot_dump_direct (state=0xed065baa40)
    at tasks/task_screenshot.c:73
        scaler = {scaler_horiz = 0x0, scaler_vert = 0x7ffe0372,
          scaler_special = 0x7cf, in_pixconv = 0x2000000,
          out_pixconv = 0x7ff6caf4c000,
          direct_pixconv = 0x7ffefd98b364 <ntdll!RtlEnterCriticalSection+228>, horiz = {filter = 0x0, filter_pos = 0xed06502d90, filter_len = 106382528,
            filter_stride = 237}, vert = {filter = 0xed06faf760,
            filter_pos = 0x0, filter_len = 105917840, filter_stride = 237},
          input = {frame = 0x7ff6cb737750 <thread_wrap>,
            stride = -881624415}, scaled = {frame = 0xed06502d90, width = 0,
            height = 0, stride = 0}, output = {
            frame = 0x7ff6cb737750 <thread_wrap>, stride = 117110640},
          in_width = 878, in_height = 672, in_stride = 106382528,
          out_width = 878, out_height = 672, out_stride = 237,
          in_fmt = SCALER_FMT_BGR24, out_fmt = SCALER_FMT_BGR24,
          scaler_type = SCALER_TYPE_POINT, unscaled = 237}
        ret = false
#9  0x00007ff6cb475e9c in task_screenshot_handler (task=0xed065cdf60)
    at tasks/task_screenshot.c:138
        state = 0xed065baa40
        ret = false
#10 0x00007ff6cb4019da in threaded_worker (userdata=0x0)
    at libretro-common/queues/task_queue.c:507
        task = 0xed065cdf60
        finished = false
#11 0x00007ff6cb737786 in thread_wrap (data_=0xed06502d90)
    at libretro-common/rthreads/rthreads.c:143
        data = 0xed06502d90
#12 0x00007ffefd7e1412 in KERNEL32!BaseThreadInitThunk ()
   from C:\Windows\system32\kernel32.dll
No symbol table info available.
#13 0x00007ffefd9654f4 in ntdll!RtlUserThreadStart ()
   from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#14 0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)

````

### Steps to reproduce the bug
1. Set "Show advanced Settings" - ON in "User interface".
2. Go to "Saving" and set to ON "Save State Thumbnails"
3.Load any game with any core which support save states (PC Engine game, NES game etc)
4. Save state.
5. Crash.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 5a40d28

### Environment information

- OS: Windows 8.1 Enterprise x64
- Compiler: [In case you are running local builds]

**Comment by ofry** [comment]
Tested on games with and without cheevos.

**Comment by twinaphex** [comment]
Please provide more information on this. Which cores does this happen with, when did this issue start for you, etc.

On its own this doesn't really help us figure out any of these questions right now. It's like trying to find a needle in a haystack.

**Comment by ofry** [comment]
Tried on different cores (PC Engine Supergrafx, FCEUmm, VBA-M). it happened everywhere.

**Comment by twinaphex** [comment]
Will need a crash log and a stack trace of this. This is simply not enough information being provided.

Also, if you are able to bisect the issue and point to a specific commit that does it, even better.

**Comment by twinaphex** [comment]
I also cannot reproduce it myself. You will have to do a bisect and provide a stack trace.

**Comment by ofry** [comment]
@twinaphex added more info. Could you reproduce this now?

**Comment by ofry** [comment]
Added stack trace too.

**Comment by ofry** [comment]
Also crashes when just taking screenshot through Quick menu.
