### ISSUE TITLE
Segfaults in some cores when you use unzip feature

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#1389]
Fceumm and Prosystem have problem to open a rom if you use unzip feature from RA, It segfaults.

```
Opening cartridge file /home/sergio/Games/Atari 7800/Asteroids (USA).zip#Asteroids (USA).a78.Cartridge.cpp
Failed to open the cartridge file /home/sergio/Games/Atari 7800/Asteroids (USA).zip#Asteroids (USA).a78 for reading.Cartridge.cpp
RetroArch [ERROR] :: load_content :: Failed to load content.
RetroArch: video_monitor_compute_fps_statistics: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x000000000044633b in ?? ()
No symbol table info available.
#2  0x0000000000410517 in ?? ()
No symbol table info available.
#3  0x0000000000414ce5 in ?? ()
No symbol table info available.
#4  0x000000000046938a in ?? ()
No symbol table info available.
#5  0x000000000041981c in ?? ()
No symbol table info available.
#6  0x000000000040e1c5 in ?? ()
No symbol table info available.
#7  0x00007ffff284dec5 in __libc_start_main (main=0x40e130, argc=1, argv=0x7fffffffdf88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdf78) at libc-start.c:287
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 2926026198984591536, 4252215, 140737488347008, 0, 0, -2926026197935159120, -2926019953044977488}, mask_was_saved = 0}}, 
          priv = {pad = {0x0, 0x0, 0x4b2460, 0x7fffffffdf88}, data = {prev = 0x0, cleanup = 0x0, canceltype = 4924512}}}
        not_first_call = <optimized out>
#8  0x000000000040e260 in ?? ()
No symbol table info available.
```

**Comment by sergiobenrocha2** [comment]
It's working in 1.2.1
