### ISSUE TITLE
Segmentation fault when all options hidden in Main Menu (flatpak/AppImage)

### ISSUE THREAD

**Issue by Heliozoa** [libretro/RetroArch#14175]
## Description
It seems that when there are no items to show in the Main Menu, RetroArch will crash with a segfault when trying to display the menu (i.e. on startup).

### Expected behavior
A "No Settings Found" message like in the Settings menu.

### Actual behavior
Crash. The AppImage gives me a segfault message, the flatpak has the same issue but exits with no message.

### Steps to reproduce the bug

1. Set retroarch.cfg to
```
desktop_menu_enable = "false"
menu_show_configurations = "false"
menu_show_information = "false"
menu_show_load_content = "false"
menu_show_load_core = "false"
menu_show_online_updater = "false"
menu_show_quit_retroarch = "false"
menu_show_restart_retroarch = "false"
menu_show_help = "false"
```
3. Open RetroArch

### Bisect Results
I was able to reproduce this on the following commits from flathub
- 46541577f1445c083bc64aaae1414d524c910f75453d561d7f0db349c0ffb2af
- 98033f26c7e424fdd38d54267df4a32581662b1b64e46b62f44b6a37181bab89
- 9c860d5e26ad883c2a5b1128950ae9734fba4e8ecbde8bff23f76a993a5c4485

### Version/Commit
- RetroArch: 46541577f1445c083bc64aaae1414d524c910f75453d561d7f0db349c0ffb2af

### Environment information
- OS: Pop!_OS 22.04 LTS

**Comment by LibretroAdmin** [comment]
Can reproduce this. Not sure yet how to go about fixing it.

**Comment by gouchi** [comment]
Backtrace gives
```

menu_entry_get (entry=0x7fffffffcf30, stack_idx=0, i=0, userdata=0x0, use_representation=false) at menu/menu_driver.c:386
386	  path                       = list->list[i].path;
(gdb) bt
#0  menu_entry_get (entry=0x7fffffffcf30, stack_idx=0, i=0, userdata=0x0, use_representation=false) at menu/menu_driver.c:386
#1  0x0000555555970412 in generic_menu_iterate (menu_st=0x5555568f4740 <menu_driver_state>, p_disp=0x55555689f5c0 <dispgfx_st>, p_anim=0x55555689f6a0 <anim_st>, settings=0x7fffe57c2010, 
    menu=0x5555585e3430, userdata=0x5555585f1470, action=MENU_ACTION_NOOP, current_time=21534041786) at menu/menu_driver.c:7300
#2  0x0000555555971f79 in menu_driver_iterate (menu_st=0x5555568f4740 <menu_driver_state>, p_disp=0x55555689f5c0 <dispgfx_st>, p_anim=0x55555689f6a0 <anim_st>, settings=0x7fffe57c2010, 
    action=MENU_ACTION_NOOP, current_time=21534041786) at menu/menu_driver.c:7868
#3  0x000055555562a114 in runloop_check_state (error_on_init=false, settings=0x7fffe57c2010, current_time=21534041786) at runloop.c:5971
#4  0x000055555562cad7 in runloop_iterate () at runloop.c:6950
#5  0x0000555555617e1a in rarch_main (argc=1, argv=0x7fffffffdfa8, data=0x0) at retroarch.c:5938
#6  0x0000555555617e7c in main (argc=1, argv=0x7fffffffdfa8) at retroarch.c:6028
```

**Comment by LibretroAdmin** [comment]
Resolved
