### ISSUE TITLE
Segfault on RaspberryPi2

### ISSUE THREAD

**Issue by blackawps** [libretro/RetroArch#1454]
So I just compiled this on my raspberry pi 2, and whenever I try to run it I get a segfault. I ran it in verbose mode in GDB and here's the output..

```
(gdb) run
Starting program: /usr/bin/retroarch --menu --verbose
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
rarch_main_init: === Build =======================================
Compiler: GCC (4.9.2) 32-bit
Built: Feb 26 2015
rarch_main_init: Version: 1.1
rarch_main_init: Git: 26c1020
rarch_main_init: =================================================
RetroArch: rarch_get_cpu_features: [CPUID]: Features:
RetroArch: open_default_config_file: Looking for config in: "/home/jake/.config/retroarch/retroarch.cfg".
config_load_file: === Config ===
RetroArch: config_file_dump_all: config_save_on_exit = "true"
config_load_file: === Config end ===
RetroArch [WARN] :: config_load_file :: system_directory is not set in config. Assuming system directory is same folder as game: "".
RetroArch: parse_config_file: Loading config from: /home/jake/.config/retroarch/retroarch.cfg.
RetroArch: rarch_environment_cb: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch: verify_api_version: Version of libretro API: 1
RetroArch: verify_api_version: Compiled against API: 1
RetroArch: audio_monitor_adjust_system_rates: Set audio input rate to: 29975.00 Hz.
RetroArch: init_video: Video @ 960x720

Program received signal SIGSEGV, Segmentation fault.
0x76a894b4 in strcasecmp () from /usr/lib/libc.so.6
(gdb) bt
#0  0x76a894b4 in strcasecmp () from /usr/lib/libc.so.6
#1  0x76b17984 in _nl_C_LC_CTYPE_tolower () from /usr/lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

I compiled it via a package build on the AUR here: https://aur.archlinux.org/packages/re/retroarch-git-rpi/PKGBUILD

and just changed "armv6h" to "armv7h"

**Comment by blackawps** [comment]
So apparently one of the latest commits causes this. I went back to a commit 3 days ago and now it works fine. To be more specific, I went to commit 29b2508

**Comment by amigagamer** [comment]
same problem here- segfault on launch on RPI2 on yesterdays builds

I compile on the PI2/Raspbian with the following settings
./configure --disable-x11 --enable-floathard --enable-neon --disable-ffmpeg --disable-netplay --enable-udev --disable-sdl --disable-pulse --disable-oss

Ive gone back to my previous build from 21 Feb which is working fine.


I

**Comment by twinaphex** [comment]
That isnt going to solve anything. Do a proper git bisect to identify which commit caused it.

**Comment by tobiasjakobi** [comment]
@blackawps: The backtrace contains almost no valuable information. Try to rebuild the binary with debug information and do another bt.

**Comment by gizmo98** [comment]
Same issue here. I tried to use vg-video instead of gl-video. Makes no difference.

**Comment by joolswills** [comment]
I'll bisect it.

**Comment by joolswills** [comment]
Git bisecting points to this commit 

https://github.com/libretro/RetroArch/commit/aafc64772408c1a4fa7e0621d66782ad197e55da

**Comment by twinaphex** [comment]
Yeah, that seems to mesh with eariler reports I've had about something having gone wrong after that commit. No idea _why_ yet though - it should only be implemented on platforms where we care about setting the resolution explicitly, so it goes unimplemented for most graphics context drivers. It was mainly added so that the PS3 and Wii's resolution setting code is properly abstracted.

Can you by any chance get a gdb backtrace so that we can see where exactly it crashes?

**Comment by joolswills** [comment]
Will do.

**Comment by joolswills** [comment]
```

**Comment by joolswills** [comment]
```
#0  0xb6b144f0 in strcasecmp () from /lib/arm-linux-gnueabihf/libc.so.6
No symbol table info available.
#1  0x000b91b8 in find_gfx_ctx_driver_index (ident=0x14ba68 "")
    at gfx/video_context_driver.c:89
        i = 0
#2  0x000b950c in gfx_ctx_find_driver (data=0x2d1930, ident=0x14ba68 "", 
    api=GFX_CTX_OPENGL_ES_API, major=0, minor=0, hw_render_ctx=false)
    at gfx/video_context_driver.c:193
        ctx = 0x0
        i = -1229160448
#3  0x000b962c in gfx_ctx_init_first (data=0x2d1930, ident=0x14ba68 "", 
    api=GFX_CTX_OPENGL_ES_API, major=0, minor=0, hw_render_ctx=false)
    at gfx/video_context_driver.c:228
No locals.
#4  0x000b6250 in gl_get_context (gl=0x2d1930) at gfx/drivers/gl.c:2051
        cb = 0x27b718
        major = 0
        minor = 0
        api = GFX_CTX_OPENGL_ES_API
        api_name = 0x132eb0 "OpenGL ES 2.0"
#5  0x000b62f4 in gl_init (video=0xbefff53c, input=0x14b8ec, input_data=0x14b924)
    at gfx/drivers/gl.c:2209
        win_width = 181308
        win_height = 0
        force_smooth = false
        gl = 0x2d1930
        ctx_driver = 0x0
        vendor = 0x0
        renderer = 0x0
        version = 0x0
        hw_render = 0x0
        __FUNCTION__ = "gl_init"
#6  0x0002b7c4 in init_video () at gfx/video_driver.c:489
        max_dim = 320
        scale = 2
        width = 960
        height = 720
        custom_vp = 0x28d9a8
        tmp = 0x140a0c
        geom = 0x27a070
        video = {width = 960, height = 720, fullscreen = false, vsync = true, 
          force_aspect = true, vfilter = false, smooth = true, input_scale = 2, 
          rgb32 = false}
        dummy_pixels = {0 <repeats 32 times>}
        __FUNCTION__ = "init_video"
#7  0x0002eaf8 in init_drivers (flags=127) at driver.c:312
No locals.
#8  0x0001affc in rarch_main_command (cmd=74) at retroarch.c:2480
        i = 0
        boolean = false
        __FUNCTION__ = "rarch_main_command"
#9  0x000194b0 in rarch_main_init (argc=2, argv=0xbefff884) at retroarch.c:1867
        sjlj_ret = 0
        __FUNCTION__ = "rarch_main_init"
#10 0x00011688 in main_load_content (argc=2, argv=0xbefff884, args=0x0, environ_get=0, 
    process_args=0) at frontend/frontend.c:239
        i = 101792
        retval = true
        ret = 0
        rarch_argc = 0
        rarch_argv = {0x0 <repeats 32 times>}
        argv_copy = {0x0 <repeats 32 times>}
        rarch_argv_ptr = 0xbefff884
        rarch_argc_ptr = 0xbefff5ec
        wrap_args = 0x2ac108
        __FUNCTION__ = "main_load_content"
#11 0x0001184c in main (argc=2, argv=0xbefff884) at frontend/frontend.c:287
        args = 0x0
        ret = 0
        __FUNCTION__ = "main"

```

**Comment by joolswills** [comment]
That was made from version fedf5f1a6b73184c8d40733df21d202a61822e29

**Comment by twinaphex** [comment]
Can you do a make clean and try again? I am really struggling to see anything here that might have caused any regression here. Looks OK to @Alcaro too.

**Comment by joolswills** [comment]
The previous backtrace was made after doing make clean as I had to build with debugging. I just tried it again, and the backtrace is the same. I can provide remote access to a pi if useful for debugging.

**Comment by twinaphex** [comment]
I noticed one possible issue with the VideoCore EGL context driver.

https://github.com/libretro/RetroArch/commit/fdd7d8be8823d8c2c7b8cae037f11a3af0371e76

Try to see if that commit fixes it.

**Comment by joolswills** [comment]
That has sorted it - thanks :)

**Comment by twinaphex** [comment]
OK, sounds good.

@blackawps - can you confirm it works now with this latest commit? If so, you can close the issue.

**Comment by blackawps** [comment]
Yep, all is good now.
