### ISSUE TITLE
RetroArch crashes when clicking "Information" in "History" tab or in quick menu

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#14809]
## Description

As the title says RetroArch crashes when clicking "Information" in "History" tab or in quick menu.

ASAN output:
```
libretro-common/compat/compat_strl.c:38:32: runtime error: load of null pointer of type 'const char'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==30698==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55abaf114c7e bp 0x7ffd63bce520 sp 0x7ffd63bce4e0 T0)
==30698==The signal is caused by a READ memory access.
==30698==Hint: address points to the zero page.
    #0 0x55abaf114c7e in strlcpy_retro__ libretro-common/compat/compat_strl.c:38
    #1 0x55abaf7a5b77 in menu_displaylist_parse_content_information menu/menu_displaylist.c:4774
    #2 0x55abaf7eb5cb in menu_displaylist_ctl menu/menu_displaylist.c:11912
    #3 0x55abaf70fd1a in deferred_push_dlist menu/cbs/menu_cbs_deferred_push.c:74
    #4 0x55abaf71056d in deferred_push_information menu/cbs/menu_cbs_deferred_push.c:121
    #5 0x55abaf67dbfc in menu_driver_displaylist_push menu/menu_driver.c:2492
    #6 0x55abaf6ba840 in generic_menu_entry_action menu/menu_driver.c:8109
    #7 0x55abaf4e971b in ozone_menu_entry_action menu/drivers/ozone.c:8210
    #8 0x55abaf68d617 in menu_entry_action menu/menu_driver.c:4405
    #9 0x55abaf6b5e1b in generic_menu_iterate menu/menu_driver.c:7814
    #10 0x55abaf6bbf78 in menu_driver_iterate menu/menu_driver.c:8286
    #11 0x55abaeb3fd27 in runloop_check_state /home/bobby/Documents/RetroArch/runloop.c:6941
    #12 0x55abaeb4a49b in runloop_iterate /home/bobby/Documents/RetroArch/runloop.c:7773
    #13 0x55abaeae209f in rarch_main /home/bobby/Documents/RetroArch/retroarch.c:3885
    #14 0x55abaeae217b in main /home/bobby/Documents/RetroArch/retroarch.c:3971
    #15 0x7f5ffd6bfd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #16 0x7f5ffd6bfe3f in __libc_start_main_impl ../csu/libc-start.c:392
    #17 0x55abaeaabcd4 in _start (/home/bobby/Documents/RetroArch/retroarch+0x4bc0cd4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV libretro-common/compat/compat_strl.c:38 in strlcpy_retro__
==30698==ABORTING
```

### Steps to reproduce the bug

1. Go to "History" tab, select a game and click "Information". Alternatively you can just start a game then "Quick Menu > Information".
2. RetroArch should crash.

### Bisect Results

First bad commit: 7d81be1d4c71148c4a3d3e492b9032b504e8a32f

### Environment information

- OS: Windows 10 / Linux Mint 21.1

**Comment by hizzlekizzle** [comment]
Ah, @sonninnos , got any ideas here?

**Comment by sonninnos** [comment]
Oops, just the usual trivialities :F
