### ISSUE TITLE
crashing directly after start

### ISSUE THREAD

**Issue by treakiandroid** [libretro/RetroArch#1496]
Log-Bericht

```
build.board: herring
build.bootloader: I9020XXLC2
build.brand: Google
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: crespo
build.display: cm_crespo-userdebug 4.4.2 KVT49L 4182a2d618 test-keys
build.fingerprint: google/soju/crespo:4.1.2/JZO54K/485486:user/release-keys
build.hardware: herring
build.host: cyanogenmod
build.id: KVT49L
build.manufacturer: Samsung
build.model: Nexus S
build.product: soju
build.radio: unknown
build.serial: 3334DB72EFC600EC
build.tags: test-keys
build.time: 1396716656000
build.type: userdebug
build.user: jenkins
version.codename: REL
version.incremental: 4182a2d618
version.release: 4.4.2
version.sdk_int: 19

03-13 10:50:47.945 D/org.fdroid.fdroid.AppDetails(5474): Getting application details for com.retroarch
03-13 10:51:10.453 D/org.fdroid.fdroid.net.ApkDownloader(5474): Downloading apk from https://f-droid.org/repo/com.retroarch_37.apk
03-13 10:51:10.461 I/org.fdroid.fdroid.net.HttpDownloader(5474): Downloading from https://f-droid.org/repo/com.retroarch_37.apk
03-13 10:51:29.457 D/FDroid  (5474): Using cached apk at /storage/sdcard0/Android/data/org.fdroid.fdroid/cache/apks/com.retroarch_37.apk
03-13 10:51:29.457 D/FDroid  (5474): Download finished: /storage/sdcard0/Android/data/org.fdroid.fdroid/cache/apks/com.retroarch_37.apk
03-13 10:51:29.500 I/ActivityManager(424): START u0 {act=android.intent.action.INSTALL_PACKAGE dat=file:///storage/sdcard0/Android/data/org.fdroid.fdroid/cache/apks/com.retroarch_37.apk cmp=com.android.packageinstaller/.PackageInstallerActivity (has extras)} from pid 5474
03-13 10:51:40.886 I/ActivityManager(424): START u0 {dat=file:///storage/sdcard0/Android/data/org.fdroid.fdroid/cache/apks/com.retroarch_37.apk flg=0x2000000 cmp=com.android.packageinstaller/.InstallAppProgress (has extras)} from pid 5647
03-13 10:51:41.582 W/ActivityManager(424): No content provider found for permission revoke: file:///storage/sdcard0/Android/data/org.fdroid.fdroid/cache/apks/com.retroarch_37.apk
03-13 10:51:53.875 W/ActivityManager(424): No content provider found for permission revoke: file:///storage/sdcard0/Android/data/org.fdroid.fdroid/cache/apks/com.retroarch_37.apk
03-13 10:51:58.507 I/PackageManager(424): Running dexopt on: com.retroarch
03-13 10:52:01.578 I/ActivityManager(424): Force stopping com.retroarch appid=10151 user=-1: update pkg
03-13 10:52:03.757 D/BackupManagerService(424): Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.retroarch flg=0x4000010 (has extras) }
03-13 10:52:03.820 I/ThemeManager(1146): Handling new theme package: com.retroarch
03-13 10:52:07.121 D/FDroid  (5474): Installer package name for com.retroarch set successfully
03-13 10:52:07.121 D/org.fdroid.fdroid.AppDetails(5474): Getting application details for com.retroarch
03-13 10:52:14.379 D/FDroid  (5474): PackageReceiver received [action = 'android.intent.action.PACKAGE_ADDED', data = 'package:com.retroarch']
03-13 10:52:14.566 D/FDroid  (5474): Inserting installed app info for 'com.retroarch' (v37)
03-13 10:52:14.847 D/org.fdroid.fdroid.AppDetails(5474): Getting application details for com.retroarch
03-13 10:52:23.761 D/org.fdroid.fdroid.AppDetails(5474): Getting application details for com.retroarch
03-13 10:53:51.035 I/ActivityManager(1203): Timeline: Activity_launch_request id:com.retroarch time:19403000
03-13 10:53:51.035 I/ActivityManager(424): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.retroarch/.browser.mainmenu.MainMenuActivity} from pid 1203
03-13 10:53:51.453 I/ActivityManager(424): Start proc com.retroarch for activity com.retroarch/.browser.mainmenu.MainMenuActivity: pid=5962 uid=10151 gids={50151, 1028, 1015, 1006, 3003}
03-13 10:53:51.824 I/MainMenuFragment(5962): Extracting RetroArch assets from: /data/app/com.retroarch-1.apk ...
03-13 10:53:51.828 W/dalvikvm(5962): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/retroarch/browser/NativeInterface;
03-13 10:53:51.836 E/AndroidRuntime(5962): Process: com.retroarch, PID: 5962
03-13 10:53:51.836 E/AndroidRuntime(5962): java.lang.UnsatisfiedLinkError: Couldn't load retroarch-jni from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.retroarch-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.retroarch-1, /vendor/lib, /system/lib]]]: findLibrary returned null
03-13 10:53:51.836 E/AndroidRuntime(5962): 	at com.retroarch.browser.NativeInterface.<clinit>(NativeInterface.java:9)
03-13 10:53:51.836 E/AndroidRuntime(5962): 	at com.retroarch.browser.mainmenu.MainMenuFragment.extractAssetsThread(MainMenuFragment.java:138)
03-13 10:53:51.836 E/AndroidRuntime(5962): 	at com.retroarch.browser.mainmenu.MainMenuFragment.access$000(MainMenuFragment.java:43)
03-13 10:53:51.836 E/AndroidRuntime(5962): 	at com.retroarch.browser.mainmenu.MainMenuFragment$1.run(MainMenuFragment.java:114)
03-13 10:53:51.929 W/ActivityManager(424):   Force finishing activity com.retroarch/.browser.mainmenu.MainMenuActivity
03-13 10:53:52.246 I/WindowManager(424): Screenshot max retries 4 of Token{422b6db8 ActivityRecord{41eb99a0 u0 com.retroarch/.browser.mainmenu.MainMenuActivity t21 f}} appWin=Window{424f0f28 u0 Starting com.retroarch} drawState=4
03-13 10:53:52.765 W/ActivityManager(424): Activity pause timeout for ActivityRecord{41eb99a0 u0 com.retroarch/.browser.mainmenu.MainMenuActivity t21 f}
03-13 10:53:54.187 I/ActivityManager(424): Process com.retroarch (pid 5962) has died.
03-13 10:53:54.195 I/ActivityManager(424): Timeline: Activity_windows_visible id: ActivityRecord{41eb99a0 u0 com.retroarch/.browser.mainmenu.MainMenuActivity t21 f} time:19406161
03-13 10:53:54.215 I/WindowState(424): WIN DEATH: Window{425c94b8 u0 com.retroarch/com.retroarch.browser.mainmenu.MainMenuActivity}
03-13 10:53:54.222 I/WindowState(424): WIN DEATH: Window{425d4438 u0 com.retroarch/com.retroarch.browser.mainmenu.MainMenuActivity}
03-13 10:53:54.230 I/WindowState(424): WIN DEATH: Window{42523a48 u0 com.retroarch/com.retroarch.browser.mainmenu.MainMenuActivity}
03-13 10:53:55.078 I/ActivityManager(1203): Timeline: Activity_launch_request id:com.retroarch time:19407045
03-13 10:53:55.078 I/ActivityManager(424): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.retroarch/.browser.mainmenu.MainMenuActivity} from pid 1203
03-13 10:53:55.246 I/ActivityManager(424): Start proc com.retroarch for activity com.retroarch/.browser.mainmenu.MainMenuActivity: pid=5986 uid=10151 gids={50151, 1028, 1015, 1006, 3003}
03-13 10:53:55.531 I/MainMenuFragment(5986): Extracting RetroArch assets from: /data/app/com.retroarch-1.apk ...
03-13 10:53:55.547 W/dalvikvm(5986): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/retroarch/browser/NativeInterface;
03-13 10:53:55.550 E/AndroidRuntime(5986): Process: com.retroarch, PID: 5986
03-13 10:53:55.550 E/AndroidRuntime(5986): java.lang.UnsatisfiedLinkError: Couldn't load retroarch-jni from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.retroarch-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.retroarch-1, /vendor/lib, /system/lib]]]: findLibrary returned null
03-13 10:53:55.550 E/AndroidRuntime(5986): 	at com.retroarch.browser.NativeInterface.<clinit>(NativeInterface.java:9)
03-13 10:53:55.550 E/AndroidRuntime(5986): 	at com.retroarch.browser.mainmenu.MainMenuFragment.extractAssetsThread(MainMenuFragment.java:138)
03-13 10:53:55.550 E/AndroidRuntime(5986): 	at com.retroarch.browser.mainmenu.MainMenuFragment.access$000(MainMenuFragment.java:43)
03-13 10:53:55.550 E/AndroidRuntime(5986): 	at com.retroarch.browser.mainmenu.MainMenuFragment$1.run(MainMenuFragment.java:114)
03-13 10:53:55.566 W/ActivityManager(424):   Force finishing activity com.retroarch/.browser.mainmenu.MainMenuActivity
03-13 10:53:57.363 I/ActivityManager(424): Timeline: Activity_windows_visible id: ActivityRecord{41ee1da8 u0 com.retroarch/.browser.mainmenu.MainMenuActivity t22 f} time:19409330
03-13 10:53:57.382 E/WindowManager(5986): android.view.WindowLeaked: Activity com.retroarch.browser.mainmenu.MainMenuActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{41edaa78 V.E..... R....... 0,0-480,224} that was originally added here
03-13 10:53:57.382 E/WindowManager(5986): 	at com.retroarch.browser.mainmenu.MainMenuFragment.extractAssets(MainMenuFragment.java:126)
03-13 10:53:57.382 E/WindowManager(5986): 	at com.retroarch.browser.mainmenu.MainMenuFragment.onCreate(MainMenuFragment.java:77)
03-13 10:53:57.617 I/ActivityManager(424): Process com.retroarch (pid 5986) has died.

```

**Comment by twinaphex** [comment]
"03-13 10:53:55.550 E/AndroidRuntime(5986): java.lang.UnsatisfiedLinkError: Couldn't load retroarch-jni from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.retroarch-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.retroarch-1, /vendor/lib, /system/lib]]]: findLibrary returned null"

Seems like you're doing something wrong packaging-wise.

**Comment by treakiandroid** [comment]
i didnt build anything, the package is from fdroid. see https://f-droid.org/repository/browse/?fdfilter=RetroArch&fdid=com.retroarch for more details.

if they build it wrong please inform them how to fix it. 

thanks a lot

**Comment by twinaphex** [comment]
They should just use RetroArch 1.1 when it comes out verbatim. There is no reason to edit it anymore in that release, it comes with all the cores taken out and instead you download the cores through the Core Updater. If they want to enforce only GPL-licensed cores can be downloaded, then they can just take RA, change the buildbot URL to point to their own and host only GPL compatible cores there. None of this is hard to do, only thing it requires is a HTTP server serving raw files and an .index hidden file within the same directory, a plain text file containing a listing of all the files in the directory. I already went well out of my way here to rectify what to f-droid was previously a concern so it would be only fitting to return the favor and move forward in this manner. I would prefer (if necessary at all) only a very shallow fork in the future so that mistakes like this dont then become a maintenance and support issue for us.
