### ISSUE TITLE
v1.15.0 CTD when menu 'Contentless Cores' is browsed while a download is in progress.

### ISSUE THREAD

**Issue by Veritas83** [libretro/RetroArch#15119]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Starting a update of all installed cores.
Browse the menu while this happening.
Upon arriving at 'Contentless Cores' a CTD will always occur.

### Expected behavior
Not CTD.

### Actual behavior
CTD.

### Steps to reproduce the bug

1) Start a update of all installed cores.
2) Browse the menu while this happening.
3) Upon arriving at 'Contentless Cores' a CTD will always occur.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
Git Commit: 1581ece

- RetroArch: [version/commit]
v1.15.0 Release

### Environment information
Win10 x64

**Comment by Veritas83** [comment]
In the latest NIGHTLY 38b884b I was able to browse 'Contentless Cores' while a download/core update was in progress once. but upon scrolling back up it crashed.

**Comment by Kvn0l** [comment]
I noticed something like this, both Linux and Android with 1.15.0, it crash if internet fails while downloading any core

**Comment by gouchi** [comment]
Indeed I reproduce the issue on Linux.
```
Main menu > Online Updater > Update Installed Cores
Go to Contentless Cores > Browse cores
```

<details>
   <summary>Debug</summary>
 
 ```
#0  0x0000555555844657 in menu_contentless_cores_get_info ()
#1  0x0000555555820da1 in menu_action_sublabel_contentless_core ()
#2  0x00005555557ed925 in menu_entry_get ()
#3  0x000055555579b774 in xmb_draw_item.constprop ()
#4  0x000055555579f4b1 in xmb_draw_items.constprop ()
#5  0x00005555557a051d in xmb_frame ()
#6  0x000055555588bcb2 in vulkan_frame ()
#7  0x0000555555690dcc in video_driver_frame ()
#8  0x000055555568ebd3 in video_driver_cached_frame ()
#9  0x00005555555f9180 in runloop_iterate ()
#10 0x00005555555efa85 in rarch_main ()
#11 0x00007ffff543c790 in  () at /usr/lib/libc.so.6
#12 0x00007ffff543c84a in __libc_start_main () at /usr/lib/libc.so.6
#13 0x00005555555e0dd5 in _start ()
 ```
 
</details>

<details>
   <summary>Debug ASAN</summary>
 
 ```
menu/menu_contentless_cores.c:208:12: runtime error: member access within null pointer of type 'struct contentless_cores_state_t'

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x000055555b50871d in menu_contentless_cores_get_info (core_id=0x6020003c9130 "mrboom_libretro", info=0x7fffffff7a80) at menu/menu_contentless_cores.c:208
208	  *info = RHMAP_GET_STR(contentless_cores_state->info_entries, core_id);
 ```
 
</details>

[Source](https://github.com/libretro/RetroArch/blob/e5737ce18d529163abee444e567db2934f4baafd/menu/menu_contentless_cores.c#L208)
