### ISSUE TITLE
[Wayland] Any core crashes if you use the game focus button or you have 'Auto Enable Game Focus Mode' set to ON

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#15127]
## Description

Title. Happens in the wayland compositor in vulkan or gl graphic driver or sdl2 or udev input driver, so i expect it has to do with the wayland compositor.

### Expected behavior

No crash.

### Actual behavior
```
i3@sleipnir:~/Documents/Games_2/Bloodlines$ gdb /home/i3/Documents/Projects/RetroArch/retroarch
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/i3/Documents/Projects/RetroArch/retroarch...
(No debugging symbols found in /home/i3/Documents/Projects/RetroArch/retroarch)
(gdb) r
Starting program: /home/i3/Documents/Projects/RetroArch/retroarch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[INFO] RetroArch 1.15.0 (Git 693435a6de)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Mar 22 2023
[INFO] Version: 1.15.0
[INFO] Git: 693435a6de
[INFO] =================================================
[New Thread 0x7ffff64b4640 (LWP 125174)]
[INFO] [Input]: Found input driver: "sdl2".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] [Wayland]: Compositor doesn't support zwp_idle_inhibit_manager_v1 protocol
[INFO] [Wayland]: Compositor doesn't support zxdg_decoration_manager_v1 protocol
[New Thread 0x7ffff537a640 (LWP 125176)]
[Thread 0x7ffff537a640 (LWP 125176) exited]
[New Thread 0x7ffff537a640 (LWP 125177)]
[New Thread 0x7ffff4a8c640 (LWP 125178)]
[Thread 0x7ffff537a640 (LWP 125177) exited]
[Thread 0x7ffff4a8c640 (LWP 125178) exited]
[New Thread 0x7ffff4a8c640 (LWP 125179)]
[New Thread 0x7ffff537a640 (LWP 125180)]
[Thread 0x7ffff4a8c640 (LWP 125179) exited]
[Thread 0x7ffff537a640 (LWP 125180) exited]
[INFO] [Vulkan]: Vulkan dynamic library loaded.
[INFO] [Vulkan]: Found vulkan context: "vk_wayland".
[INFO] [Vulkan]: Detecting screen resolution: 1920x1080.
[New Thread 0x7ffff537a640 (LWP 125181)]
[INFO] [Vulkan]: Found GPU at index 0: "Intel(R) UHD Graphics 620 (KBL GT2)".
[INFO] [Vulkan]: Found GPU at index 1: "llvmpipe (LLVM 15.0.6, 256 bits)".
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using semaphores for WSI acquire.
[INFO] [Vulkan]: Using GPU: "Intel(R) UHD Graphics 620 (KBL GT2)".
[INFO] [Vulkan]: Queue family 0 supports 1 sub-queues.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Wayland]: Auto fullscreen on display "CMN" "0x14d4"
[INFO] [Vulkan]: Using resolution 1920x1080.
[INFO] [Vulkan]: Using RGB565 format.
[New Thread 0x7ffff4a8c640 (LWP 125182)]
[New Thread 0x7fffdd901640 (LWP 125183)]
[New Thread 0x7fffdd100640 (LWP 125184)]
[INFO] [Vulkan]: Loading stock shader.
[INFO] [Joypad]: Found joypad driver: "sdl2".
[INFO] [Video]: Found display server: "null".
[New Thread 0x7fffcffff640 (LWP 125185)]
[INFO] [PulseAudio]: Requested 24960 bytes buffer, got 18720.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Playlist]: Loading history file: "/home/i3/.config/retroarch/content_history.lpl".
[INFO] [Playlist]: Loading history file: "/home/i3/.config/retroarch/content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "/home/i3/.config/retroarch/content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "/home/i3/.config/retroarch/content_favorites.lpl".
[INFO] [PulseAudio]: Pausing.
[INFO] [Content]: Updating firmware status for: "/home/i3/.config/retroarch/cores/scummvm_libretro.so" on "/home/i3/.config/retroarch/system".
[INFO] [Core]: No content, starting dummy core.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[Thread 0x7fffdd100640 (LWP 125184) exited]
[Thread 0x7fffdd901640 (LWP 125183) exited]
[Thread 0x7ffff4a8c640 (LWP 125182) exited]
[Thread 0x7ffff537a640 (LWP 125181) exited]
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[Thread 0x7fffcffff640 (LWP 125185) exited]
[INFO] RetroArch 1.15.0 (Git 693435a6de)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Mar 22 2023
[INFO] Version: 1.15.0
[INFO] Git: 693435a6de
[INFO] =================================================
[Thread 0x7ffff64b4640 (LWP 125174) exited]
[New Thread 0x7ffff64b4640 (LWP 125188)]
[INFO] [Input]: Found input driver: "sdl2".
[INFO] [Core]: Loading dynamic libretro core from: "/home/i3/.config/retroarch/cores/scummvm_libretro.so"
[INFO] [Environ]: SET_SUPPORT_NO_GAME: yes.
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[INFO] [Overrides]: Redirecting save file to "/home/i3/.config/retroarch/saves/ScummVM.srm".
[INFO] [Overrides]: Redirecting save state to "/home/i3/.config/retroarch/states/ScummVM.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SET_AUDIO_BUFFER_STATUS_CALLBACK.
[INFO] [Environ]: GET_CAN_DUPE: true
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Environ]: SET_KEYBOARD_CALLBACK.
[INFO] [Environ]: SYSTEM_DIRECTORY: "/home/i3/.config/retroarch/system".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [State]: found_last_state_slot: #0
[INFO] [Replay]: Found last replay slot: #0
[INFO] [SRAM]: Skipping SRAM load.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48006.28 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] [Wayland]: Compositor doesn't support zwp_idle_inhibit_manager_v1 protocol
[INFO] [Wayland]: Compositor doesn't support zxdg_decoration_manager_v1 protocol
[INFO] [Vulkan]: Vulkan dynamic library loaded.
[INFO] [Vulkan]: Found vulkan context: "vk_wayland".
[INFO] [Vulkan]: Detecting screen resolution: 1920x1080.
[New Thread 0x7fffcffff640 (LWP 125189)]
[INFO] [Vulkan]: Found GPU at index 0: "Intel(R) UHD Graphics 620 (KBL GT2)".
[INFO] [Vulkan]: Found GPU at index 1: "llvmpipe (LLVM 15.0.6, 256 bits)".
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using semaphores for WSI acquire.
[INFO] [Vulkan]: Using GPU: "Intel(R) UHD Graphics 620 (KBL GT2)".
[INFO] [Vulkan]: Queue family 0 supports 1 sub-queues.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Wayland]: Auto fullscreen on display "CMN" "0x14d4"
[INFO] [Vulkan]: Using resolution 1920x1080.
[INFO] [Vulkan]: Using RGB565 format.
[New Thread 0x7fffdd100640 (LWP 125190)]
[INFO] [Vulkan]: Loading stock shader.
[INFO] [Joypad]: Found joypad driver: "sdl2".
[INFO] [Video]: Found display server: "null".
[New Thread 0x7fffdd901640 (LWP 125191)]
[INFO] [PulseAudio]: Requested 24960 bytes buffer, got 18720.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Playlist]: Loading history file: "/home/i3/.config/retroarch/content_history.lpl".
[INFO] [Playlist]: Loading history file: "/home/i3/.config/retroarch/content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "/home/i3/.config/retroarch/content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "/home/i3/.config/retroarch/content_favorites.lpl".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_MINIMUM_AUDIO_LATENCY.
[INFO] [Environ]: Setting audio latency to 160 ms.
[Thread 0x7fffdd901640 (LWP 125191) exited]
[INFO] [Audio]: Set audio input rate to: 48006.28 Hz.
[New Thread 0x7fffdd901640 (LWP 125192)]
[INFO] [PulseAudio]: Requested 61440 bytes buffer, got 38400.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Input]: Game Focus => OFF
[INFO] [Input]: Game Focus => ON
zwp_pointer_constraints_v1@13: error 0: the pointer was already requested to be locked or confined on that surface
[INFO] [Vulkan]: QueuePresent failed, destroying swapchain.

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x0000555555885aab in vulkan_create_swapchain ()
(gdb) bt
#0  0x0000555555885aab in vulkan_create_swapchain ()
#1  0x0000555555886a19 in vulkan_acquire_next_image ()
#2  0x0000555555857d68 in gfx_ctx_wl_swap_buffers ()
#3  0x000055555587f0de in vulkan_frame ()
#4  0x00005555556981d9 in video_driver_frame ()
#5  0x00007fffc2c15f76 in retro_run ()
    at /home/i3/.config/retroarch/cores/scummvm_libretro.so
#6  0x00005555555f5789 in core_run ()
#7  0x00005555555f8245 in runloop_iterate ()
#8  0x00005555555ee145 in rarch_main ()
#9  0x00007ffff70bcd90 in __libc_start_call_main
     (main=main@entry=0x5555555dee90 <main>, argc=argc@entry=1, argv=argv@entry=0x7fffffffdeb8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#10 0x00007ffff70bce40 in __libc_start_main_impl
     (main=0x5555555dee90 <main>, argc=1, argv=0x7fffffffdeb8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdea8)
    at ../csu/libc-start.c:392
#11 0x00005555555df055 in _start ()
(gdb) q
A debugging session is active.

	Inferior 1 [process 125171] will be killed.

Quit anyway? (y or n) y
```
### Steps to reproduce the bug

1. Start any game (i tried a playstation 1 game and the scummvm menu) with the a key to activate game focus configured
2. Press that key

### Version/Commit
```
RetroArch: Frontend for libretro -- v1.15.0 -- 693435a6de --
Compiler: GCC (11.3.0) 64-bit Built: Mar 22 2023
```

@ColinKinloch , since you're most the driving force to update the wayland functionality, i'm calling you, since i doubt it gets fixed otherwise.

**Comment by i30817** [comment]
Just to make sure i built retroarch without wayland (so it's using XWayland in my desktop), and it doesn't crash with the same action, so i _know_ it's the wayland part of retroarch causing the crash, probably the input part.

**Comment by ColinKinloch** [comment]
Where is the Auto Enable Game Focus Mode option? 😄

**Comment by i30817** [comment]
BTW, another strange thing which is not 'game breaking' is that Ozone is 'zoomed' in wayland and not in xwayland. It's likely just a difference of default fonts size, so it's perfectly fine 'not to fix', but just FYI.

**Comment by i30817** [comment]
I just noticed that if it 'crashes' with the Auto Enable Game Focus Mode way, it doesn't actually crash, just exits the core before starting it.

With the button it presents a crash like the above for scummvm, with 'Auto Enable Game Focus Mode' set to ON or Detect and a core like scummvm it just exits retroarch before loading the core and doesn't output a crash.
