### ISSUE TITLE
video_processor core is broken

### ISSUE THREAD

**Issue by kokoko3k** [libretro/RetroArch#16457]
## Description

Cannot use video_processor core

### Expected behavior

See webcam output

### Actual behavior

Core is closed immediately
```
[WARN] Going to default to first input driver...
[INFO] [Overrides]: Redirecting save file to "/home/koko/.config/retroarch/saves/V4L2.srm".
[INFO] [Overrides]: Redirecting save state to "/home/koko/.config/retroarch/states/V4L2.state".
[INFO] [Environ]: SET_SUPPORT_NO_GAME: yes.
[INFO] [Environ]: SET_VARIABLES.
[INFO] [Environ]: SET_VARIABLES.
[ERROR] [Environ]: GET_VARIABLE: videoproc_audiodev - Invalid value.
/dev/video2:
  Driver: uvcvideo
  Card: Integrated_Webcam_5M: Integrate
  Bus Info: usb-0000:00:14.0-6
  Version: 6.7.9
[ERROR] [Environ]: GET_VARIABLE: videoproc_audiodev - Invalid value.
VIDIOC_G_STD failed: Inappropriate ioctl for device
[ERROR] [Content]: Failed to load content
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Core]: Saved core options file to "/home/koko/.config/retroarch/config/V4L2/V4L2.opt".
```
### Steps to reproduce the bug

1. turn on webcam
2. load video_processor core

- RetroArch: [version/commit]
v1.17

- OS: Archlinux

**Comment by hizzlekizzle** [comment]
This has always been a bit wonky, but would you mind trying a build from a few years ago? say, 1.7.3 and see if it treats you any better?

**Comment by kokoko3k** [comment]
Just trtied to compile 1.7.3, but fails on ffmpeg :/

**Comment by kokoko3k** [comment]
1.7.3 gives a nice segmentation fault :)

**Comment by hizzlekizzle** [comment]
yeah, it was a half (or less)-baked feature to begin with that only worked with some webcams, as I recall. We had hoped someone would pick it up and run with it to make it more/fully functional but no one ever did.

**Comment by gouchi** [comment]
Indeed, this core will need some update.

I tried to re-enable it #14969 but I ran  also into a segfault using [v4l2loopback](https://github.com/libretro/RetroArch/issues/14950#issuecomment-1421492146).

**Comment by gouchi** [comment]
Since this [PR](https://github.com/libretro/RetroArch/pull/17799), it seems to stop at "[Hardware doesn't support sample rate](https://github.com/libretro/RetroArch/blob/203fff1a1140d5ce052d7cb113e0a448bef2230f/cores/libretro-video-processor/video_processor_v4l2.c#L506)".

@kokoko3k Do you get the same error ?

@tekdahl Did you succeed to make it work with a webcam ?

Thank you.

**Comment by tekdahl** [comment]
i don't have a webcam so i didn't test it i assume it'd break at the same spot you mentioned. you might get a webcam working by adding an option to skip the audio device logic.

**Comment by gouchi** [comment]
Thank you @tekdahl ! I tried your [branch](https://github.com/tekdahl/RetroArch/tree/tekdahl-videoprocessor-audio) and got some image !

I set a resolution from `v4l2-ctl -d /dev/video0 --list-formats-ext` with this configuration in `~/.config/retroarch/config/V4L2/V4L2.opt`

```
videoproc_audiodev = "none"
videoproc_capture_mode = "alternate"
videoproc_capture_resolution = "640x360"
videoproc_frame_times = "Off"
videoproc_output_mode = "progressive"
videoproc_videodev = "/dev/video0"
```

But if I changed  windowed to fullscreen or close the core, I got a segfault

<details>
  <summary>log</summary>

```
(gdb) bt
#0  0x00007fffce4552c7 in ?? () from /usr/lib/libnvidia-glcore.so.570.133.07
#1  0x00007fffcde81e58 in ?? () from /usr/lib/libnvidia-glcore.so.570.133.07
#2  0x00007fffcdeb63b0 in ?? () from /usr/lib/libnvidia-glcore.so.570.133.07
#3  0x00007fffce47ebab in ?? () from /usr/lib/libnvidia-glcore.so.570.133.07
#4  0x00007fffcdec6536 in ?? () from /usr/lib/libnvidia-glcore.so.570.133.07
#5  0x00007fffcdbc9efb in ?? () from /usr/lib/libnvidia-glcore.so.570.133.07
#6  0x00007fffcdeb88f8 in ?? () from /usr/lib/libnvidia-glcore.so.570.133.07
#7  0x00007fffcdeb8af5 in ?? () from /usr/lib/libnvidia-glcore.so.570.133.07
#8  0x00007fffcdbec4dc in ?? () from /usr/lib/libnvidia-glcore.so.570.133.07
#9  0x00007fffcdbffe65 in ?? () from /usr/lib/libnvidia-glcore.so.570.133.07
#10 0x00007fffcdc001ba in ?? () from /usr/lib/libnvidia-glcore.so.570.133.07
#11 0x0000555555a723c2 in gl3_update_cpu_texture (gl=0x555556f29290, streamed=0x555556f29434, frame=0x5555586f68e0, width=640, height=180, pitch=2560) at gfx/drivers/gl3.c:2562
#12 0x0000555555a72b5e in gl3_frame (data=0x555556f29290, frame=0x5555586f68e0, frame_width=640, frame_height=180, frame_count=0, pitch=2560, msg=0x5555568e8200 <video_driver_msg> "", video_info=0x7fffffffcd80)
    at gfx/drivers/gl3.c:2697
#13 0x000055555579e2c6 in video_driver_frame (data=0x5555586f68e0, width=640, height=180, pitch=2560) at gfx/video_driver.c:4234
#14 0x0000555555f68404 in libretro_videoprocessor_retro_run () at cores/libretro-video-processor/video_processor_v4l2.c:1143
#15 0x000055555563674e in core_run () at runloop.c:7789
#16 0x0000555555635364 in runloop_iterate () at runloop.c:7124
#17 0x00005555556201a3 in rarch_main (argc=2, argv=0x7fffffffdec8, data=0x0) at retroarch.c:5972
#18 0x0000555555620205 in main (argc=2, argv=0x7fffffffdec8) at retroarch.c:6083
```

</details> 

and if I close the core, I got this one

<details>
  <summary>log</summary>

```
(gdb) bt
#0  0x00007ffff44a5624 in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff444bba0 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff4433582 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff44343bf in ?? () from /usr/lib/libc.so.6
#4  0x00007ffff44af765 in ?? () from /usr/lib/libc.so.6
#5  0x00007ffff44afabc in ?? () from /usr/lib/libc.so.6
#6  0x00007ffff44b4a08 in free () from /usr/lib/libc.so.6
#7  0x0000555555f6974d in libretro_videoprocessor_retro_unload_game () at cores/libretro-video-processor/video_processor_v4l2.c:1532
#8  0x000055555562de8e in core_unload_game () at runloop.c:3944
#9  0x000055555562e196 in runloop_event_deinit_core () at runloop.c:4042
#10 0x000055555561c8db in command_event (cmd=CMD_EVENT_CORE_DEINIT, data=0x0) at retroarch.c:4201
#11 0x000055555562421c in retroarch_ctl (state=RARCH_CTL_MAIN_DEINIT, data=0x0) at retroarch.c:8130
#12 0x0000555555753faf in content_load (info=0x7fffffffb170, p_content=0x55555689b660 <runloop_state+1920>) at tasks/task_content.c:1450
#13 0x0000555555754dd3 in task_push_start_dummy_core (content_info=0x7fffffffb170) at tasks/task_content.c:1992
#14 0x000055555561b701 in command_event (cmd=CMD_EVENT_UNLOAD_CORE, data=0x0) at retroarch.c:3653
#15 0x0000555555954704 in generic_action_ok_command (cmd=CMD_EVENT_UNLOAD_CORE) at menu/cbs/menu_cbs_ok.c:2209
#16 0x000055555595cf82 in action_ok_close_content (path=0x7fffffffd0ba "Close Content", label=0x7fffffffd1ba "close_content", type=159, idx=2, entry_idx=0) at menu/cbs/menu_cbs_ok.c:5684
#17 0x000055555594f138 in generic_menu_entry_action (userdata=0x55555814f870, entry=0x7fffffffcea0, i=2, action=MENU_ACTION_OK) at menu/menu_driver.c:7636
#18 0x00005555558b3a25 in xmb_menu_entry_action (userdata=0x55555814f870, entry=0x7fffffffcea0, i=2, action=MENU_ACTION_OK) at menu/drivers/xmb.c:5836
#19 0x0000555555947813 in menu_entry_action (entry=0x7fffffffcea0, i=2, action=MENU_ACTION_OK) at menu/menu_driver.c:4173
#20 0x000055555594e042 in generic_menu_iterate (menu_st=0x55555691ff80 <menu_driver_state>, p_disp=0x5555568e8380 <dispgfx_st>, p_anim=0x5555568e8460 <anim_st>, settings=0x555556a4f6e0, menu=0x555558118c20, 
    userdata=0x55555814f870, action=MENU_ACTION_OK, current_time=977472999) at menu/menu_driver.c:7294
#21 0x000055555594fc61 in menu_driver_iterate (menu_st=0x55555691ff80 <menu_driver_state>, p_disp=0x5555568e8380 <dispgfx_st>, p_anim=0x5555568e8460 <anim_st>, settings=0x555556a4f6e0, action=MENU_ACTION_OK, 
    current_time=977472999) at menu/menu_driver.c:7882
#22 0x0000555555632536 in runloop_check_state (input_st=0x5555568dd3c0 <input_driver_st>, audio_st=0x5555568b2860 <audio_driver_st>, video_st=0x5555568e31c0 <video_driver_st>, 
    uico_st=0x5555568ad160 <uico_driver_st>, error_on_init=false, settings=0x555556a4f6e0, current_time=977472999, netplay_allow_pause=true, netplay_allow_timeskip=true) at runloop.c:6018
#23 0x0000555555634fc6 in runloop_iterate () at runloop.c:7011
#24 0x00005555556201a3 in rarch_main (argc=2, argv=0x7fffffffdec8, data=0x0) at retroarch.c:5972
#25 0x0000555555620205 in main (argc=2, argv=0x7fffffffdec8) at retroarch.c:6083
```
</details>


Running with ASAN debug build, when I load the core I got

<details>
  <summary>log</summary>

```
==22090==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fffdd541e00 at pc 0x7ffff78faf59 bp 0x7fffffffd900 sp 0x7fffffffd0a8
WRITE of size 691200 at 0x7fffdd541e00 thread T0
    #0 0x7ffff78faf58 in memcpy /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors_memintrinsics.inc:115
    #1 0x55555dbc015f in source_v4l2_normal cores/libretro-video-processor/video_processor_v4l2.c:774
    #2 0x55555dbc3bc9 in libretro_videoprocessor_retro_run cores/libretro-video-processor/video_processor_v4l2.c:1074
    #3 0x55555ae99462 in core_run /tmp/RetroArch/runloop.c:7789
    #4 0x55555ae92bf3 in runloop_iterate /tmp/RetroArch/runloop.c:7124
    #5 0x55555ae35bf8 in rarch_main /tmp/RetroArch/retroarch.c:5972
    #6 0x55555ae35cce in main /tmp/RetroArch/retroarch.c:6083
    #7 0x7ffff3635487  (/usr/lib/libc.so.6+0x27487) (BuildId: 0b707b217b15b106c25fe51df3724b25848310c0)
    #8 0x7ffff363554b in __libc_start_main (/usr/lib/libc.so.6+0x2754b) (BuildId: 0b707b217b15b106c25fe51df3724b25848310c0)
    #9 0x55555ade7534 in _start (/tmp/RetroArch/retroarch+0x5893534) (BuildId: 2a080d8c48b77e196ef53999275de85c6c50f5d4)

0x7fffdd541e00 is located 0 bytes after 345600-byte region [0x7fffdd4ed800,0x7fffdd541e00)
allocated by thread T0 here:
    #0 0x7ffff78fd02a in calloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:77
    #1 0x55555dbc62cf in libretro_videoprocessor_retro_load_game cores/libretro-video-processor/video_processor_v4l2.c:1468
    #2 0x55555ae97d9f in core_load_game /tmp/RetroArch/runloop.c:7636
    #3 0x55555afd922a in content_file_load tasks/task_content.c:1131
    #4 0x55555afdae79 in content_file_init tasks/task_content.c:1319
    #5 0x55555afea321 in content_init tasks/task_content.c:3112
    #6 0x55555ae75545 in event_init_content /tmp/RetroArch/runloop.c:4255
    #7 0x55555ae7939d in runloop_event_init_core /tmp/RetroArch/runloop.c:4736
    #8 0x55555ae255e1 in command_event /tmp/RetroArch/retroarch.c:4242
    #9 0x55555ae40fa9 in retroarch_main_init /tmp/RetroArch/retroarch.c:7880
    #10 0x55555afdd611 in content_load tasks/task_content.c:1455
    #11 0x55555afe5db4 in task_load_content_internal tasks/task_content.c:2621
    #12 0x55555afe606f in task_load_content_internal_wrap tasks/task_content.c:2650
    #13 0x55555afe65c8 in task_push_start_builtin_core tasks/task_content.c:2733
    #14 0x55555b93c13e in action_ok_start_video_processor_core menu/cbs/menu_cbs_ok.c:4258
    #15 0x55555b91d16d in generic_menu_entry_action menu/menu_driver.c:7636
    #16 0x55555b680b7e in xmb_menu_entry_action menu/drivers/xmb.c:5836
    #17 0x55555b8f39a8 in menu_entry_action menu/menu_driver.c:4173
    #18 0x55555b917315 in generic_menu_iterate menu/menu_driver.c:7294
    #19 0x55555b920280 in menu_driver_iterate menu/menu_driver.c:7882
    #20 0x55555ae85da3 in runloop_check_state /tmp/RetroArch/runloop.c:6018
    #21 0x55555ae9192c in runloop_iterate /tmp/RetroArch/runloop.c:7011
    #22 0x55555ae35bf8 in rarch_main /tmp/RetroArch/retroarch.c:5972
    #23 0x55555ae35cce in main /tmp/RetroArch/retroarch.c:6083
    #24 0x7ffff3635487  (/usr/lib/libc.so.6+0x27487) (BuildId: 0b707b217b15b106c25fe51df3724b25848310c0)
    #25 0x7ffff363554b in __libc_start_main (/usr/lib/libc.so.6+0x2754b) (BuildId: 0b707b217b15b106c25fe51df3724b25848310c0)
    #26 0x55555ade7534 in _start (/tmp/RetroArch/retroarch+0x5893534) (BuildId: 2a080d8c48b77e196ef53999275de85c6c50f5d4)

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors_memintrinsics.inc:115 in memcpy
Shadow bytes around the buggy address:
  0x7fffdd541b80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7fffdd541c00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7fffdd541c80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7fffdd541d00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7fffdd541d80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x7fffdd541e00:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7fffdd541e80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7fffdd541f00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7fffdd541f80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7fffdd542000: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7fffdd542080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==22090==ABORTING
[Thread 0x7fffdd48f6c0 (LWP 22096) exited]
[Thread 0x7fffe3648200 (LWP 22090) exited]
[Thread 0x7fffc51ff6c0 (LWP 22097) exited]
[New process 22090]
[Inferior 1 (process 22090) exited with code 01]
```

</details>

**Comment by tekdahl** [comment]
no idea, i can't reproduce it locally so feel free to tinker with it.
sometimes if you change settings faster than your device is ready for it'll crash because the device is busy. might be other ways to trigger that kind of behavior.
other than that some of the capture/output modes interact with the resolution/frame rate so maybe changing those would help.
