### ISSUE TITLE
MAME crashing on 1.2

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#1944]
It's happening only in this new version, try load any rom on mame and it will crash.

```
(gdb) bt full
#0  0x0000000000411362 in input_state (port=0, device=3, idx=0, id=97) at libretro_version_1.c:202
        i = 16
        libretro_input_binds = {0x7fffec572098, 0x7fffec579f10, 0x7fffec581d88, 0x7fffec589c00, 0x7fffec591a78, 0x7fffec5998f0, 0x7fffec5a1768, 0x7fffec5a95e0, 0x7fffec5b1458, 
          0x7fffec5b92d0, 0x7fffec5c1148, 0x7fffec5c8fc0, 0x7fffec5d0e38, 0x7fffec5d8cb0, 0x7fffec5e0b28, 0x7fffec5e89a0}
        res = 0
        settings = 0x7fffec567010
        driver = 0x819650
        global = 0x81a7d0
        ol_state = 0x0
#1  0x00007fffdba887d2 in ?? () from /usr/lib/libretro/mame_stable_libretro.so
No symbol table info available.
#2  0x00007fffdba88a09 in retro_run () from /usr/lib/libretro/mame_stable_libretro.so
No symbol table info available.
#3  0x000000000041d3d0 in rarch_main_iterate () at runloop.c:1178
        i = 4
        trigger_input = 0
        old_input = 256
        cmd = {fullscreen_toggle = false, overlay_next_pressed = false, grab_mouse_pressed = false, menu_pressed = false, quit_key_pressed = false, screenshot_pressed = false, 
          mute_pressed = false, osk_pressed = false, volume_up_pressed = false, volume_down_pressed = false, reset_pressed = false, disk_prev_pressed = false, disk_next_pressed = false, 
          disk_eject_pressed = false, movie_record = false, save_state_pressed = false, load_state_pressed = false, slowmotion_pressed = false, shader_next_pressed = false, 
          shader_prev_pressed = false, fastforward_pressed = false, hold_pressed = false, old_hold_pressed = false, state_slot_increase = false, state_slot_decrease = false, 
          pause_pressed = false, frameadvance_pressed = false, rewind_pressed = false, netplay_flip_pressed = false, cheat_index_plus_pressed = false, cheat_index_minus_pressed = false, 
          cheat_toggle_pressed = false}
        ret = 0
        last_input = 0
        input = 0
        driver = 0x819650
        settings = 0x7fffec567010
        global = 0x81a7d0
        system = 0x817860
#4  0x0000000000410b45 in rarch_main (argc=1, argv=0x7fffffffe048, data=0x0) at frontend/frontend.c:343
        args = 0x0
        ret = 0
        settings = 0x7fffec567010
        driver = 0x819650
#5  0x0000000000410b8b in main (argc=1, argv=0x7fffffffe048) at frontend/frontend.c:356
No locals.
```

I can compile mame with debug=1 after. It's happening with mame 0.157 and git version from 2015-04-22

**Comment by ddg1** [comment]
Same problem here. It seems to happen since commit [cdf3ce3](https://github.com/libretro/RetroArch/commit/cdf3ce309e9f12fb2e531ba45a8de2e31f91a11a).

**Comment by fr500** [comment]
just to make it clear, this is mame from master right? not the genie branch

**Comment by sergiobenrocha2** [comment]
It's not the genie branch

**Comment by sergiobenrocha2** [comment]
This mame from 2015-04-22 is the master, last commit libretro/mame@3650f17

**Comment by sergiobenrocha2** [comment]
Fixed
