### ISSUE TITLE
RA segfaults in System Information

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2135]
RA segfaults in the Information --> System

```
(gdb) run
Starting program: /home/sergio/Projects/libretro/retroarch/RetroArch-git/retroarch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
RetroArch [INFO] :: Config: loading config from: /home/sergio/.config/retroarch/retroarch.cfg.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29999.40 Hz.
RetroArch [INFO] :: Found shader "/home/sergio/Projects/libretro/shaders/common-shaders/quilez.cg"
RetroArch [INFO] :: Found shader "/home/sergio/Projects/libretro/shaders/common-shaders/retroarch.cgp"
RetroArch [INFO] :: Found shader "/home/sergio/Projects/libretro/shaders/common-shaders/scanline.cg"
RetroArch [INFO] :: Found shader "/home/sergio/Projects/libretro/shaders/common-shaders/stock.cg"
RetroArch [INFO] :: Video @ fullscreen
RetroArch [INFO] :: Found GL context: glx
RetroArch [INFO] :: Detecting screen resolution 1600x900.
RetroArch [INFO] :: [X11]: Xinerama version: 1.1.
RetroArch [INFO] :: [X11]: Xinerama screens: 1.
RetroArch [INFO] :: [GLX]: Using Xinerama on screen #0.
RetroArch [INFO] :: [GLX]: X = 0, Y = 0, W = 1600, H = 900.
RetroArch [INFO] :: [GLX]: Using windowed fullscreen.
RetroArch [INFO] :: [GLX]: Found swap function: glXSwapIntervalMESA.
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) Haswell Mobile .
RetroArch [INFO] :: [GL]: Version: 3.0 Mesa 10.1.3.
RetroArch [INFO] :: Querying GL extension: ARB_ES2_compatibility => exists
RetroArch [INFO] :: Querying GL extension: ARB_sync => exists
RetroArch [INFO] :: Querying GL extension: ARB_texture_float => exists
RetroArch [INFO] :: Querying GL extension: EXT_texture_sRGB => exists
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_sRGB => exists
RetroArch [INFO] :: GL: Using resolution 1600x900
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [GL]: Not loading any shader.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 0 program(s).
RetroArch [INFO] :: [GL]: Using GL_RGB565 for texture uploads.
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Suspending screensaver (X11).
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[New Thread 0x7fffe5b06700 (LWP 21479)]
RetroArch [INFO] :: [PulseAudio]: Requested 24576 bytes buffer, got 18432.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [INFO] :: null: [/home/sergio/.config/retroarch/history/content_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [INFO] :: [PulseAudio]: Pausing.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2479f59 in __readdir (dirp=0x0) at ../sysdeps/posix/readdir.c:44
44	../sysdeps/posix/readdir.c: No such file or directory.
(gdb) bt full
#0  0x00007ffff2479f59 in __readdir (dirp=0x0) at ../sysdeps/posix/readdir.c:44
        dp = <optimized out>
        saved_errno = 2
#1  0x0000000000422d53 in retro_readdir (rdir=0xbcea70) at libretro-common/file/retro_dirent.c:106
No locals.
#2  0x000000000041075e in frontend_linux_powerstate_check_acpi_sysfs (state=0x7ffffffe89bc, seconds=0x7ffffffe89f8, percent=0x7ffffffe89fc)
    at frontend/drivers/platform_linux.c:1343
        ret = false
        entry = 0xbcea70
        have_battery = false
        have_ac = false
        charging = false
#3  0x0000000000410805 in frontend_linux_get_powerstate (seconds=0x7ffffffe89f8, percent=0x7ffffffe89fc) at frontend/drivers/platform_linux.c:1390
        ret = FRONTEND_POWERSTATE_NONE
#4  0x00000000004cee39 in menu_displaylist_parse_system_info (info=0x7fffffff0b90) at menu/menu_displaylist.c:499
        seconds = 0
        percent = 96
        state = FRONTEND_POWERSTATE_NONE
        major = 3
        minor = 14
        controller = 16
        feat_str = '\000' <repeats 4095 times>
        tmp = "RetroRating level : -1\000\064\000x\000t", '\000' <repeats 4067 times>
        tmp2 = "Linux", '\000' <repeats 4090 times>
        tmp_string = 0x0
        frontend = 0x7cc520 <frontend_ctx_linux>
        settings = 0x7fffec567010
#5  0x00000000004d57b6 in menu_displaylist_push_list (info=0x7fffffff0b90, type=43) at menu/menu_displaylist.c:2693
        i = 0
        list_size = 17179869184
        ret = 0
        need_sort = false
        need_refresh = false
        need_push = false
        setting = 0x0
        menu = 0x105b260
        nav = 0x1070c70
        global = 0x7d0140 <g_extern>
        settings = 0x7fffec567010
        system = 0x84f860
#6  0x00000000004c58fc in deferred_push_system_information (info=0x7fffffff0b90) at menu/cbs/menu_cbs_deferred_push.c:40
No locals.
#7  0x00000000004d6287 in menu_displaylist_push (list=0x1070ea0, menu_list=0x1070e80) at menu/menu_displaylist.c:2936
        cbs = 0xa99100
        path = 0xa98f00 "system_information"
        label = 0xa98ee0 "system_information"
        hash_label = 544128783
        type = 36
        info = {list = 0x1070ea0, menu_list = 0x1070e80, path = "system_information", '\000' <repeats 4077 times>, path_b = '\000' <repeats 4095 times>, 
          path_c = '\000' <repeats 4095 times>, label = "system_information", '\000' <repeats 4077 times>, exts = '\000' <repeats 4095 times>, type = 36, type_default = 0, 
          directory_ptr = 0, flags = 0, setting = 0x0}
        _menu_list = 0x1070e60
#8  0x00000000004c3b30 in action_refresh_default (list=0x1070ea0, menu_list=0x1070e80) at menu/cbs/menu_cbs_refresh.c:24
No locals.
#9  0x00000000004a5cc5 in menu_entry_action (entry=0x7fffffff5cb0, i=1, action=MENU_ACTION_OK) at menu/menu_entry.c:430
        ret = 0
        nav = 0x1070c70
        menu_list = 0x1070e60
        cbs = 0x10702f0
#10 0x00000000004ca7ab in menu_iterate (render_this_frame=true, action=4) at menu/menu_iterate.c:506
        entry = {path = "System Information\000 available.", '\000' <repeats 1074 times>..., 
          label = "system_information\000?\000\000\251>\000\200:?\000\000\251>\000\000\064?\000\000\234>\000\200:?\000\000\234>\000\000\064?\000\000\234>\000\200:?\000\000\251>\000\000\000\000\000\000\320=\000\000\000\000\000\000\320=\000\000\000\000\000\000\320=\000\000\000\000\000\000\320=\000\000\000\000\000\000\320=\000\000\000\000\000\000\320=\000\000\020>\000\000v>\000\000\060>\000\000v>\000\000\020>\000\000P>\000\000\060>\000\000P>\000\000\020>\000\000P>\000\000\060>\000\000v>\000\000\064?\000\000\251>\000\200:?\000\000\251>\000\000\064?\000\000\234>\000\200:?\000\000\234>\000\000\064?\000\000\234>"..., value = '\000' <repeats 3152 times>..., entry_idx = 0, idx = 1, type = 36, spacing = 0}
        iterate_type = ITERATE_TYPE_DEFAULT
        selected = 1
        label = 0x14c8d80 "information_list"
        ret = 0
        hash = 576615942
        menu = 0x105b260
        nav = 0x1070c70
        disp = 0x105f288
        menu_list = 0x1070e60
#11 0x000000000041e0d2 in rarch_main_iterate (sleep_ms=0x7fffffffdde0) at runloop.c:1082
        menu = 0x105b260
        i = 0
        trigger_input = 256
        cmd = {fullscreen_toggle = false, overlay_next_pressed = false, grab_mouse_pressed = false, menu_pressed = false, quit_key_pressed = false, screenshot_pressed = false, 
          mute_pressed = false, osk_pressed = false, volume_up_pressed = false, volume_down_pressed = false, reset_pressed = false, disk_prev_pressed = false, 
          disk_next_pressed = false, disk_eject_pressed = false, movie_record = false, save_state_pressed = false, load_state_pressed = false, slowmotion_pressed = false, 
          shader_next_pressed = false, shader_prev_pressed = false, fastforward_pressed = false, hold_pressed = false, old_hold_pressed = false, state_slot_increase = false, 
          state_slot_decrease = false, pause_pressed = false, frameadvance_pressed = false, rewind_pressed = false, netplay_flip_pressed = false, 
          cheat_index_plus_pressed = false, cheat_index_minus_pressed = false, cheat_toggle_pressed = false}
        do_quit = false
        last_input = 256
        driver = 0x7fc660 <g_driver>
        settings = 0x7fffec567010
        global = 0x7d0140 <g_extern>
        input = 256
        system = 0x84f860
        old_input = 0
#12 0x00000000004118f5 in rarch_main (argc=1, argv=0x7fffffffdf18, data=0x0) at frontend/frontend.c:345
        sleep_ms = 0
        args = 0x0
        ret = 1
        settings = 0x7fffec567010
        driver = 0x7fc660 <g_driver>
#13 0x0000000000411952 in main (argc=1, argv=0x7fffffffdf18) at frontend/frontend.c:361
No locals.
```

Ubuntu 14.04.

**Comment by fr500** [comment]
Can you bisect this?

**Comment by sergiobenrocha2** [comment]
87ece39 broke it

**Comment by twinaphex** [comment]
Works fine here on Arch Linux.

**Comment by twinaphex** [comment]
Check if these last two commits fixed anything for you.

**Comment by sergiobenrocha2** [comment]
Fixed, thanks.
