### ISSUE TITLE
[RPI2] [Retropie] mupen64 doesn't work with latest RA

### ISSUE THREAD

**Issue by nemo93** [libretro/RetroArch#2140]
Hi,

FYI if I build latest RA on my Retropie setup and also the latest mupen64 (https://github.com/libretro/mupen64plus-libretro) then this core will never launch a single ROM. It just send me back to Retropie. I have to stick with RA and mupen64 core shipped with Retropie which is absolutely fine. Just wanted to give you a heads up. cheers

**Comment by sergiobenrocha2** [comment]
The right place to report this: https://github.com/libretro/mupen64plus-libretro/issues

**Comment by nemo93** [comment]
ooops sorry. This is now done! 

https://github.com/libretro/mupen64plus-libretro/issues/267

**Comment by joolswills** [comment]
Turns out it works with older retroarch so I bisected it to 0bf8a36d5027190dc34d65f7f1c63e2efb664571

```
0bf8a36d5027190dc34d65f7f1c63e2efb664571 is the first bad commit
commit 0bf8a36d5027190dc34d65f7f1c63e2efb664571
Author: twinaphex <libretro@gmail.com>
Date:   Mon Aug 17 20:51:12 2015 +0200

    Fix RGUI fallback - if threaded video wrapper was enabled,
    we could not grab an ident resembling 'd3d' or 'gl'

:040000 040000 81156ac823d7ae18e2454cd63a5bcbc2d68932bf 968eae16f2e2e9b68ac45caf5974b2743bffda93 M  gfx
:040000 040000 f31838d633a48f0fb1d45b5d99e5e4ef14fea96d 6636b6bde1b320fff3c4515d964924a9a8fb665c M  menu
```

Before this commit, the latest mupen64-plus works

**Comment by twinaphex** [comment]
Run it through gdb to see why it actually fails. We need to come up with a fix for whatever segfault is going on because we cannot undo the contents of that patch, it is necessary for other parts of RA to function correctly.

**Comment by joolswills** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00103230 in rarch_threaded_video_get_ident () at gfx/video_thread_wrapper.c:1149
1149	   return thr->driver->ident;
(gdb) bt
#0  0x00103230 in rarch_threaded_video_get_ident () at gfx/video_thread_wrapper.c:1149
#1  0x000d4db4 in menu_video_get_ident () at menu/menu_video.c:102
#2  0x00036bc8 in init_menu () at menu/menu_driver.c:192
#3  0x0003879c in init_drivers (flags=127) at driver.c:408
#4  0x0001ce88 in event_command (cmd=EVENT_CMD_DRIVERS_INIT) at command_event.c:1407
#5  0x00018278 in rarch_main_init (argc=9, argv=0x7efff754) at retroarch.c:1183
#6  0x00013de8 in main_load_content (argc=9, argv=0x7efff754, args=0x0, environ_get=0x13020 <frontend_linux_get_env>, 
    process_args=0) at frontend/frontend.c:260
#7  0x00013f8c in rarch_main (argc=9, argv=0x7efff754, data=0x0) at frontend/frontend.c:315
#8  0x00014150 in main (argc=9, argv=0x7efff754) at frontend/frontend.c:366
(gdb) bt full
#0  0x00103230 in rarch_threaded_video_get_ident () at gfx/video_thread_wrapper.c:1149
        driver = 0x1dbd44
        thr = 0x240ec8
#1  0x000d4db4 in menu_video_get_ident () at menu/menu_video.c:102
        settings = 0x7678c008
#2  0x00036bc8 in init_menu () at menu/menu_driver.c:192
        video_driver = 0x1c67ec ""
        driver = 0x1dbd44
#3  0x0003879c in init_drivers (flags=127) at driver.c:408
        driver = 0x1dbd44
        system = 0x22c008
#4  0x0001ce88 in event_command (cmd=EVENT_CMD_DRIVERS_INIT) at command_event.c:1407
        i = 0
        boolean = false
        driver = 0x1dbd44
        global = 0x1b07a8
        settings = 0x7678c008
        system = 0x22c008
#5  0x00018278 in rarch_main_init (argc=9, argv=0x7efff754) at retroarch.c:1183
        sjlj_ret = 0
        global = 0x1b07a8
#6  0x00013de8 in main_load_content (argc=9, argv=0x7efff754, args=0x0, environ_get=0x13020 <frontend_linux_get_env>, 
    process_args=0) at frontend/frontend.c:260
        i = 98132
        retval = true
        ret = 0
        rarch_argc = 0
        rarch_argv = {0x0 <repeats 32 times>}
        argv_copy = {0x0 <repeats 32 times>}
        rarch_argv_ptr = 0x7efff754
        rarch_argc_ptr = 0x7efff48c
        global = 0x1b07a8
        wrap_args = 0x230948
#7  0x00013f8c in rarch_main (argc=9, argv=0x7efff754, data=0x0) at frontend/frontend.c:315
        args = 0x0
        ret = 0
        settings = 0x0
        driver = 0x1dbd44
#8  0x00014150 in main (argc=9, argv=0x7efff754) at frontend/frontend.c:366
No locals.
```

**Comment by joolswills** [comment]
Let me know if you need me to dump the contents of any variables/structs etc

**Comment by twinaphex** [comment]
My first guess is a possible NULL pointer dereference.

See if this makes any difference.

https://github.com/libretro/RetroArch/commit/5bf91c92cb55962d055170b55e04ce144212ad92

**Comment by joolswills** [comment]
That fixed it - thanks.
