### ISSUE TITLE
Audio Devices Seg Faults on Linux

### ISSUE THREAD

**Issue by CanadianJeff** [libretro/RetroArch#2202]
(gdb) run
Starting program: /usr/local/bin/retroarch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe6447700 (LWP 6081)]

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) bt
0  strlen () at ../sysdeps/x86_64/strlen.S:106

Full Backtrace: https://bpaste.net/show/310aa7980379

**Comment by sergiobenrocha2** [comment]
I can't reproduce that, at least with the ubuntu package from the PPA. What audio driver are you using? Pulse? Alsa?

Also, what's version of retroarch? git master?

**Comment by CanadianJeff** [comment]
I used the PPA https://launchpad.net/~libretro/+archive/ubuntu/testing

I think Pulseaudio and Alsa

libsdl has been giving me major problems of late

**Comment by sergiobenrocha2** [comment]
```
Starting program: /usr/local/bin/retroarch
```
Are you sure you are using from the PPA?

**Comment by CanadianJeff** [comment]
oh in the IRC they said to try the git clone and make from source thats why

same seg fault on both PPA and GIT

**Comment by CanadianJeff** [comment]
also this just happend when I pressed on IP Address under network?

https://bpaste.net/show/2c69732e0d91

**Comment by sergiobenrocha2** [comment]
You installed RA from the PPA, and you used this right?

```
gdb retroarch
```
The PPA doesn't install stuff at /usr/local/bin/

**Comment by Alcaro** [comment]
He compiled from source and used make install, that's why it's in /usr/local/bin/. He used the PPA at first, which ended up in /usr/bin/, but I told him to compile from source so we can get sensible backtraces.

**Comment by sergiobenrocha2** [comment]
I tested with all audio drivers, all works except jack (which I need to change some config in the system I guess).

**Comment by sergiobenrocha2** [comment]
I'm getting the same backtrace if I try to choose Settings --> Audio --> Audio Device

```
(gdb) bt full
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
No locals.
#1  0x000000000047e6e0 in xmb_frame_messagebox (message=0x7fffffffac00 "\n") at menu/drivers/xmb.c:530
        width = 1366
        height = 768
        xmb = 0xc8ac60
        x = <optimized out>
        font_size = 22
        gl = <optimized out>
        menu = <optimized out>
        y = <optimized out>
        i = <optimized out>
        list = 0x10b9d90
#2  xmb_frame () at menu/drivers/xmb.c:1663
        selection = 8
        mymat = {data = {2, 0, 0, 0, 0, 2, 0, 0, 0, 0, -1, 0, -1, -1, 0, 1}}
        mrot = {data = {1, 0, 0, 0, -0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1}}
        mscal = {data = {1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1}}
        depth = <optimized out>
        i = <optimized out>
        width = 1366
        height = 768
        msg = "\n", '\000' <repete 4055 vezes>...
        title_msg = "1.2.2 - No Core ", '\000' <repete 472 vezes>...
        timedate = "2015-10-03 15:54:00\000\000\000\000\000\070\260U\353\377\177\000\000\000\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\360E\212\000\000\000\000\000\245\354\345\353\377\177\000\000\070\260U\353\377\177\000\000\070\260U\353\377\177\000\000\220F\210", '\000' <repete 13 vezes>, "H\352U\353\377\177\000\000I\212\352\353\377\177\000\000\b\000\000\000\000\000\000\000 %\205\000\000\000\000\000\270(\205\000\000\000\000\000@\215\000\000\000\000\000\000\001\000\000\000\000\000\000\000\070\226\350\353\377\177\000\000\260\314\377\377\377\177\000\001 %\205\000\000\000\000\000\350\003\000\000\000\000\000\000\v\000\000\000\000\000\000\000\070\260U\353\377\177\000\000"...
        item_color = {1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0}
        coord_color = {0, 0, 0, 0,75, 0, 0, 0, 0,75, 0, 0, 0, 0,75, 0, 0, 0, 0,75}
        coord_color2 = {1 <repeats 16 times>}
        display_kb = true
        render_background = <optimized out>
        xmb = 0xc8ac60
        gl = 0x842290
        menu = 0xc83c10
        menu_list = <optimized out>
        settings = 0x7fffec565010
#3  0x00000000004e4785 in gl_frame (data=0x842290, frame=<optimized out>, frame_width=4, frame_height=4, frame_count=622, pitch=8, msg=0x7c1ba0 <g_driver+320> "") at gfx/drivers/gl.c:1791
        is_slowmotion = false
        is_paused = false
        width = 1366
        height = 768
        feedback_info = {tex = 4, input_size = {4, 4}, tex_size = {512, 512}, coord = {0, 0, 0,0078125, 0, 0, 0,0078125, 0,0078125, 0,0078125}}
        frame_run = {ident = 0x55c0a3 "frame_run", start = 0, total = 0, call_cnt = 0, registered = false}
        gl = 0x842290
        driver = 0x7c1a60 <g_driver>
        settings = 0x7fffec565010
        font_driver = 0x795640 <gl_raster_font>
#4  0x0000000000412ddb in video_frame (data=0x7bd8e0 <dummy_pixels>, width=4, height=4, pitch=8) at libretro_version_1.c:107
        frame_count = 0x7bd920 <video_frame_count>
        output_width = 0
        output_height = 0
        output_pitch = 0
        msg = <optimized out>
        driver = 0x7c1a60 <g_driver>
        global = 0x7963c0 <g_extern>
        settings = <optimized out>
        video = 0x7955a0 <video_gl>
#5  0x0000000000428a34 in video_driver_cached_frame () at gfx/video_driver.c:860
        is_idle = false
        driver = 0x7c1a60 <g_driver>
        recording = 0x0
#6  0x00000000004c3505 in menu_display_ctl (state=state@entry=MENU_DISPLAY_CTL_LIBRETRO, data=data@entry=0x0) at menu/menu_display.c:269
        width = 3965383792
        height = 7949984
        settings = 0x7fffec565010
#7  0x00000000004cc9bc in menu_iterate_render () at menu/drivers/menu_generic.c:359
        is_idle = false
        driver = 0x794ea0 <menu_ctx_xmb>
        menu = 0xc83c10
#8  0x000000000041d04f in rarch_main_data_menu_iterate () at runloop_data.c:219
No locals.
#9  rarch_main_data_iterate () at runloop_data.c:254
        settings = 0x7fffec565010
#10 0x00000000004125a3 in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:350
        sleep_ms = 0
        args = 0x0
        ret = 0
        settings = 0x7fffec565010
        driver = <optimized out>
#11 0x00007ffff23ddec5 in __libc_start_main (main=0x40f080 <main>, argc=1, argv=0x7fffffffe048, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe038) at libc-start.c:287
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 136681458475313539, 4255879, 140737488347200, 0, 0, -136681457385100925, -136669895298930301}, mask_was_saved = 0}}, priv = {pad = {
              0x0, 0x0, 0x5136c0 <__libc_csu_init>, 0x7fffffffe048}, data = {prev = 0x0, cleanup = 0x0, canceltype = 5322432}}}
        not_first_call = <optimized out>
#12 0x000000000040f0b0 in _start ()
No symbol table info available.
```

**Comment by sergiobenrocha2** [comment]
0b9f167 broke it @twinaphex

**Comment by twinaphex** [comment]
Check if these latest commits fix it - I no longer get garbled text when setting the Audio Device -

https://github.com/libretro/RetroArch/commit/8d705844deeec7110f0d4c62af157446c203e29b

**Comment by sergiobenrocha2** [comment]
Fixed.

**Comment by twinaphex** [comment]
OK, thanks. Can the OP confirm this on his end too - @CanadianJeff?

**Comment by CanadianJeff** [comment]
no longer segfaults thank you
