### ISSUE TITLE
Segfault when no core can handle chosen rom?

### ISSUE THREAD

**Issue by CanadianJeff** [libretro/RetroArch#2211]
```
Program received signal SIGSEGV, Segmentation fault.
gl_frame (data=0x0, frame=0x7b6660 <dummy_pixels>, frame_width=4, frame_height=4, frame_count=2128, pitch=8, 
    msg=0x7ba920 <g_driver+320> "Failed to load Kirby's Adventure (USA).zip.\n") at gfx/drivers/gl.c:1653
1653	   if (gl->core_context)
(gdb) bt full
#0  gl_frame (data=0x0, frame=0x7b6660 <dummy_pixels>, frame_width=4, frame_height=4, frame_count=2128, pitch=8, 
    msg=0x7ba920 <g_driver+320> "Failed to load Kirby's Adventure (USA).zip.\n") at gfx/drivers/gl.c:1653
        is_slowmotion = 160
        is_paused = false
        width = 960
        height = 720
        feedback_info = {tex = 4, input_size = {4, -7.46839214e-06}, tex_size = {4.03530087e+16, 0}, coord = {0, 1.41740779e-38, 
            0, -nan(0x7fd980), 4.59163468e-41, -nan(0x7fd990), 4.59163468e-41, -nan(0x7fd9a0)}}
        frame_run = {ident = 0x5569a3 "frame_run", start = 0, total = 0, call_cnt = 0, registered = false}
        gl = 0x0
        driver = 0x7ba7e0 <g_driver>
        settings = 0x854750
        font_driver = 0x78e460 <gl_raster_font>
#1  0x000000000041161b in video_frame (data=0x7b6660 <dummy_pixels>, width=4, height=4, pitch=8) at libretro_version_1.c:107
        frame_count = 0x7b66a0 <video_frame_count>
        output_width = 0
        output_height = 0
        output_pitch = 0
        msg = <optimized out>
        driver = 0x7ba7e0 <g_driver>
        global = 0x78f140 <g_extern>
        settings = <optimized out>
        video = 0x78e3c0 <video_gl>
#2  0x0000000000427274 in video_driver_cached_frame () at gfx/video_driver.c:860
        is_idle = false
        driver = 0x7ba7e0 <g_driver>
        recording = 0x0
#3  0x00000000004c1485 in menu_display_ctl (state=state@entry=MENU_DISPLAY_CTL_LIBRETRO, data=data@entry=0x0)
    at menu/menu_display.c:269
        width = 9038768
        height = 7919968
        settings = 0x854750
#4  0x00000000004ca93c in menu_iterate_render () at menu/drivers/menu_generic.c:359
        is_idle = false
        driver = 0x78d960 <menu_ctx_rgui>
        menu = 0x11c2090
#5  0x000000000041b88f in rarch_main_data_menu_iterate () at runloop_data.c:219
No locals.
#6  rarch_main_data_iterate () at runloop_data.c:254
        settings = 0x854750
#7  0x0000000000410de3 in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:354
        sleep_ms = 0
        args = 0x0
        ret = 0
        settings = 0x854750
        driver = <optimized out>
#8  0x00007ffff2b5cec5 in __libc_start_main (main=0x40dae0 <main>, argc=1, argv=0x7fffffffdc28, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdc18) at libc-start.c:287
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -8552267076957767105, 4250343, 140737488346144, 0, 0, 8552267077909084735, 
                8552295063484627519}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x50ded0 <__libc_csu_init>, 0x7fffffffdc28}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 5299920}}}
        not_first_call = <optimized out>
#9  0x000000000040db10 in _start ()
No symbol table info available.
```

**Comment by fr500** [comment]
There is no context so I'm closing this
