### ISSUE TITLE
PSX Games [No-Intro] File Extension (.bin) (.cue)

### ISSUE THREAD

**Issue by CanadianJeff** [libretro/RetroArch#2246]
using the no-intro .dat file to verify hashes of playstation 1 roms they have 2 files inside the folder or .zip file

  game (country).bin
  game (country).cue

I use clrmamepro to name my games using the no-intro dat file

I see that retroarch uses Mednafen for playstation 1 games but if I goto detect core and select the .bin file for example "Crash Bandicoot - Warped (USA).bin" it only shows gameboy advance mednafen which leads me to think its loading the cores based on file extension?

*note* the game runs 100% just fine using PCSX for ubuntu linux

**Comment by twinaphex** [comment]
Yiu need to load cue, not bin.

**Comment by CanadianJeff** [comment]
doing so caused a segfault but atleast it shows up as mednafen

```
(gdb) run
Starting program: /usr/bin/retroarch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[New Thread 0x7fffe5cd4700 (LWP 23981)]
[Thread 0x7fffe5cd4700 (LWP 23981) exited]
[New Thread 0x7fffe5cd4700 (LWP 23999)]
unhandled setting UI: psx.input.port1.gun_chairs
unhandled setting UI: psx.input.port2.gun_chairs
unhandled setting UI: psx.input.port3.gun_chairs
unhandled setting UI: psx.input.port4.gun_chairs
unhandled setting UI: psx.input.port5.gun_chairs
unhandled setting UI: psx.input.port6.gun_chairs
unhandled setting UI: psx.input.port7.gun_chairs
unhandled setting UI: psx.input.port8.gun_chairs
terminate called after throwing an instance of 'MDFN_Error'
  what():  Error opening file No such file or directory

Program received signal SIGABRT, Aborted.
0x00007ffff24fecc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt full
#0  0x00007ffff24fecc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 23942
        selftid = 23942
#1  0x00007ffff25020d8 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7fffe9ac7a20, sa_sigaction = 0x7fffe9ac7a20}, sa_mask = {__val = {7, 
              10241280, 140737351947607, 140733193388037, 0, 7944680, 140737258515752, 7944680, 10241280, 18735024, 
              140737351976213, 140737352193760, 140737259452557, 1, 140737352196304, 10241136}}, sa_flags = 10, 
          sa_restorer = 0x7ffff7e257c0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff1df7535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff1df56d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff1df5703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007ffff1df5922 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007fffe9855523 in ?? () from /usr/lib/libretro/mednafen_psx_libretro.so
No symbol table info available.
#7  0x00007fffe98613e1 in ?? () from /usr/lib/libretro/mednafen_psx_libretro.so
No symbol table info available.
#8  0x00007fffe9861d9b in ?? () from /usr/lib/libretro/mednafen_psx_libretro.so
No symbol table info available.
#9  0x00007fffe985e7c1 in ?? () from /usr/lib/libretro/mednafen_psx_libretro.so
No symbol table info available.
#10 0x00007fffe9860ba3 in retro_load_game () from /usr/lib/libretro/mednafen_psx_libretro.so
No symbol table info available.

----------- SNIP -----------

#24 0x0000000000411d57 in ?? ()
No symbol table info available.
#25 0x00007ffff24e9ec5 in __libc_start_main (main=0x40ea60, argc=1, argv=0x7fffffffdc38, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdc28) at libc-start.c:287
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 2375677012435319749, 4254311, 140737488346160, 0, 0, -2375677011214156859, 
                -2375651849245115451}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x511fd0, 0x7fffffffdc38}, data = {
              prev = 0x0, cleanup = 0x0, canceltype = 5316560}}}
        not_first_call = <optimized out>
#26 0x000000000040ea90 in ?? ()
No symbol table info available.

```

**Comment by fr500** [comment]
This is most likely a wrong cue or wrong bios case and it's a core issue anyway so it should be opened in the correct repo.

https://github.com/libretro/beetle-psx-libretro
Check the wiki page for information on the core usage 
http://wiki.libretro.com/index.php?title=Beetle/Mednafen_PSX
