### ISSUE TITLE
Segfaults when downloading shaders??

### ISSUE THREAD

**Issue by CanadianJeff** [libretro/RetroArch#2470]
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000045025b in strlcpy_retro__ (dest=dest@entry=0x7fffffffbd00 "\351S", source=source@entry=0x0, size=size@entry=4096)
    at libretro-common/compat/compat_strl.c:38
38	      while (--n && (*dest++ = *source++)) src_size++;
(gdb) bt full
#0  0x000000000045025b in strlcpy_retro__ (dest=dest@entry=0x7fffffffbd00 "\351S", source=source@entry=0x0, size=size@entry=4096)
    at libretro-common/compat/compat_strl.c:38
        src_size = 0
        n = 4095
#1  0x0000000000421dba in fill_pathname_join (out_path=out_path@entry=0x7fffffffbd00 "\351S", dir=dir@entry=0x0, 
    path=path@entry=0x1ffb7e4 "shaders_glsl.zip", size=size@entry=4096) at libretro-common/file/file_path.c:576
No locals.
#2  0x00000000004c172c in cb_generic_download (task_data=0x7fffd4002a50, user_data=0x1ffb7e0, err=0x0)
    at menu/cbs/menu_cbs_deferred_push.c:430
        msg = "\000\000\236>\316\314L=\232\231\237>\316\314L=\000\000\236>\253\252\212=\232\231\237>\253\252\212=\000\000\236>\253\252\212=\232\231\237>\316\314L=gf\242>\316\314L=gf\242>\316\314L=gf\242>\316\314L=gf\242>\316\314L=gf\242>\316\314L=gf\242>\316\314L=\315̪>\316\314L=\315̰>\316\314L=\315̪>xw\227=\315̰>xw\227=\315̪>xw\227=\315̰>\316\314L=gf\262>\316\314L=gf\270>\316\314L=gf\262>xw\227=gf\270>xw\227=gf\262>xw\227=gf\270>\316\314L=\232\231\271>\316\314L=\315\314\300>\316\314"...
        output_path = "\351S\000\000\000\000\000\000\351S\000\000\000\000\000\000@\377\027\352\377\177\000\000\365_\273\357\377\177\000\000\003\000\000\000\000\000\000\000\260L\300\000\000\000\000\000\b\364\277\000\000\000\000\000e~\250\357\377\177\000\000\260L\300\000\000\000\000\000\030M\300\000\000\000\000\000\240\336\277\000\000\000\000\000\001\000\000\000\377\177\000\000p\276\377\377\377\177\000\000\060\276\377\377\377\177\000\000\260L\300\000\000\000\000\000(S\300\000\000\000\000\000H\000\000\000\000\000\000\000$ \257\357\377\177\000\000(Xz\344\377\177\000\000\001", '\000' <repeats 15 times>, "\300̢", '\000' <repeats 13 times>, "\002b\273\357\377\177\000\000\240\336\277\000\000\000\000\000\030M\300"...
        shaderdir = "/home/jefferyw/.config/retroarch/shaders/shaders_glsl", '\000' <repeats 851 times>...
        file_ext = 0x0
        dir_path = 0x0
        transf = 0x1ffb7e0
        settings = <optimized out>
        data = 0x7fffd4002a50
#3  0x000000000041b59d in rarch_task_internal_gather () at tasks/tasks.c:61
No locals.
#4  threaded_gather () at tasks/tasks.c:152
No locals.
#5  0x000000000040fded in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:331
        sleep_ms = 0
        args = 0x0
        ret = 1
        settings = 0x892bd0
        driver = <optimized out>
        global = <optimized out>
#6  0x00007ffff2d78a40 in __libc_start_main (main=0x40c750 <main>, argc=1, argv=0x7fffffffdea8, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde98) at libc-start.c:289
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -8155622679195531653, 4245344, 140737488346784, 0, 0, 8155622248431896187, 
                8155611458002896507}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x5207e0 <__libc_csu_init>, 0x7fffffffdea8}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 5375968}}}
---Type <return> to continue, or q <return> to quit---
        not_first_call = <optimized out>
#7  0x000000000040c789 in _start ()
No symbol table info available.
```

**Comment by fr500** [comment]
works fine here and the shader package is the same for all platforms

**Comment by fr500** [comment]
Yeah it happens, quite weird, there must be some peculiarity in the zip

**Comment by Nerdy314159265** [comment]
I can confirm that it's crashing for both the CG Shaders and GLSL Shaders for me. Both crash the program at ~98-99% complete on download.

**Comment by CanadianJeff** [comment]
a fix for this bug would be...

if the download does not complete verify its MD5 before extracting it

**Comment by CanadianJeff** [comment]
I will attempt to download using wget and watch in wireshark to see whats going wrong

**Comment by CanadianJeff** [comment]
```
jefferyw@xubuntu:/tmp$ wget http://buildbot.libretro.com/assets/frontend/shaders_cg.zip
--2015-11-25 20:00:02--  http://buildbot.libretro.com/assets/frontend/shaders_cg.zip
Resolving buildbot.libretro.com (buildbot.libretro.com)... 104.28.21.83, 104.28.20.83, 2400:cb00:2048:1::681c:1553, ...
Connecting to buildbot.libretro.com (buildbot.libretro.com)|104.28.21.83|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17208610 (16M) [application/zip]
Saving to: ‘shaders_cg.zip’

shaders_cg.zip                   100%[============================================================>]  16.41M  3.32MB/s   in 4.9s   

2015-11-25 20:00:07 (3.36 MB/s) - ‘shaders_cg.zip’ saved [17208610/17208610]
```

```
jefferyw@xubuntu:/tmp$ md5sum shaders_cg.zip 
63f23f462349dc33ecd0b5bccc581172  shaders_cg.zip
jefferyw@xubuntu:/tmp$ sha1sum shaders_cg.zip 
e246457940b8898f06153f31e2aa8b47f5bb1e81  shaders_cg.zip
```

**Comment by hizzlekizzle** [comment]
There's a PR to fix this. Can one of you guys try it?
https://github.com/libretro/RetroArch/pull/2471

**Comment by fr500** [comment]
The PR fixed the issue yeah, if it persists please reopen.
