### ISSUE TITLE
Cheevos Segfaulting yawn.....

### ISSUE THREAD

**Issue by CanadianJeff** [libretro/RetroArch#2477]
```
Program received signal SIGSEGV, Segmentation fault.
cheevos_get_var_value (var=0xcea014) at cheevos.c:922
922	         live_val = memory[0];
(gdb) Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 1414682964 (0x54525954)
 at -e line 15.
Quit
(gdb) 
(gdb) 
(gdb) bt full
#0  cheevos_get_var_value (var=0xcea014) at cheevos.c:922
        previous = <optimized out>
        live_val = 0
#1  cheevos_test_condition (cond=0xce9ff0) at cheevos.c:960
        sval = 0
#2  cheevos_test_cond_set (dirty_conds=dirty_conds@entry=0x7fffffffdc40, reset_conds=reset_conds@entry=0x7fffffffdc44, 
    condset=<optimized out>, condset=<optimized out>, match_any=0) at cheevos.c:1022
        cond_valid = <optimized out>
        set_valid = 0
        end = 0xcea028
        cond = 0xce9ff0
#3  0x000000000051cded in cheevos_test_cheevo (cheevo=0x4ae8d00) at cheevos.c:1103
        reset_conds = 0
        ret_val = 0
        end = 0xd4ded8
        dirty_conds = 0
        ret_val_sub_cond = 1
        condset = 0xd4dec0
        dirty = <optimized out>
#4  cheevos_test_cheevo_set (set=set@entry=0x828528 <cheevos_locals+8>) at cheevos.c:1256
        global = 0x7ad140 <g_extern>
        end = 0x4ae8f40
        cheevo = 0x4ae8d00
#5  0x000000000051f175 in cheevos_test () at cheevos.c:1279
        settings = 0x892bd0
#6  0x000000000041a106 in rarch_main_iterate (sleep_ms=sleep_ms@entry=0x7fffffffdd7c) at runloop.c:968
        i = <optimized out>
        trigger_input = <optimized out>
        cmd = {fullscreen_toggle = false, overlay_next_pressed = false, grab_mouse_pressed = false, menu_pressed = false, 
          quit_key_pressed = false, screenshot_pressed = false, mute_pressed = false, osk_pressed = false, 
          volume_up_pressed = false, volume_down_pressed = false, reset_pressed = false, disk_prev_pressed = false, 
          disk_next_pressed = false, disk_eject_pressed = false, movie_record = false, save_state_pressed = false, 
          load_state_pressed = false, slowmotion_pressed = false, shader_next_pressed = false, shader_prev_pressed = false, 
          fastforward_pressed = false, hold_pressed = false, old_hold_pressed = false, state_slot_increase = false, 
          state_slot_decrease = false, pause_pressed = false, frameadvance_pressed = false, rewind_pressed = false, 
          netplay_flip_pressed = false, cheat_index_plus_pressed = false, cheat_index_minus_pressed = false, 
          cheat_toggle_pressed = false}
        current = <optimized out>
        target = <optimized out>
        to_sleep_ms = <optimized out>
        last_input = 0
        driver = 0x7d87c0 <g_driver>
---Type <return> to continue, or q <return> to quit---
        settings = 0x892bd0
        input = 0
        system = 0x9bb270
        old_input = <optimized out>
#7  0x000000000040fda2 in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:327
        sleep_ms = 0
        args = 0x0
        ret = <optimized out>
        settings = 0x892bd0
        driver = <optimized out>
        global = <optimized out>
#8  0x00007ffff2d78a40 in __libc_start_main (main=0x40c750 <main>, argc=1, argv=0x7fffffffdea8, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde98) at libc-start.c:289
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 2468835131403433193, 4245344, 140737488346784, 0, 0, -2468835561768586007, 
                -2468828618286009111}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x520800 <__libc_csu_init>, 0x7fffffffdea8}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 5376000}}}
        not_first_call = <optimized out>
#9  0x000000000040c789 in _start ()
No symbol table info available.
```

**Comment by leiradel** [comment]
Segfaulting what???

**Comment by fr500** [comment]
@CanadianJeff can you be more explicit on your bug reports and skip the "humor"?
Thanks

**Comment by fr500** [comment]
No feedback, closed feel free to reopen
