### ISSUE TITLE
Segfault on RPI with current retroarch (777f8e94)

### ISSUE THREAD

**Issue by joolswills** [libretro/RetroArch#2495]
Current RetroArch (777f8e94d068209b9a34def99843e28f00454c0b) segfaults on RPI2 in my set up.

configured with

```
./configure --disable-x11 --disable-oss --disable-pulse --disable-al --enable-floathard --enable-neon
```

log & backtrace

```
RetroArch [INFO] :: === Build =======================================RetroArch [INFO] :: [CPUID]: Features:
Built: Nov 29 2015
RetroArch [INFO] :: Version: 1.3.0
RetroArch [INFO] :: Git: 777f8e9
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: [CPUID]: Features:
RetroArch [INFO] :: Config: loading config from: /opt/retropie/configs/nes/retroarch.cfg.
RetroArch [INFO] :: Threaded rarch_task started
RetroArch [INFO] :: Loading dynamic libretro core from: "/opt/retropie/libretrocores/lr-fceumm/fceumm_libretro.so"
RetroArch [INFO] :: Environ SET_VARIABLES.
RetroArch [INFO] :: Remaps: core name: FCEUmm
RetroArch [INFO] :: Remaps: game name: rom
RetroArch [INFO] :: Remaps: remap directory: /opt/retropie/configs/nes/
RetroArch [INFO] :: Remaps: no game-specific remap found at /opt/retropie/configs/nes/FCEUmm/rom.rmp
RetroArch [INFO] :: Remaps: no core-specific remap found at /opt/retropie/configs/nes/FCEUmm/FCEUmm.rmp
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Environ GET_LOG_INTERFACE.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [libretro INFO] ::  :: Frontend supports RGB565 - will use that instead of XRGB1555.
RetroArch [INFO] :: Environ PERFORMANCE_LEVEL: 5.
RetroArch [INFO] :: Content loading skipped. Implementation will load it on its own.
RetroArch [INFO] :: Environ SET_INPUT_DESCRIPTORS:
RetroArch [INFO] :: 	RetroPad, User 1, Button "B (bottom)" => "B"
RetroArch [INFO] :: 	RetroPad, User 1, Button "Select" => "Select"
RetroArch [INFO] :: 	RetroPad, User 1, Button "Start" => "Start"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] :: 	RetroPad, User 1, Button "A (right)" => "A"
RetroArch [INFO] :: 	RetroPad, User 1, Button "X (up)" => "(VSSystem) Insert Coin"
RetroArch [INFO] :: 	RetroPad, User 1, Button "L" => "(FDS) Disk Side Change"
RetroArch [INFO] :: 	RetroPad, User 1, Button "R" => "(FDS) Insert/Eject Disk"
RetroArch [INFO] :: 	RetroPad, User 2, Button "B (bottom)" => "B"
RetroArch [INFO] :: 	RetroPad, User 2, Button "Select" => "Select"
RetroArch [INFO] :: 	RetroPad, User 2, Button "Start" => "Start"
RetroArch [INFO] :: 	RetroPad, User 2, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] :: 	RetroPad, User 2, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] :: 	RetroPad, User 2, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] :: 	RetroPad, User 2, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] :: 	RetroPad, User 2, Button "A (right)" => "A"
RetroArch [INFO] :: 	RetroPad, User 3, Button "B (bottom)" => "B"
RetroArch [INFO] :: 	RetroPad, User 3, Button "Select" => "Select"
RetroArch [INFO] :: 	RetroPad, User 3, Button "Start" => "Start"
RetroArch [INFO] :: 	RetroPad, User 3, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] :: 	RetroPad, User 3, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] :: 	RetroPad, User 3, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] :: 	RetroPad, User 3, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] :: 	RetroPad, User 3, Button "A (right)" => "A"
RetroArch [INFO] :: 	RetroPad, User 4, Button "B (bottom)" => "B"
RetroArch [INFO] :: 	RetroPad, User 4, Button "Select" => "Select"
RetroArch [INFO] :: 	RetroPad, User 4, Button "Start" => "Start"
RetroArch [INFO] :: 	RetroPad, User 4, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] :: 	RetroPad, User 4, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] :: 	RetroPad, User 4, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] :: 	RetroPad, User 4, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] :: 	RetroPad, User 4, Button "A (right)" => "A"
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "/home/pi/RetroPie/BIOS".
RetroArch [libretro INFO] ::  :: Loading ./rom.nes...

RetroArch [libretro INFO] ::  ::  PRG ROM:    2 x 16KiB
RetroArch [libretro INFO] ::  ::  CHR ROM:    1 x  8KiB
RetroArch [libretro INFO] ::  ::  ROM CRC32:  0xd445f698
RetroArch [libretro INFO] ::  ::  ROM MD5:  0x8e3630186e35d477231bf8fd50e54cdd
RetroArch [libretro INFO] ::  ::  Mapper #:  0
RetroArch [libretro INFO] ::  ::  Mapper name: NROM
RetroArch [libretro INFO] ::  ::  Mirroring: Vertical
RetroArch [libretro INFO] ::  ::  Battery-backed: No
RetroArch [libretro INFO] ::  ::  Trained: No
RetroArch [libretro INFO] ::  :: 
RetroArch [INFO] :: Environ GET_VARIABLE nes_palette:
RetroArch [INFO] :: 	asqrealc
RetroArch [INFO] :: Environ GET_VARIABLE nes_nospritelimit:
RetroArch [INFO] :: 	disabled
RetroArch [INFO] :: Environ GET_OVERSCAN: 0
RetroArch [INFO] :: Skipping SRAM load..
RetroArch [INFO] :: Set audio input rate to: 31960.62 Hz.
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/2xBR.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/5xbr-retro.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/5xbr-retro.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/5xbr-retro_phosphor.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/5xBR-v3.5.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/barrel-distortion.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/barrel-distortion.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/barrel-distortion_lanczos4.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/barrel-distortion_phosphor.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/barrel-distortion_snes.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/bead.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/blinky.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/box-1x.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/box-2x.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/box-3x.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/box-4x.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/box-max.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/bsnes_gamma_ramp.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/bsnes_gamma_ramp.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/cgwg-CRT-flat.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/cgwg-CRT-flat.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/crt-pi-barrel.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/crt-pi-mask.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/crt-pi.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/CRT_cgwg.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/CRT_cgwg.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/dot.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/Edge.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/gameboy.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/gameboy2.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/gamma.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/gamma2.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/gb-pass-1.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/gb-pass-2.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/gb-pass-3.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/gb-pass-4.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2x&lcd3x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2x.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2x2.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2x2.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2x_lcd3x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2x_phosphor.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2xwaterpaint.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq2xwaterpaintscanline.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq4x.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq4x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/hq4x_lcd3x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/lcd3x.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/ntsc-pass1.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/ntsc-pass2.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/ntsc-pass3.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/ntsc-pass4.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/ntsc-pass5.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/ntsc.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/phosphor-normalgamma.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/phosphor.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/phosphor.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/pixellate.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/quilez.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/retro-v2.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/retroarch.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/SABR-v1.0.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/scanline.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/sharp-bilinear.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes-hires-blend.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes2.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes3.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_hq2x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_hq2xwaterpaint.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_hq2xwaterpainthicontrast.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_hq2xwaterpaintscanline.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_lcd3x.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_phosphor.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_scanline.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/snes_waterpaint.glslp"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/stock.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/super2xSal.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/water.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/waterpaint-hicontrast.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/waterpaint-scanline.glsl"
RetroArch [INFO] :: Found shader "/opt/retropie/emulators/retroarch/shader/waterpaint.glsl"
RetroArch [INFO] :: Video @ 897x672
RetroArch [INFO] :: Starting threaded video driver ...
RetroArch [INFO] :: [EGL]: EGL version: 1.4
RetroArch [INFO] :: [EGL]: Current context: 0x1.
RetroArch [INFO] :: Found GL context: videocore
RetroArch [INFO] :: Detecting screen resolution 1280x1024.
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
RetroArch [INFO] :: [GL]: Version: OpenGL ES 2.0.
RetroArch [INFO] :: Querying GL extension: ARB_texture_non_power_of_two => doesn't exist
RetroArch [INFO] :: Querying GL extension: OES_texture_npot => exists
RetroArch [INFO] :: Querying GL extension: BGRA8888 => exists
RetroArch [WARN] :: [GL]: GLES implementation does not have BGRA8888 extension.
32-bit path will require conversion.
RetroArch [INFO] :: Querying GL extension: GL_EXT_unpack_subimage => doesn't exist
RetroArch [INFO] :: Querying GL extension: EXT_sRGB => doesn't exist
RetroArch [INFO] :: GL: Using resolution 1280x1024
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [GL]: Using GLSL shader backend.
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: Querying EGL extension: KHR_image => exists
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
RetroArch [INFO] :: [udev] Adding device /dev/input/event1 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev]: Plugged pad: USB,2-axis 8-button gamepad   (0583:2060) on port #0.
RetroArch [INFO] :: Autodetect: 0 profiles found
RetroArch [INFO] :: Autodetect: no profiles found for USB,2-axis 8-button gamepad   (1411/8288)RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event0) supports 0 force feedback effects.
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: [CPUID]: Features:
RetroArch [INFO] :: ALSA: Using signed 16-bit format.
RetroArch [INFO] :: ALSA: Period size: 384 frames
RetroArch [INFO] :: ALSA: Buffer size: 1536 frames
RetroArch [INFO] :: [CPUID]: Features:
Segmentation fault

```

backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x76fd09b8 in memset () from /usr/lib/arm-linux-gnueabihf/libcofi_rpi.so
(gdb) bt full
#0  0x76fd09b8 in memset () from /usr/lib/arm-linux-gnueabihf/libcofi_rpi.so
No symbol table info available.
#1  0x0005aeb8 in video_shader_read_conf_cgp (conf=0x308a10, shader=0x322b58) at gfx/video_shader_parse.c:605
        shaders = 2071686
        i = 1987621016
#2  0x000d5120 in menu_shader_manager_init (menu=0x313f30) at menu/menu_shader.c:86
        ext_hash = 260312199
        ext = 0x7678b0ca "glslp"
        shader = 0x322b58
        conf = 0x308a10
        config_path = 0x1f9c6c "/opt/retropie/configs/nes/retroarch.cfg"
        settings = 0x76789008
        global = 0x1f5c58
#3  0x000977c0 in menu_init (data=0x1f4d2c) at menu/menu.c:267
        menu = 0x313f30
        menu_ctx = 0x1f4d2c
        global = 0x1f5c58
        settings = 0x76789008
#4  0x00097db4 in init_menu () at menu/menu_driver.c:143
        driver = 0x222260
#5  0x00037b34 in init_drivers (flags=127) at driver.c:411
        driver = 0x222260
        system = 0x291008
#6  0x0001cbd0 in event_command (cmd=EVENT_CMD_DRIVERS_INIT) at command_event.c:1464
        i = 0
        boolean = false
        driver = 0x222260
        global = 0x1f5c58
        settings = 0x76789008
        info = 0x291008
#7  0x000177d4 in rarch_main_init (argc=7, argv=0x7efff764) at retroarch.c:1211
        sjlj_ret = 0
        verbosity = 0x222ac4
        global = 0x1f5c58
#8  0x00013c78 in main_load_content (argc=7, argv=0x7efff764, args=0x0, environ_get=0x13118 <frontend_linux_get_env>, process_args=0) at frontend/frontend.c:229
        i = 2697120
        retval = true
        ret = 0
        rarch_argc = 0
        rarch_argv = {0x0 <repeats 32 times>}
        argv_copy = {0x0 <repeats 32 times>}
        rarch_argv_ptr = 0x7efff764
        rarch_argc_ptr = 0x7efff494
        global = 0x1f5c58
        wrap_args = 0x292860
#9  0x00013e4c in rarch_main (argc=7, argv=0x7efff764, data=0x0) at frontend/frontend.c:292
        args = 0x0
        ret = 0
---Type <return> to continue, or q <return> to quit---
        settings = 0x0
        driver = 0x222260
        global = 0x1f5c58
#10 0x0001403c in main (argc=7, argv=0x7efff764) at frontend/frontend.c:347
```

something configuration file / shader related

cat /opt/retropie/configs/nes/retroarch.cfg

```
# Settings made here will only override settings in the global retroarch.cfg if placed above the #include line

input_remapping_directory = /opt/retropie/configs/nes/
# video_smooth = false
video_shader = /opt/retropie/emulators/retroarch/shader/phosphor.glslp
# video_shader_enable = true

#include "/opt/retropie/configs/all/retroarch.cfg"
```

works if I just use the /opt/retropie/configs/all/retroarch.cfg file directly (config - http://pastebin.com/WhZMvv8n).

Bisecting now to see where this broke.

**Comment by joolswills** [comment]
c75885b7b4a328c7bfab97a613badad16b189e2c is the first bad commit
```
commit c75885b7b4a328c7bfab97a613badad16b189e2c
Author: twinaphex <libretro@gmail.com>
Date:   Sun Nov 29 01:15:40 2015 +0100

    Remove gfx/video_driver.h dependency from driver.h

:100644 100644 a72a4fdc1e648e2d2fd94c0a5d7851d964278be2 81efc563d8c916011467065893be09bbc846a758 M	config.def.h
:100644 100644 52171001dadd928158c1f7a6e517e76e8ed7e758 5b42d8a4bbe355b96c8705467be8ac2165268141 M	configuration.h
:100644 100644 1f3bda1bc3328e588c9924c53f4b62150cd46235 09db5848f0e552476aa5c18b166bafee521f42a4 M	driver.h
:040000 040000 fa4c2900eb7a29f5c06c56ed3706216103a675ed a96eb6bd9b265f14b6a122fa4e38f01264dffabc M	gfx
```

**Comment by twinaphex** [comment]
That commit you highlighted doesn't make much sense in terms of why it would no longer work afterwards. I doubt it is the case.

**Comment by twinaphex** [comment]
There seems to be a general issue with loading CGPs right now, maybe that is your problem. Anyway, lots of internal stuff had to change these past few days if we want to have any hope of being able to move forward. Clinging onto bad old code that has countless potential concurrency issues is not a good idea.

Anyway, I'm pretty sure that commit you showed me is not the first bad commit.

**Comment by fr500** [comment]
It's one of these
https://github.com/libretro/RetroArch/commit/c75885b7b4a328c7bfab97a613badad16b189e2c
https://github.com/libretro/RetroArch/commit/0044d853f8640dfe3788c269161ad702287915ce
https://github.com/libretro/RetroArch/commit/50ca3a17d9322b65b8255887abfe122c6b2e2cb2
https://github.com/libretro/RetroArch/commit/127448f848fd90606cb06e1683de597a14ea6b03

**Comment by fr500** [comment]
This is the commit I use for reference
3bad31e513efff9b140f24d8ef01ad22f183fb45

**Comment by twinaphex** [comment]
@joolswills  This solved the issue for me on my end:

https://github.com/libretro/RetroArch/commit/91b40523bd1a1fe29098d6ae47303dfb5bee7049

Try it on your end too.

**Comment by joolswills** [comment]
I can confirm that https://github.com/libretro/RetroArch/commit/91b40523bd1a1fe29098d6ae47303dfb5bee7049 fixes it (I didnt think it should have been https://github.com/libretro/RetroArch/commit/c75885b7b4a328c7bfab97a613badad16b189e2c being the problem either, but reverting it did solve it).

**Comment by joolswills** [comment]
thanks.
