### ISSUE TITLE
Segfault with dispmanx driver on RPI when "video_threaded = true" 

### ISSUE THREAD

**Issue by joolswills** [libretro/RetroArch#2503]
building retroarch c5df156f238f7f3457806bcf30152adbd705a461 - using dispmanx video driver -
with video_threaded = false it works, but with video_threaded = true it segfaults

compiling with 
```
./configure --disable-x11 --disable-oss --disable-pulse --disable-al --enable-floathard --enable-neon --enable-dispmanx; make clean; make DEBUG=1
```

backtrace

```
#1  0x00109e20 in thread_get_current_shader (data=0x2d9cb0) at gfx/video_thread_wrapper.c:1000
        thr = 0x2d9cb0
#2  0x0005963c in video_shader_driver_get_current_shader () at gfx/video_shader_driver.c:81
        video_driver = 0x2d9cb0
        video_poke = 0x1dcbe8
#3  0x000f5bb8 in menu_displaylist_push_list (info=0x7eff93c0, type=4) at menu/menu_displaylist.c:2399
        i = 0
        ret = 0
        menu = 0x2fbbc0
        global = 0x1fac78
        settings = 0x76789008
        system = 0x292008
        shader = 0xc2e64
#4  0x000fc700 in generic_menu_init_list (data=0x2fbbc0) at menu/drivers/menu_generic.c:385
        info = {need_sort = false, need_refresh = false, need_push = false, list = 0x2f0260, menu_list = 0x0, 
          path = '\000' <repeats 4095 times>, path_b = '\000' <repeats 4095 times>, 
          path_c = '\000' <repeats 4095 times>, label = "Main Menu", '\000' <repeats 4086 times>, 
          exts = '\000' <repeats 4095 times>, type = 0, type_default = 0, directory_ptr = 0, flags = 0, 
          setting = 0x0}
        menu_stack = 0x2e4560
        selection_buf = 0x2f0260
#5  0x000985fc in init_menu () at menu/menu_driver.c:147
        driver = 0x223098
#6  0x0003798c in init_drivers (flags=127) at driver.c:411
        driver = 0x223098
        system = 0x292008
#7  0x0001c7ec in event_command (cmd=EVENT_CMD_DRIVERS_INIT) at command_event.c:1301
        i = 0
        boolean = false
        driver = 0x223098
        global = 0x1fac78
        settings = 0x76789008
        info = 0x292008
#8  0x00017c48 in rarch_main_init (argc=7, argv=0x7efff774) at retroarch.c:1240
        sjlj_ret = 0
        verbosity = 0x223928
        global = 0x1fac78
---Type <return> to continue, or q <return> to quit---
#9  0x000140c8 in main_load_content (argc=7, argv=0x7efff774, args=0x0, 
    environ_get=0x13568 <frontend_linux_get_env>, process_args=0) at frontend/frontend.c:228
        i = 2701216
        retval = true
        ret = 0
        rarch_argc = 0
        rarch_argv = {0x0 <repeats 32 times>}
        argv_copy = {0x0 <repeats 32 times>}
        rarch_argv_ptr = 0x7efff774
        rarch_argc_ptr = 0x7efff4a4
        global = 0x1fac78
        wrap_args = 0x293860
#10 0x0001429c in rarch_main (argc=7, argv=0x7efff774, data=0x0) at frontend/frontend.c:291
        args = 0x0
        ret = 0
        settings = 0x0
        driver = 0x223098
        global = 0x1fac78
#11 0x0001448c in main (argc=7, argv=0x7efff774) at frontend/frontend.c:346
```

it did used to work with video_threaded = true - I have git bisected to 
3602d703cc6a01d3f65e7743345f5be06ff1f9b1

```
3602d703cc6a01d3f65e7743345f5be06ff1f9b1 is the first bad commit
commit 3602d703cc6a01d3f65e7743345f5be06ff1f9b1
Author: twinaphex <libretro@gmail.com>
Date:   Tue Oct 20 01:54:04 2015 +0200

    Cleanups

:040000 040000 d5178c36d25e626d218fc88e4ce0218286ae0d6a ef3618d16109d4e8156ed6b26bebd07e85c16fa5 M	menu
```

bisect log

```
git bisect start
# bad: [b8eba00a7e4297a676802c1021635952c0a13236] Reduce scope of global->cheat
git bisect bad b8eba00a7e4297a676802c1021635952c0a13236
# bad: [6a46b4d1ec5e3485aa9636d8a4997854635ae4f6] Lower PATH_MAX_LENGTH to 512 for 3DS/PSP/Wii/Gamecube/Xbox 1
git bisect bad 6a46b4d1ec5e3485aa9636d8a4997854635ae4f6
# good: [f5566cbe3bc02152d5dcd08f0a3323a5ab2ff4ae] Cleanup warnings
git bisect good f5566cbe3bc02152d5dcd08f0a3323a5ab2ff4ae
# good: [16ec2a620e4cfc55001f3afaf4cff871b2b41a65] (libretro-db) Silence warning
git bisect good 16ec2a620e4cfc55001f3afaf4cff871b2b41a65
# bad: [f57675fa40592d7938cdff74a9a2d5293808f5ed] Cleanup cheevos_populate_menu
git bisect bad f57675fa40592d7938cdff74a9a2d5293808f5ed
# bad: [b900fcc0f78a2672ae1a4ec2ab86d5a574a27a71] (Zarch) Cleanups
git bisect bad b900fcc0f78a2672ae1a4ec2ab86d5a574a27a71
# skip: [7f843fe21ee5ee8d4087039c0b9f239f41164f04] Start splitting up accounts options
git bisect skip 7f843fe21ee5ee8d4087039c0b9f239f41164f04
# good: [ab65bec860d4ec6c3d7a50e602effb4ceaa5767e] Add HAVE_MENU ifdefs
git bisect good ab65bec860d4ec6c3d7a50e602effb4ceaa5767e
# good: [0cc83fe8fe7688e2cc331ba99487513887863c10] Cleanups
git bisect good 0cc83fe8fe7688e2cc331ba99487513887863c10
# skip: [d8d18fc886ec4bc596919204b4678594e13291d8] Merge pull request #2272 from pyroesp/Add_File_Check_2
git bisect skip d8d18fc886ec4bc596919204b4678594e13291d8
# bad: [260f2f713c41eaae712374333a6655513ee03523] Merge pull request #2271 from Monroe88/patch-1
git bisect bad 260f2f713c41eaae712374333a6655513ee03523
# bad: [227bb3fe499f194e22da93b75ef2151a07e4ba51] Remove malloc.h
git bisect bad 227bb3fe499f194e22da93b75ef2151a07e4ba51
# good: [5b9aab68e558573f9a8bf543d96f2a57492b0201] (XMB) Start using menu_entries_ functions inside XMB
git bisect good 5b9aab68e558573f9a8bf543d96f2a57492b0201
# good: [4afbd0682b569f055a0969f82147a8a4312e8d4a] (wgl_ctx) Set fullscreen mode refresh rate to video_refresh_rate
git bisect good 4afbd0682b569f055a0969f82147a8a4312e8d4a
# bad: [34cf3c6a1391a58b1bb656951fc37b27622b1276] update osx buildbot url
git bisect bad 34cf3c6a1391a58b1bb656951fc37b27622b1276
# good: [90fae3e2d071e7c810da369a8f4e7c9381bc79d8] Refactor 'Accounts' code - moved to menu_setting.c
git bisect good 90fae3e2d071e7c810da369a8f4e7c9381bc79d8
# bad: [3602d703cc6a01d3f65e7743345f5be06ff1f9b1] Cleanups
git bisect bad 3602d703cc6a01d3f65e7743345f5be06ff1f9b1
# good: [e89708a082d9b8d0050b00b8a4540b0fe30fe0e9] Reorder settings
git bisect good e89708a082d9b8d0050b00b8a4540b0fe30fe0e9
```

**Comment by joolswills** [comment]
This fixes it for me

```diff
diff --git a/menu/menu_displaylist.c b/menu/menu_displaylist.c
index ddc7971..0fcdb60 100644
--- a/menu/menu_displaylist.c
+++ b/menu/menu_displaylist.c
@@ -2196,7 +2196,7 @@ int menu_displaylist_push_list(menu_displaylist_info_t *info, unsigned type)
    settings_t      *settings   = config_get_ptr();
    rarch_system_info_t *system = rarch_system_info_get_ptr();
 #ifdef HAVE_SHADER_MANAGER
-   struct video_shader *shader = video_shader_driver_get_current_shader();
+   struct video_shader *shader;
 #endif
 
    switch (type)
@@ -2457,6 +2457,7 @@ int menu_displaylist_push_list(menu_displaylist_info_t *info, unsigned type)
       case DISPLAYLIST_SHADER_PARAMETERS:
       case DISPLAYLIST_SHADER_PARAMETERS_PRESET:
 #ifdef HAVE_SHADER_MANAGER
+         shader = video_shader_driver_get_current_shader();
          if (shader)
             ret = deferred_push_video_shader_parameters_common(info, shader,
                   (type == DISPLAYLIST_SHADER_PARAMETERS)
```

**Comment by twinaphex** [comment]
See if this works for you -

https://github.com/libretro/RetroArch/commit/b056e809c3f845f3f50a86f38df40003e95a5317

**Comment by joolswills** [comment]
Yep. all good. Cheers.
