### ISSUE TITLE
Segfaults if fails to load a core

### ISSUE THREAD

**Issue by CanadianJeff** [libretro/RetroArch#2608]
steps to reproduce:
```
1) Start Retroarch
2) Pick content from playlist
3) Retroarch attempts to find/load core
4) Missing core so it crashes
```
Possible idea for a fix just warn the user that it failed to find or load a core

Segfault Details Included:
```
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapIntervalEXT(1)
RetroArch [INFO] :: [PulseAudio]: Pausing.

Program received signal SIGSEGV, Segmentation fault.
core_info_find (list=0x0, core=core@entry=0x7fffffff2ca0 "") at core_info.c:558
558	   for (i = 0; i < list->count; i++)
(gdb) bt full
#0  core_info_find (list=0x0, core=core@entry=0x7fffffff2ca0 "") at core_info.c:558
        i = 0
#1  0x00000000004b8ad0 in action_ok_playlist_entry (path=<optimized out>, label=0x7fffffff5d80 "collection", type=<optimized out>, 
    idx=<optimized out>, entry_idx=6) at menu/cbs/menu_cbs_ok.c:559
        list = 0x0
        path_base = <optimized out>
        found_associated_core = false
        new_core_path = '\000' <repeats 48 times>, "collection", '\000' <repeats 1582 times>...
        core_info = 0x0
        selection = 0
        core_name_hash = <optimized out>
        core_path_hash = 2878187678
        entry_path = 0x23e48c0 "/home/jefferyw/.retro/roms/gameboy/Donkey Kong Land (USA, Europe) (SGB Enhanced).zip#Donkey Kong Land (USA, Europe) (SGB Enhanced).gb"
        entry_label = 0x23e4950 "Donkey Kong Land (USA, Europe) (SGB Enhanced)"
        core_path = 0x23eb150 "DETECT"
        core_name = 0x1babba0 "DETECT"
        selection_ptr = 6
        tmp_playlist = 0x23ea970
        playlist = 0x23ea970
        is_history = false
        menu = <optimized out>
        hash_label = <optimized out>
---Type <return> to continue, or q <return> to quit---
#2  0x00000000004a302d in menu_entry_action (entry=entry@entry=0x7fffffff4d80, i=<optimized out>, 
    action=action@entry=MENU_ACTION_OK) at menu/menu_entry.c:382
        ret = 0
        selection_buf = 0x120ad20
        cbs = <optimized out>
#3  0x00000000004ce077 in generic_menu_iterate (data=0x11fc710, userdata=<optimized out>, action=MENU_ACTION_OK)
    at menu/drivers/menu_generic.c:306
        selection = 0
        entry = {
          path = "Run\000\000\000\250=\000\000\236>\000\000\250=\000\000\230>\000\000\250=\000\000\236>\000\000\364=\000\000\344=\000\000n>\000\000\b>\000\000n>\000\000\344=\000\000R>\000\000\b>\000\000R>\000\000\344=\000\000R>\000\000\b>\000\000n>\000\000\205>\000\000D>\000\000\224>\000\000D>\000\000\205>\000\000(>\000\000\224>\000\000(>\000\000\205>\000\000(>\000\000\224>\000\000D>\000\000\230=\000\000D>\000\000\300=\000\000D>\000\000\230=\000\000(>\000\000\300=\000\000(>\000\000\230=\000\000(>\000\000\300=\000\000D>\000\000\000\000\000\000\250=\000\000\000\000\000\000\250=\000\000\000\000\000\000\250="..., 
          label = "collection\000?\316\314L\274\232\231\033?\360\356\231\033?\360\356\231\033?\360\356\231\033?\360\356\231\033?\360\356\231\033?\360\356\356\273\000\000\035?\316\314L\274\063\063\036?\316\314L\274\000\000\035?\360\356\356;33\036?\360\356\356;\000\000\035?\360\356\356;33\036?\316\314L\274\315\314\036?\360\356\356\273\315\314 ?\360\356\356\273\315\314\036?\360\356\356;\315\314 ?\360\356\356;\315\314\036?\360\356\356;\315\314 ?\360\356\356\273\063\063!?\360\356\356\273\063\063#?\360\356\356\273\063\063!?\316\314L;33#?\316\314L;33!?\316\314L;33#?\360\356\356\273gf"..., 
          value = "\000\000\200?\000\000\200?\000\000\200?\000\377\376>\000\000\200?\000\000\200?\000\000\200?\000\377\376>\000\000\200?\000\000\200?\000\000\200?\000\377\376>\000\000\200?\000\000\200?\000\000\200?\000\377\376>\000\000\200?\000\000\200?\000\000\200?\000\377\376>\000\000\200?\000\000\200?\000\000\200?\000\377\376>\000\000\200?\000\000\200?\000\000\200?\000\377\376>\000\000\200?\000\000\200?\000\000\200?\000\377\376>\000\000\200?\000\000\200?\000\000\200?\000\377\376>\000\000\200?\000\000\200?\000\000\200?\0---Type <return> to continue, or q <return> to quit---
00\377\376>\000\000\200?\000\000\200?\000\000\200?\000\377\376>\000\000\200?\000\000\200?\000\000\200?\000\377\376>\000\000\200?\000\000\200?"..., entry_idx = 6, idx = 0, type = 7, spacing = 1065353216}
        label = 0x1215130 "null"
        ret = 0
        label_hash = 0
        hash = <optimized out>
        menu = 0x11fc710
        menu_stack = 0x120ad00
        selection_buf = 0x120ad20
#4  0x0000000000419b70 in runloop_iterate (sleep_ms=sleep_ms@entry=0x7fffffffdeb8) at runloop.c:1359
        focused = true
        is_idle = false
        i = <optimized out>
        cmd = {state = {256, 0, 256}}
        cmd_ptr = 0x7fffffffde60
        current = <optimized out>
        target = <optimized out>
        to_sleep_ms = <optimized out>
        frame_time_last = 0
        frame_limit_minimum_time = 16667
        frame_limit_last_time = 369059710742
        last_input = 256
        settings = 0x889bc0
---Type <return> to continue, or q <return> to quit---
        system = 0x7a8260 <runloop_system>
#5  0x000000000040f190 in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:310
        sleep_ms = 0
        args = 0x0
        ret = <optimized out>
        settings = <optimized out>
#6  0x00007ffff2fe8a00 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#7  0x000000000040c0f9 in _start ()
No symbol table info available.
```

**Comment by fr500** [comment]
This is fixed in individual cores 
Relevant: https://github.com/libretro/RetroArch/issues/3241

**Comment by orbea** [comment]
Just want to point out this issue was fixed a while ago.
