### ISSUE TITLE
Retroarch xmb gui asserts with the vulkan video driver.

### ISSUE THREAD

**Issue by alex34567** [libretro/RetroArch#3225]
The xmb gui seams to give vulkan an empty texture with no height, width or pixels causing the driver to assert.

Using ArchLinux 64 bit on Xorg

VGA compatible controller: NVIDIA Corporation GM107 \[GeForce GTX 750 Ti] (rev a2) with propitiatory drivers

Output of retroarch -v
```
RetroArch [INFO] :: Version: 1.3.5
RetroArch [INFO] :: Git: a55199a
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Looking for config in: "/home/alex/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Config: loading config from: /home/alex/.config/retroarch/retroarch.cfg.
RetroArch [INFO] :: Resetting undo buffers.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29975.00 Hz.
RetroArch [INFO] :: Video @ 960x720
RetroArch [ERROR] :: Failed to connect to Wayland server.
RetroArch [INFO] :: Vulkan dynamic library loaded.
RetroArch [INFO] :: Detecting screen resolution 1280x1024.
RetroArch [INFO] :: [GLX]: X = 0, Y = 0, W = 960, H = 720.
RetroArch [INFO] :: [Vulkan]: Queue family 0 supports 16 sub-queues.
RetroArch [INFO] :: [Vulkan]: Swapchain supports present mode: 2.
RetroArch [INFO] :: [Vulkan]: Swapchain supports present mode: 3.
RetroArch [INFO] :: [Vulkan]: Swapchain supports present mode: 0.
RetroArch [INFO] :: [Vulkan]: Creating swapchain with present mode: 2
RetroArch [INFO] :: [Vulkan]: Using swapchain size 960 x 720.
RetroArch [INFO] :: [Vulkan]: Got 3 swapchain images.
RetroArch [INFO] :: Vulkan: Using resolution 960x720
RetroArch [INFO] :: [Vulkan]: Using RGB565 format.
RetroArch [INFO] :: [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
RetroArch [INFO] :: [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
RetroArch [INFO] :: [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
RetroArch [INFO] :: [Vulkan]: Loading stock shader.
RetroArch [INFO] :: [slang]: Building pass #0 (N/A)
RetroArch [INFO] :: [slang]: Reflection
RetroArch [INFO] :: [slang]:   Textures:
RetroArch [INFO] :: [slang]:      Source (#0)
RetroArch [INFO] :: [slang]:
RetroArch [INFO] :: [slang]:   Uniforms (Vertex: yes, Fragment: no):
RetroArch [INFO] :: [slang]:      MVP (Offset: 0)
RetroArch [INFO] :: [Vulkan filter chain]: Not using frame history.
RetroArch [INFO] :: [Vulkan filter chain]: Not using framebuffer feedback.
RetroArch [INFO] :: [udev]: Plugged pad: Microsoft X-Box 360 pad (1118:654) on port #0.
RetroArch [INFO] :: Autodetect: 127 profiles found
RetroArch [INFO] :: Autodetect: selected configuration: /home/alex/.config/retroarch/autoconfig/udev/Microsoft_X-Box_360_pad.cfg
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event15) supports force feedback.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event15) supports 16 force feedback effects.
RetroArch [INFO] :: [udev]: Plugged pad: HuiJia  USB GamePad (6708:63237) on port #1.
RetroArch [INFO] :: Autodetect: 127 profiles found
RetroArch [INFO] :: Autodetect: selected configuration: /home/alex/.config/retroarch/autoconfig/udev/Mayflash-GameCube-to-USB-Adapter.cfg
RetroArch [INFO] :: [udev]: Pad #1 (/dev/input/event2) supports force feedback.
RetroArch [INFO] :: [udev]: Pad #1 (/dev/input/event2) supports 16 force feedback effects.
RetroArch [INFO] :: [udev]: Plugged pad: HuiJia  USB GamePad (6708:63237) on port #2.
RetroArch [INFO] :: Autodetect: 127 profiles found
RetroArch [INFO] :: Autodetect: selected configuration: /home/alex/.config/retroarch/autoconfig/udev/Mayflash-GameCube-to-USB-Adapter.cfg
RetroArch [INFO] :: [udev]: Pad #2 (/dev/input/event3) supports force feedback.
RetroArch [INFO] :: [udev]: Pad #2 (/dev/input/event3) supports 16 force feedback effects.
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Suspending screensaver (X11).
RetroArch [INFO] :: [PulseAudio]: Requested 24576 bytes buffer, got 18432.
RetroArch [INFO] :: Found menu display driver: "menu_display_vulkan".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Using font rendering backend: freetype.
Assertion failed at gfx/common/vulkan_common.c:318
```

Gdb backtrace
```
#0  0x00007fffefd3e295 in raise () from /usr/lib/libc.so.6
#1  0x00007fffefd3f6da in abort () from /usr/lib/libc.so.6
#2  0x00000000004ee853 in vulkan_create_texture (vk=vk@entry=0xa920f0, 
    old=old@entry=0x0, width=0, height=0, 
    format=format@entry=VK_FORMAT_B8G8R8A8_UNORM, initial=0x0, swizzle=0x0, 
    type=<optimized out>) at gfx/common/vulkan_common.c:325
#3  0x00000000004e94b7 in vulkan_load_texture (video_data=0xa920f0, 
    data=0x7fffffff19a0, threaded=<optimized out>, 
    filter_type=TEXTURE_FILTER_MIPMAP_LINEAR) at gfx/drivers/vulkan.c:2049
#4  0x000000000043af49 in video_driver_texture_load (
    data=data@entry=0x7fffffff19a0, 
    filter_type=filter_type@entry=TEXTURE_FILTER_MIPMAP_LINEAR, 
    id=id@entry=0x1315228) at gfx/video_driver.c:2220
#5  0x0000000000481d51 in xmb_context_reset_horizontal_list (
    xmb=xmb@entry=0x130f7b0) at menu/drivers/xmb.c:1376
#6  0x000000000048252a in xmb_context_reset (data=0x130f7b0)
    at menu/drivers/xmb.c:2785
#7  0x0000000000484b69 in menu_driver_ctl (
    state=state@entry=RARCH_MENU_CTL_CONTEXT_RESET, data=data@entry=0x0)
    at menu/menu_driver.c:914
#8  0x000000000043c4d0 in init_drivers (flags=<optimized out>) at driver.c:358
#9  driver_ctl (state=<optimized out>, data=<optimized out>) at driver.c:457
#10 0x000000000043c3f7 in driver_ctl (
    state=state@entry=RARCH_DRIVER_CTL_INIT_ALL, data=data@entry=0x0)
    at driver.c:463
#11 0x000000000041e33a in retroarch_main_init (argc=1, 
    argv=argv@entry=0x7fffffffe4b8) at retroarch.c:1358
#12 0x000000000042b816 in content_load (info=0x7fffffffe3a0)
    at tasks/task_content.c:935
#13 task_load_content (content_info=content_info@entry=0x7fffffffe3a0, 
    launched_from_menu=launched_from_menu@entry=false)
    at tasks/task_content.c:1607
#14 0x000000000042d4bd in task_push_content_load_default (
    core_path=core_path@entry=0x0, fullpath=fullpath@entry=0x0, 
    content_info=content_info@entry=0x7fffffffe3a0, 
    type=type@entry=CORE_TYPE_PLAIN, 
    mode=mode@entry=CONTENT_MODE_LOAD_FROM_CLI, cb=cb@entry=0x0, user_data=0x0)
    at tasks/task_content.c:1909
#15 0x000000000041ac42 in rarch_main (argc=1, argv=0x7fffffffe4b8, data=0x0)
    at frontend/frontend.c:105
#16 0x00007fffefd2b741 in __libc_start_main () from /usr/lib/libc.so.6
#17 0x00000000004183a9 in _start ()
```

**Comment by twinaphex** [comment]
XMB for me doesn't work on Intel Ivy Bridge (HD 4K). However, it has worked fine for maister, hunterk, LexSfx, and other people, on various GPUs.

Let me get a report back for you from another Nvidia GPU user though. Also make sure you have the very latest Nvidia drivers.

**Comment by alex34567** [comment]
I am using the latest driver.

**Comment by alex34567** [comment]
For me it only happends when there are black boxes like this
![bug](https://cloud.githubusercontent.com/assets/11170617/16898298/3be011be-4b90-11e6-85d5-286d2428d548.png)

**Comment by Themaister** [comment]
I think this is related to a bug where it tries to load blank textures and it doesn't error out in a place where it should.
https://github.com/libretro/RetroArch/pull/3227 is this related?

**Comment by Themaister** [comment]
This should be fixed now.
