### ISSUE TITLE
Segmentation fault of v1.3.6 on my PI3 running Arch

### ISSUE THREAD

**Issue by hinzundcode** [libretro/RetroArch#3234]
I compiled RetroArch v1.3.6 with `--disable-x11 --disable-ffmpeg` on my Raspberry Pi 3 running Arch Linux, but as soon as I start it I get a segmentation fault:

```
(gdb) run
Starting program: /home/alarm/RetroArch/retroarch
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x75cd63f0 (LWP 12370)]
[New Thread 0x754b03f0 (LWP 12371)]
[New Thread 0x74aff3f0 (LWP 12372)]
[New Thread 0x742ff3f0 (LWP 12373)]
[New Thread 0x73aff3f0 (LWP 12374)]

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) backtrace
#0  0x00000000 in ?? ()
#1  0x000cf020 in rglgen_resolve_symbols_custom (
    map=0x14f22c <rglgen_symbol_map>, proc=0x0)
    at libretro-common/glsym/rglgen.c:34
#2  rglgen_resolve_symbols (proc=0x0) at libretro-common/glsym/rglgen.c:41
#3  0x000cbb18 in gl_init (video=0x7effa058, video@entry=0x7effa050,
    input=0x75cd7008, input@entry=0x192718 <current_input>, input_data=0x0)
    at gfx/drivers/gl.c:2699
#4  0x00041bf8 in init_video () at gfx/video_driver.c:713
#5  video_driver_init () at gfx/video_driver.c:1548
#6  0x0004429c in init_drivers (flags=127) at driver.c:328
#7  driver_ctl (state=<optimized out>, data=<optimized out>) at driver.c:457
#8  0x00044000 in driver_ctl (state=state@entry=RARCH_DRIVER_CTL_INIT_ALL,
    data=data@entry=0x0) at driver.c:463
#9  0x0002436c in retroarch_main_init (argc=0, argv=0x0, argv@entry=0x7efff6b4)
    at retroarch.c:1358
#10 0x000348dc in content_load (info=0x0) at tasks/task_content.c:935
#11 task_load_content (content_info=content_info@entry=0x7efff530,
    launched_from_menu=launched_from_menu@entry=false)
    at tasks/task_content.c:1607
#12 0x00036460 in task_push_content_load_default (
    core_path=core_path@entry=0x0, fullpath=fullpath@entry=0x0,
    content_info=0x7efff530, content_info@entry=0x7efff528,
    type=type@entry=CORE_TYPE_PLAIN,
    mode=mode@entry=CONTENT_MODE_LOAD_FROM_CLI, cb=cb@entry=0x0,
    user_data=user_data@entry=0x0) at tasks/task_content.c:1909
#13 0x00020b10 in rarch_main (argc=1, argv=0x7efff6b4, data=0x0)
    at frontend/frontend.c:105
#14 0x767d3cbc in __libc_start_main () from /usr/lib/libc.so.6
#15 0x0001e334 in _start ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Did I forget to install some requirements? These packages are installed: https://gist.github.com/hinzundcode/4b2f24a3f3c2b1e5113cc73c646380bb

**Comment by fr500** [comment]
Try again on a current trunk and re-open if the issue persists
