### ISSUE TITLE
XMB freeze when used in GL cores

### ISSUE THREAD

**Issue by dankcushions** [libretro/RetroArch#3537]
You can recreate this with mupen64plus-libretro or glupen64 - launch any game and then open the XMB and it will freeze. You can unfreeze by closing the XMB and returning to the game. This issue is reported here: http://libretro.com/forums/showthread.php?t=6688

Previously it crashed with this sort of error:
```
Program received signal SIGSEGV, Segmentation fault.
0x000d5c44 in matrix_4x4_multiply (out=0x7effddd0, a=a@entry=0x7effdc08, b=b@entry=0x0) at libretro-common/gfx/math/matrix_4x4.c:195
195 libretro-common/gfx/math/matrix_4x4.c: No such file or directory.
(gdb) bt
#0  0x000d5c44 in matrix_4x4_multiply (out=0x7effddd0, a=a@entry=0x7effdc08, b=b@entry=0x0) at libretro-common/gfx/math/matrix_4x4.c:195
#1  0x000bb310 in menu_display_rotate_z (draw=0x7effdcc8, draw@entry=0x7effdcc0) at menu/menu_display.c:580
#2  0x0008e480 in xmb_frame (data=0x3012e8) at menu/drivers/xmb.c:2215
#3  0x000915f4 in menu_driver_ctl (state=state@entry=RARCH_MENU_CTL_FRAME, data=data@entry=0x0) at menu/menu_driver.c:509
#4  0x000d8ab0 in gl_frame (data=0x264d98, frame=<optimized out>, frame_width=<optimized out>, frame_height=<optimized out>, frame_count=131, pitch=0, msg=0x1ba5c0 <video_driver_msg> "")
    at gfx/drivers/gl.c:1270
#5  0x0004778c in video_driver_frame (data=0x0, width=320, height=240, pitch=0) at gfx/video_driver.c:2169
#6  0x000200f4 in core_frame (info=info@entry=0x7efff3b0) at core_impl.c:304
#7  0x00046e2c in video_driver_cached_frame () at gfx/video_driver.c:1130
#8  video_driver_cached_frame_render () at gfx/video_driver.c:1697
#9  0x000bab18 in menu_display_libretro () at menu/menu_display.c:324
#10 0x00091cc4 in menu_driver_ctl (state=state@entry=RARCH_MENU_CTL_RENDER, data=data@entry=0x0) at menu/menu_driver.c:476
#11 0x00032a14 in runloop_iterate_menu (sleep_ms=0x7efff55c, action=<optimized out>) at runloop.c:1400
#12 runloop_iterate (sleep_ms=0x7efff55c, sleep_ms@entry=0x7efff554) at runloop.c:1550
#13 0x0001f514 in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:122
#14 0x769ab294 in __libc_start_main (main=0x7efff6e4, argc=1991049216, argv=0x769ab294 <__libc_start_main+276>, init=<optimized out>, fini=0x107cd0 <__libc_csu_fini>, rtld_fini=0x76fdf408 <_dl_fini>,
    stack_end=0x7efff6e4) at libc-start.c:287
#15 0x0001cb8c in _start ()
(gdb)
```

but following https://github.com/libretro/RetroArch/commit/2080301088446a5d4c773e854e2ba8db3568b40f this now at least doesn't crash :)

if you use RGUI with a GL core, or XMB with a none-GL core all seems ok so I assume it's some sort of GL conflict. I will attempt to bisect it to the commit that originally caused it when I have a moment. I guess something to do with the xmb driver?

**Comment by bparker06** [comment]
What is it that freezes exactly? Do you have threaded video turned on? Are you launching content from the command-line?

**Comment by dankcushions** [comment]
Duplicate of https://github.com/libretro/RetroArch/issues/2655 - closing
