### ISSUE TITLE
latest android build crashes on startup

### ISSUE THREAD

**Issue by bparker06** [libretro/RetroArch#3620]
Thread 15 "Thread-179" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 2901.2959]
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0xa366c508 in rglgen_resolve_symbols_custom (proc=proc@entry=0x0, map=map@entry=0xa3a98380 <rglgen_symbol_map>) at jni/../../../../griffin/../libretro-common/glsym/rglgen.c:34
#2  0xa366c546 in rglgen_resolve_symbols (proc=0x0) at jni/../../../../griffin/../libretro-common/glsym/rglgen.c:41
#3  0xa36e3788 in gl_init (video=0xb43ef010, input=0xa3b09d24 <current_input>, input_data=0xa3b09d20 <current_input_data>) at jni/../../../../griffin/../gfx/drivers/gl.c:1912
#4  0xa36df14c in video_thread_handle_packet (incoming=0xa2effcc8, thr=<optimized out>) at jni/../../../../griffin/../gfx/video_thread_wrapper.c:343
#5  video_thread_loop (data=0xb43ef000) at jni/../../../../griffin/../gfx/video_thread_wrapper.c:585
#6  0xa362a921 in thread_wrap (data_=0xb426ee08) at jni/../../../../griffin/../libretro-common/rthreads/rthreads.c:105
#7  0xb75321a9 in __pthread_start(void*) () from /home/bp/RetroArch-bp/RetroArch-android/pkg/android/phoenix/obj/local/x86/system/lib/libc.so
#8  0xb752d52a in __start_thread () from /home/bp/RetroArch-bp/RetroArch-android/pkg/android/phoenix/obj/local/x86/system/lib/libc.so
#9  0xb75240f7 in __bionic_clone () from /home/bp/RetroArch-bp/RetroArch-android/pkg/android/phoenix/obj/local/x86/system/lib/libc.so

**Comment by bparker06** [comment]
Apparently this only happens on an emulator and not with a real android device.
