### ISSUE TITLE
Music player segfaults on opening files with unicode glyphs.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#3687]
OS: `Slackware64-current`
`RetroArch-2016.09.29_3d09883_master-x86_64-1_git`

When opening a music file by an artist that used used unconventional glyphs in the song names RetroArch will segfault. However this only happens if `DEBUG=1` is not set in the make environment. Using `-g`, `-O0`, and `GL_DEBUG=1` can be still used for some debugging support.

A free music album that can be used to test this can be found at the below bandcamp music. It can be downloaded if you enter `0` into `Buy Now`.

https://deathsdynamicshroud.bandcamp.com/album/seawrld

Additionally the non-latin characters and unicode glyphs display a question marks, but that is another issue. I point this out because death's dynamic shroud.wmv could be a good test case due to the messed up song titles and album names. This artist has already found issue https://github.com/libretro/RetroArch/issues/3686.
```
#0  0x00000000004da72e in gl_raster_font_render_line (font=<optimized out>, 
    msg=0x7f8f22 <video_driver_msg+98> "", msg_len_full=0, 
    scale=<optimized out>, color=<optimized out>, pos_x=<optimized out>, 
    pos_y=<optimized out>, text_align=<optimized out>)
    at gfx/drivers_font/gl_raster_font.c:372
#1  0x3f80000000000000 in ?? ()
#2  0x3e99999a3e99999a in ?? ()
#3  0x3f80000000000000 in ?? ()
#4  0x3e99999a3e99999a in ?? ()
#5  0x3f80000000000000 in ?? ()
#6  0x0000000000000000 in ?? ()
```
GDB log - http://pastebin.com/j6zJXWrV

**Comment by orbea** [comment]
bparker fixed this.

https://github.com/libretro/RetroArch/commit/b83d2529e2d5c684d038c24a20bed1f8decc6f0f
