### ISSUE TITLE
Remote RetroPad segfaults when started after another core

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#3978]
OS: `Slackware64-current`
`RetroArch-2016.11.09_4b03bb9_master-x86_64-1_git`
`snes9x-libretro-2016.10.16_b826cb9_master-x86_64-1_git`

How to reproduce:

1. Start RetroArch and load a core.
2. Load Core --> Start Remote RetroPad

Which core and whether it is closed before starting the Remote RetroPad does not matter, the segfault was reproduced with snes9x. Other cores do not crash when started after another core.
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007fffe73d9715 in retro_load_game (game=0x0) at ../libretro/libretro.cpp:444
444	   if(game->data == NULL && game->size == 0 && game->path != NULL)
(gdb) bt 
#0  0x00007fffe73d9715 in retro_load_game (game=0x0)
    at ../libretro/libretro.cpp:444
#1  0x0000000000412499 in core_load_game (load_info=0x7fffffffbf50)
    at core_impl.c:271
#2  0x0000000000428077 in load_content (temporary_content=0x95cb50, 
    info=0xe5f860, content=0x1276f30, special=0x0) at tasks/task_content.c:563
#3  0x0000000000428562 in content_file_init (temporary_content=0x95cb50)
    at tasks/task_content.c:741
#4  0x0000000000428745 in content_init () at tasks/task_content.c:817
#5  0x0000000000419fce in event_init_content () at command.c:1329
#6  0x000000000041a15f in command_event_init_core (data=
    0x8b09ec <explicit_current_core_type>) at command.c:1394
#7  0x000000000041b896 in command_event (cmd=CMD_EVENT_CORE_INIT, 
    data=0x8b09ec <explicit_current_core_type>) at command.c:2166
#8  0x0000000000414995 in retroarch_main_init (argc=10, argv=0x7fffffffc3b0)
    at retroarch.c:1057
#9  0x000000000042777c in content_load (info=0x7fffffffd7c0)
    at tasks/task_content.c:280
#10 0x00000000004289fa in task_load_content (content_info=0x7fffffffd7c0, 
    launched_from_menu=true, mode=
    CONTENT_MODE_LOAD_NOTHING_WITH_NET_RETROPAD_CORE_FROM_MENU)
    at tasks/task_content.c:902
#11 0x0000000000428f8e in task_push_content_load_default (core_path=0x0, 
    fullpath=0x0, content_info=0x7fffffffd7c0, type=CORE_TYPE_FFMPEG, mode=
    CONTENT_MODE_LOAD_NOTHING_WITH_NET_RETROPAD_CORE_FROM_MENU, cb=0x0, 
    user_data=0x0) at tasks/task_content.c:1244
#12 0x00000000004d6e90 in generic_action_ok_file_load (corepath=0x0, 
    fullpath=0x0, action_type=CORE_TYPE_FFMPEG, content_enum_idx=
    CONTENT_MODE_LOAD_NOTHING_WITH_NET_RETROPAD_CORE_FROM_MENU)
    at menu/cbs/menu_cbs_ok.c:831
#13 0x00000000004d91b8 in action_ok_start_net_retropad_core (
    path=0x7fffffffd8e0 "Start Remote RetroPad", 
    label=0x7fffffffd9df "menu_start_net_retropad", type=102, idx=0, entry_idx=0)
    at menu/cbs/menu_cbs_ok.c:1863
#14 0x00000000004d4497 in menu_entry_action (entry=0x7fffffffd8e0, i=0, action=
    MENU_ACTION_OK) at menu/widgets/menu_entry.c:523
#15 0x0000000000503d8b in generic_menu_iterate (data=0x10e5be0, 
    userdata=0x10e9ff0, action=MENU_ACTION_OK) at menu/drivers/menu_generic.c:234
#16 0x00000000004bf1cb in menu_driver_ctl (state=RARCH_MENU_CTL_ITERATE, 
    data=0x7fffffffe030) at menu/menu_driver.c:888
#17 0x000000000042532a in runloop_check_state (settings=0x7ffff7e7c010, 
    current_input=256, old_input=0, sleep_ms=0x7fffffffe160) at runloop.c:872
#18 0x0000000000425e6d in runloop_iterate (sleep_ms=0x7fffffffe160)
    at runloop.c:1180
#19 0x0000000000411360 in rarch_main (argc=1, argv=0x7fffffffe278, data=0x0)
    at frontend/frontend.c:127
#20 0x00000000004113c7 in main (argc=1, argv=0x7fffffffe278)
    at frontend/frontend.c:145
```
GDB log - http://pastebin.com/Cdip0Mpv

**Comment by lasers** [comment]
Similar issue: https://github.com/libretro/RetroArch/issues/3965

**Comment by orbea** [comment]
Thanks, I guess I will close this as a duplicate.

**Comment by lasers** [comment]
Just making a reference. Linking things together.
