### ISSUE TITLE
RetroArch crashes while running in KMS using an external display

### ISSUE THREAD

**Issue by diegoviola** [libretro/RetroArch#4098]
Arch Linux (x86_64)
RetroArch git dc99713a9b9961b61dbfa70b9353ba7f88bc2c60
ThinkPad T450
Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
Intel Corporation HD Graphics 5500

It doesn't crash if I disconnect the external display and I use the primary display only.

```
Starting program: /home/diego/RetroArch/retroarch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe50ad700 (LWP 5789)]

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
#0  0x0000000000000000 in ?? ()
#1  0x000000000052c809 in rglgen_resolve_symbols_custom (proc=0x0, map=0x695920 <rglgen_symbol_map>) at libretro-common/glsym/rglgen.c:34
#2  0x000000000052c84d in rglgen_resolve_symbols (proc=0x0) at libretro-common/glsym/rglgen.c:41
#3  0x0000000000525fb0 in gl_init (video=0x7fffffffd220, input=0x8fbe80 <current_input>, input_data=0x8fbe88 <current_input_data>) at gfx/drivers/gl.c:1911
#4  0x000000000043c99d in init_video () at gfx/video_driver.c:751
#5  0x000000000043de5f in video_driver_init () at gfx/video_driver.c:1550
#6  0x00000000004402c0 in init_drivers (flags=255) at driver.c:323
#7  0x00000000004405b4 in driver_ctl (state=RARCH_DRIVER_CTL_INIT, data=0x7fffffffd378) at driver.c:454
#8  0x00000000004405d1 in driver_ctl (state=RARCH_DRIVER_CTL_INIT_ALL, data=0x0) at driver.c:460
#9  0x00000000004153c2 in retroarch_main_init (argc=1, argv=0x7fffffffeb48) at retroarch.c:1083
#10 0x0000000000426f99 in content_load (info=0x7fffffffea10) at tasks/task_content.c:280
#11 0x00000000004281f0 in task_load_content (content_info=0x7fffffffea10, launched_from_menu=false, mode=CONTENT_MODE_LOAD_FROM_CLI) at tasks/task_content.c:902
#12 0x000000000042873a in task_push_content_load_default (core_path=0x0, fullpath=0x0, content_info=0x7fffffffea10, type=CORE_TYPE_PLAIN, mode=
    CONTENT_MODE_LOAD_FROM_CLI, cb=0x0, user_data=0x0) at tasks/task_content.c:1244
#13 0x0000000000412104 in rarch_main (argc=1, argv=0x7fffffffeb48, data=0x0) at frontend/frontend.c:110
#14 0x0000000000412195 in main (argc=1, argv=0x7fffffffeb48) at frontend/frontend.c:145
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x000000000052c809 in rglgen_resolve_symbols_custom (proc=0x0, map=0x695920 <rglgen_symbol_map>) at libretro-common/glsym/rglgen.c:34
        func = 0x0
#2  0x000000000052c84d in rglgen_resolve_symbols (proc=0x0) at libretro-common/glsym/rglgen.c:41
No locals.
#3  0x0000000000525fb0 in gl_init (video=0x7fffffffd220, input=0x8fbe80 <current_input>, input_data=0x8fbe88 <current_input_data>) at gfx/drivers/gl.c:1911
        mode = {width = 320, height = 240, fullscreen = true}
        inp = {input = 0x0, input_data = 0x0}
        interval = 1
        mip_level = 4294955456
        full_x = 320
        full_y = 240
        shader_filter = {index = 21, smooth = 0x7ffffff3}
        shader_info = {set_active = 176, num = 32767, idx = 4458352, data = 0x7fffffffd1c0}
        ident_info = {ident = 0x3 <error: Cannot access memory at address 0x3>}
        wrap_info = {idx = 0, type = RARCH_WRAP_BORDER}
        win_width = 320
        win_height = 240
        temp_width = 0
        temp_height = 0
        force_smooth = false
        vendor = 0x0
        renderer = 0x0
        version = 0x0
        hwr = 0x0
        error_string = 0x0
        settings = 0x7fffe50ae010
        gl = 0x96fd00
        ctx_driver = 0x68d880 <gfx_ctx_null>
#4  0x000000000043c99d in init_video () at gfx/video_driver.c:751
        max_dim = 320
        scale = 2
        width = 0
        height = 0
        custom_vp = 0x7fffe50ae010
        tmp = 0x8d5a20 <input_udev>
        geom = 0x900120 <av_info>
        system = 0x8e4c80 <runloop_system>
        video = {width = 0, height = 0, fullscreen = true, vsync = true, force_aspect = true, smooth = true, input_scale = 2, rgb32 = false}
        dummy_pixels = {0 <repeats 32 times>}
        settings = 0x7fffe50ae010
        av_info = 0x900120 <av_info>
#5  0x000000000043de5f in video_driver_init () at gfx/video_driver.c:1550
No locals.
#6  0x00000000004402c0 in init_drivers (flags=255) at driver.c:323
        hwr = 0x900000 <hw_render>
#7  0x00000000004405b4 in driver_ctl (state=RARCH_DRIVER_CTL_INIT, data=0x7fffffffd378) at driver.c:454
        flags = 0x7fffffffd378
#8  0x00000000004405d1 in driver_ctl (state=RARCH_DRIVER_CTL_INIT_ALL, data=0x0) at driver.c:460
        flags = 255
#9  0x00000000004153c2 in retroarch_main_init (argc=1, argv=0x7fffffffeb48) at retroarch.c:1083
        init_failed = false
#10 0x0000000000426f99 in content_load (info=0x7fffffffea10) at tasks/task_content.c:280
        i = 0
        retval = true
        rarch_argc = 0
        rarch_argv = {0x0 <repeats 32 times>}
        argv_copy = {0x0 <repeats 32 times>}
        rarch_argv_ptr = 0x7fffffffeb48
        rarch_argc_ptr = 0x7fffffffea10
        wrap_args = 0x96f8d0
#11 0x00000000004281f0 in task_load_content (content_info=0x7fffffffea10, launched_from_menu=false, mode=CONTENT_MODE_LOAD_FROM_CLI) at tasks/task_content.c:902
        name = '\000' <repeats 67 times>, "\307", '\000' <repeats 28 times>, "p\317h\002\004\005\177<", '\000' <repeats 24 times>, "\bC\022\000\000\000\000\000\060C\022\000\000\000\000\000\fI\000\000\000\000\000\000\061$\001\000<I\000\000!\t\000\000\000\000\000\000$\001\000\000\000\000\000\000|\t\000\000\222\001\000\000$\000\000\000\000\000\000\000\005\000\000\000\000\000\000\000"...
        msg = "\000\000\000\000\000\000\000\000\310\301\375\367\377\177\000\000\300\350\377\377\377\177\000\000 \023\215\000\000\000\000\000\200\354@\000\000\000\000\000@\353\377\377\377\177", '\000' <repeats 18 times>, "\240\351\377\377\377\177\000\000\364\210\336\367\377\177\000\000\001", '\000' <repeats 15 times>, "\240\351\377\377\377\177\000\000\b?\372\366\377\177\000\000p\351\377\377\377\177\000\000c\371\336\367\377\177", '\000' <repeats 43 times>, "\377\000\000\000\000\377", '\000' <repeats 50 times>...
#12 0x000000000042873a in task_push_content_load_default (core_path=0x0, fullpath=0x0, content_info=0x7fffffffea10, type=CORE_TYPE_PLAIN, mode=
    CONTENT_MODE_LOAD_FROM_CLI, cb=0x0, user_data=0x0) at tasks/task_content.c:1244
        loading_from_menu = false
#13 0x0000000000412104 in rarch_main (argc=1, argv=0x7fffffffeb48, data=0x0) at frontend/frontend.c:110
        info = {argc = 1, argv = 0x7fffffffeb48, args = 0x0, environ_get = 0x41186b <frontend_linux_get_env>}
        args = 0x0
#14 0x0000000000412195 in main (argc=1, argv=0x7fffffffeb48) at frontend/frontend.c:145
No locals.
quit
```

**Comment by twinaphex** [comment]
I'm on Arch Linux, x64, and I can't reproduce this.

**Comment by orbea** [comment]
@diegoviola Can you still reproduce this with the current master? I don't have an external display to test this issue with...

**Comment by diegoviola** [comment]
@orbea I can't reproduce this with current master anymore, closing.
