### ISSUE TITLE
Crash when running Virtual Boy game; backtrace included

### ISSUE THREAD

**Issue by AlexFolland** [libretro/RetroArch#4172]
All of RA crashes when trying to run any Virtual Boy game.

Here's the backtrace:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000000875d107 in nvoglv64!DrvPresentBuffers () from C:\windows\system32\nvoglv64.dll
(gdb) bt
#0  0x000000000875d107 in nvoglv64!DrvPresentBuffers () from C:\windows\system32\nvoglv64.dll
#1  0x000000000875bc9e in nvoglv64!DrvPresentBuffers () from C:\windows\system32\nvoglv64.dll
#2  0x000000000875bbc7 in nvoglv64!DrvPresentBuffers () from C:\windows\system32\nvoglv64.dll
#3  0x0000000008743dc9 in nvoglv64!DrvPresentBuffers () from C:\windows\system32\nvoglv64.dll
#4  0x00000000004feed3 in vulkan_destroy_texture (device=0xb8a4270, tex=tex@entry=0x111b4e00) at gfx/common/vulkan_common.c:677
#5  0x00000000004f79e0 in vulkan_unload_texture (data=0x11097570, handle=287002112) at gfx/drivers/vulkan.c:2208
#6  0x000000000042b3ac in video_driver_texture_unload (id=id@entry=0xfc24f80) at gfx/video_driver.c:2171
#7  0x000000000048583a in xmb_load_image (userdata=<optimized out>, data=0xfc1c400, type=<optimized out>) at menu/drivers/xmb.c:3120
#8  0x000000000048d080 in menu_driver_ctl (state=state@entry=RARCH_MENU_CTL_LOAD_IMAGE, data=data@entry=0x22fc80) at menu/menu_driver.c:848
#9  0x00000000004bc0f8 in menu_display_handle_thumbnail_upload (task_data=0xfc1c400, user_data=0x0, err=<optimized out>) at menu/menu_display.c:664
#10 0x0000000000413a98 in retro_task_internal_gather () at libretro-common/queues/task_queue.c:135
#11 0x00000000004141bb in retro_task_threaded_gather () at libretro-common/queues/task_queue.c:353
#12 0x00000000004145e4 in task_queue_ctl (state=state@entry=TASK_QUEUE_CTL_CHECK, data=data@entry=0x0) at libretro-common/queues/task_queue.c:567
#13 0x00000000004016d7 in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:134
#14 0x000000000066f6d8 in main_getcmdline ()
#15 0x00000000004013f8 in __tmainCRTStartup () at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
#16 0x00000000004014eb in WinMainCRTStartup () at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:184
```

And since Github's issue tracker code tag seems to not adapt to be wide enough to read without using a horizontal scroll bar, here's a link to the text version: http://lex.clansfx.co.uk/dump/9c707363dd348581db57726d87a20dea/000001BB.txt

**Comment by Alcaro** [comment]
Linebreaks work if you use the multiline code block syntax, triple backticks on a separate line. I edited your post.

Scrollbars do indeed exist, but you'll get them at some point no matter what you do; most people don't have 3840px monitors, and scrollbars are perfectly scrollable unless you're doing something too tall.

Either way, Vulkan issues -> pinging @Themaister

**Comment by AlexFolland** [comment]
Thanks.  Didn't know about the ` vs ```.

**Comment by Alcaro** [comment]
Another trick:
```c++
if (openingLine == "```c++")
{
    syntaxHighlight(this, "c++");
}
```
