### ISSUE TITLE
(Regression) RetroArch segfaults when started under KMS

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#4450]
## Description

RetroArch segfaults when started under KMS, it still works fine if started in a Xorg session though.

### Expected behavior

KMS should not segfault.

### Actual behavior

```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000000053e302 in rglgen_resolve_symbols_custom (proc=0x0, map=0x8b6b20 <rglgen_symbol_map>) at libretro-common/glsym/rglgen.c:34
#2  0x000000000053e34b in rglgen_resolve_symbols (proc=0x0) at libretro-common/glsym/rglgen.c:41
#3  0x000000000053768f in gl_init (video=0x7fffffffcac0, input=0x8e4be0 <current_input>, input_data=0x8e4be8 <current_input_data>) at gfx/drivers/gl.c:1923
#4  0x000000000043fe94 in init_video () at gfx/video_driver.c:808
#5  0x00000000004414f7 in video_driver_init () at gfx/video_driver.c:1588
#6  0x0000000000443eb4 in drivers_init (flags=255) at driver.c:325
#7  0x0000000000414acd in retroarch_main_init (argc=1, argv=0x7fffffffe368) at retroarch.c:1098
#8  0x0000000000428a9f in content_load (info=0x7fffffffe230) at tasks/task_content.c:276
#9  0x0000000000429bf5 in task_load_content (content_info=0x7fffffffe230, content_ctx=0x7fffffffe1a0, launched_from_menu=false, mode=CONTENT_MODE_LOAD_FROM_CLI, error_string=0x7fffffffe198)
    at tasks/task_content.c:807
#10 0x000000000042a3e2 in task_push_content_load_default (core_path=0x0, fullpath=0x0, content_info=0x7fffffffe230, type=CORE_TYPE_PLAIN, mode=CONTENT_MODE_LOAD_FROM_CLI, cb=0x0, user_data=0x0)
    at tasks/task_content.c:1223
#11 0x00000000004113af in rarch_main (argc=1, argv=0x7fffffffe368, data=0x0) at frontend/frontend.c:113
#12 0x0000000000411440 in main (argc=1, argv=0x7fffffffe368) at frontend/frontend.c:148
```
Full GDB log - http://pastebin.com/89CpaQjS

### Steps to reproduce the bug

1. Start RetroArch under Linux KMS.

### Bisect Results

The first broken commit, I confirmed it was this commit manually as well.
```
23017e0b45de5dbb972534023159687b2d119583 is the first bad commit
commit 23017e0b45de5dbb972534023159687b2d119583
Author: twinaphex <libretro@gmail.com>
Date:   Fri Jan 13 16:57:57 2017 +0100

    Cleanups

:040000 040000 6841a6d9d7f8d81fbb0380a1ebfbf3e6e74a1fa9 6cc943757ef96c0ffae0c9e4e7086e97d8171715 M	gfx
```
23017e0b45de5dbb972534023159687b2d119583

### Version/Commit

`RetroArch-2017.01.17_c78991b6a_master-x86_64-1_git.tgz`

### Environment information

- OS: `Slackware64-ccurent`
- Compiler: `gcc-5.4.0`

**Comment by twinaphex** [comment]
This should fix the segfault I believe -

https://github.com/libretro/RetroArch/commit/f0820f6433681778bf580f9d85373d7b05759b09

**Comment by orbea** [comment]
I can confirm its fixed, thanks!

**Comment by inukaze** [comment]
Hi there when i try to use the latest yabasanshiro core i got : 

```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()

```
Slackware(64) 14.2, and older version of the same core works perfectly, well i had try to find the yabasanshiro core, but is the version for retroarch is not in the repository, just yabause. i don't have any explaniation if really can build yabasanshiro core.
