### ISSUE TITLE
Cannot join netplay rooms on Linux

### ISSUE THREAD

**Issue by bparker06** [libretro/RetroArch#4526]
## Description

When attempting to join any netplay room, RetroArch crashes with the following backtrace:

=================================================================
==29407==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f096ba426a0 bp 0x7ffdd77be630 sp 0x7ffdd77be618 T0)
    #0 0x7f096ba4269f in __lll_unlock_elision (/usr/lib/libpthread.so.0+0x1269f)
    #1 0x5fd003 in slock_unlock libretro-common/rthreads/rthreads.c:305
    #2 0x4366a7 in retro_task_threaded_gather libretro-common/queues/task_queue.c:373
    #3 0x436e02 in task_queue_ctl libretro-common/queues/task_queue.c:607
    #4 0x417724 in rarch_main frontend/frontend.c:134
    #5 0x4177cd in main frontend/frontend.c:148
    #6 0x7f09644ec290 in __libc_start_main (/usr/lib/libc.so.6+0x20290)
    #7 0x4108c9 in _start (/home/bp/RetroArch-bp/RetroArch/retroarch+0x4108c9)

Running under ThreadSanitizer also gives these errors:

==================
WARNING: ThreadSanitizer: unlock of an unlocked mutex (or by a wrong thread) (pid=31579)
    #0 pthread_mutex_unlock /build/gcc-multilib/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:3319 (libtsan.so.0+0x000000038c34)
    #1 slock_unlock libretro-common/rthreads/rthreads.c:305 (retroarch+0x00000058ebe8)
    #2 retro_task_threaded_gather libretro-common/queues/task_queue.c:372 (retroarch+0x00000042fbb5)
    #3 task_queue_ctl libretro-common/queues/task_queue.c:607 (retroarch+0x0000004305ba)
    #4 rarch_main frontend/frontend.c:134 (retroarch+0x00000041510d)
    #5 main frontend/frontend.c:148 (retroarch+0x000000415163)

  Location is heap block of size 40 at 0x7d0c0002ade0 allocated by main thread:
    #0 calloc /build/gcc-multilib/src/gcc/libsanitizer/tsan/tsan_interceptors.cc:555 (libtsan.so.0+0x000000026d71)
    #1 slock_new libretro-common/rthreads/rthreads.c:234 (retroarch+0x00000058eacd)
    #2 retro_task_threaded_init libretro-common/queues/task_queue.c:487 (retroarch+0x000000430043)
    #3 task_queue_init libretro-common/queues/task_queue.c:562 (retroarch+0x0000004303c7)
    #4 runloop_ctl /home/bp/RetroArch-bp/RetroArch/runloop.c:513 (retroarch+0x00000042cad3)
    #5 retroarch_main_init /home/bp/RetroArch-bp/RetroArch/retroarch.c:1064 (retroarch+0x000000419e6a)
    #6 content_load tasks/task_content.c:278 (retroarch+0x0000004318fa)
    #7 task_load_content tasks/task_content.c:832 (retroarch+0x000000433313)
    #8 task_push_content_load_default tasks/task_content.c:1253 (retroarch+0x000000433f17)
    #9 netplay_crc_scan_callback tasks/task_netplay_find_content.c:63 (retroarch+0x000000623b00)
    #10 retro_task_internal_gather libretro-common/queues/task_queue.c:138 (retroarch+0x00000042f1d4)
    #11 retro_task_threaded_gather libretro-common/queues/task_queue.c:371 (retroarch+0x00000042fb9c)
    #12 task_queue_ctl libretro-common/queues/task_queue.c:607 (retroarch+0x0000004305ba)
    #13 rarch_main frontend/frontend.c:134 (retroarch+0x00000041510d)
    #14 main frontend/frontend.c:148 (retroarch+0x000000415163)

  Mutex M409 (0x7d0c0002ade0) created at:
    #0 pthread_mutex_init /build/gcc-multilib/src/gcc/libsanitizer/tsan/tsan_interceptors.cc:1091 (libtsan.so.0+0x000000028c9e)
    #1 slock_new libretro-common/rthreads/rthreads.c:243 (retroarch+0x00000058eaf0)
    #2 retro_task_threaded_init libretro-common/queues/task_queue.c:487 (retroarch+0x000000430043)
    #3 task_queue_init libretro-common/queues/task_queue.c:562 (retroarch+0x0000004303c7)
    #4 runloop_ctl /home/bp/RetroArch-bp/RetroArch/runloop.c:513 (retroarch+0x00000042cad3)
    #5 retroarch_main_init /home/bp/RetroArch-bp/RetroArch/retroarch.c:1064 (retroarch+0x000000419e6a)
    #6 content_load tasks/task_content.c:278 (retroarch+0x0000004318fa)
    #7 task_load_content tasks/task_content.c:832 (retroarch+0x000000433313)
    #8 task_push_content_load_default tasks/task_content.c:1253 (retroarch+0x000000433f17)
    #9 netplay_crc_scan_callback tasks/task_netplay_find_content.c:63 (retroarch+0x000000623b00)
    #10 retro_task_internal_gather libretro-common/queues/task_queue.c:138 (retroarch+0x00000042f1d4)
    #11 retro_task_threaded_gather libretro-common/queues/task_queue.c:371 (retroarch+0x00000042fb9c)
    #12 task_queue_ctl libretro-common/queues/task_queue.c:607 (retroarch+0x0000004305ba)
    #13 rarch_main frontend/frontend.c:134 (retroarch+0x00000041510d)
    #14 main frontend/frontend.c:148 (retroarch+0x000000415163)

SUMMARY: ThreadSanitizer: unlock of an unlocked mutex (or by a wrong thread) libretro-common/rthreads/rthreads.c:305 in slock_unlock
==================
==================
WARNING: ThreadSanitizer: unlock of an unlocked mutex (or by a wrong thread) (pid=31579)
    #0 pthread_mutex_unlock /build/gcc-multilib/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:3319 (libtsan.so.0+0x000000038c34)
    #1 slock_unlock libretro-common/rthreads/rthreads.c:305 (retroarch+0x00000058ebe8)
    #2 retro_task_threaded_gather libretro-common/queues/task_queue.c:373 (retroarch+0x00000042fbce)
    #3 task_queue_ctl libretro-common/queues/task_queue.c:607 (retroarch+0x0000004305ba)
    #4 rarch_main frontend/frontend.c:134 (retroarch+0x00000041510d)
    #5 main frontend/frontend.c:148 (retroarch+0x000000415163)

  Location is heap block of size 40 at 0x7d0c0000ed60 allocated by main thread:
    #0 calloc /build/gcc-multilib/src/gcc/libsanitizer/tsan/tsan_interceptors.cc:555 (libtsan.so.0+0x000000026d71)
    #1 slock_new libretro-common/rthreads/rthreads.c:234 (retroarch+0x00000058eacd)
    #2 retro_task_threaded_init libretro-common/queues/task_queue.c:488 (retroarch+0x00000043005c)
    #3 task_queue_init libretro-common/queues/task_queue.c:562 (retroarch+0x0000004303c7)
    #4 runloop_ctl /home/bp/RetroArch-bp/RetroArch/runloop.c:513 (retroarch+0x00000042cad3)
    #5 retroarch_main_init /home/bp/RetroArch-bp/RetroArch/retroarch.c:1064 (retroarch+0x000000419e6a)
    #6 content_load tasks/task_content.c:278 (retroarch+0x0000004318fa)
    #7 task_load_content tasks/task_content.c:832 (retroarch+0x000000433313)
    #8 task_push_content_load_default tasks/task_content.c:1253 (retroarch+0x000000433f17)
    #9 netplay_crc_scan_callback tasks/task_netplay_find_content.c:63 (retroarch+0x000000623b00)
    #10 retro_task_internal_gather libretro-common/queues/task_queue.c:138 (retroarch+0x00000042f1d4)
    #11 retro_task_threaded_gather libretro-common/queues/task_queue.c:371 (retroarch+0x00000042fb9c)
    #12 task_queue_ctl libretro-common/queues/task_queue.c:607 (retroarch+0x0000004305ba)
    #13 rarch_main frontend/frontend.c:134 (retroarch+0x00000041510d)
    #14 main frontend/frontend.c:148 (retroarch+0x000000415163)

  Mutex M410 (0x7d0c0000ed60) created at:
    #0 pthread_mutex_init /build/gcc-multilib/src/gcc/libsanitizer/tsan/tsan_interceptors.cc:1091 (libtsan.so.0+0x000000028c9e)
    #1 slock_new libretro-common/rthreads/rthreads.c:243 (retroarch+0x00000058eaf0)
    #2 retro_task_threaded_init libretro-common/queues/task_queue.c:488 (retroarch+0x00000043005c)
    #3 task_queue_init libretro-common/queues/task_queue.c:562 (retroarch+0x0000004303c7)
    #4 runloop_ctl /home/bp/RetroArch-bp/RetroArch/runloop.c:513 (retroarch+0x00000042cad3)
    #5 retroarch_main_init /home/bp/RetroArch-bp/RetroArch/retroarch.c:1064 (retroarch+0x000000419e6a)
    #6 content_load tasks/task_content.c:278 (retroarch+0x0000004318fa)
    #7 task_load_content tasks/task_content.c:832 (retroarch+0x000000433313)
    #8 task_push_content_load_default tasks/task_content.c:1253 (retroarch+0x000000433f17)
    #9 netplay_crc_scan_callback tasks/task_netplay_find_content.c:63 (retroarch+0x000000623b00)
    #10 retro_task_internal_gather libretro-common/queues/task_queue.c:138 (retroarch+0x00000042f1d4)
    #11 retro_task_threaded_gather libretro-common/queues/task_queue.c:371 (retroarch+0x00000042fb9c)
    #12 task_queue_ctl libretro-common/queues/task_queue.c:607 (retroarch+0x0000004305ba)
    #13 rarch_main frontend/frontend.c:134 (retroarch+0x00000041510d)
    #14 main frontend/frontend.c:148 (retroarch+0x000000415163)

SUMMARY: ThreadSanitizer: unlock of an unlocked mutex (or by a wrong thread) libretro-common/rthreads/rthreads.c:305 in slock_unlock
==================
Segmentation fault (core dumped)

### Steps to reproduce the bug

1. Refresh Room List
2. Try to join a room
3. Crash happens before the game loads

### Workaround

I was able to work around the issue by deferring the call to task_push_content_load_default() using a separate menu item to join the game. I do not have a suitable patch as I was testing with other existing menu items.

### Version/Commit

- RetroArch: fc2654c

### Environment information

- OS: Arch Linux x64
- Compiler: gcc 6.2.1

**Comment by bparker06** [comment]
Closing this to make a new issue so that bountysource will work correctly.
