### ISSUE TITLE
Retroarch crashes when trying 'save state' on Mupen64Plus

### ISSUE THREAD

**Issue by medwatt** [libretro/RetroArch#4686]
## Description
I'm using **Mupen64Plus OpenGL 2.5 938277a** in **RetroArch 1.4.1**. Games can be loaded and played normally. However, if I try to do 'Save State', Retroarch crashes. This does not happen with other cores.

### Steps to reproduce the bug
Every time I try to do 'Save State', RetroArch crashes.

### Environment information
- OS: Win 10 64-bit

### Notes
I raised this issue on the Mupen64Plus git and here is their reply:
_'It's a libretro bug; you need to file it with them. Save states work fine in our console front-end application.'_

**Comment by CromlechDE** [comment]
Same problem here on Windows 7 64-bit.

**Comment by bparker06** [comment]
Seems to be a null pointer dereference:

```
Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: そのようなファイルやディレクトリはありません.
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff4e5a277 in strlen () from /usr/lib/x86_64-linux-gnu/libasan.so.0
#2  0x00007fffd1133ba6 in strpbrk_reverse (needles=0x7fffd11a8b18 "/", haystack=0x0) at mupen64plus-core/src/main/util.c:211
#3  0x00007fffd1133c28 in namefrompath (path=0x0) at mupen64plus-core/src/main/util.c:227
#4  0x00007fffd113c80f in savestates_save_m64p_work (work=0x600c00058418) at mupen64plus-core/src/main/savestates.c:1036
#5  0x00007fffd11378fd in queue_work (work=0x600c00058418) at mupen64plus-core/src/main/workqueue.h:62
#6  0x00007fffd113fd67 in savestates_save_m64p (data=0x7fffbf167800) at mupen64plus-core/src/main/savestates.c:1314
#7  0x00007fffd118c692 in retro_serialize (data=0x7fffbf167800, size=16789316) at libretro/libretro.c:935
#8  0x0000000000415f8d in core_serialize (info=0x7fffffffc110) at core_impl.c:328
#9  0x0000000000442f48 in content_save_state (path=0x7fffffffc2b0 "/home/bp/saves/states/blast.state", save_to_disk=true, autosave=false) at tasks/task_save.c:1128
#10 0x0000000000422f5b in command_event_main_state (cmd=10) at command.c:1722
#11 0x000000000042377d in command_event (cmd=CMD_EVENT_SAVE_STATE, data=0x0) at command.c:1937
#12 0x000000000042ff35 in runloop_check_state (settings=0x7fffdc167800, current_input=562950221856768, old_input=562949953421312, trigger_input=268435456, input_driver_is_nonblock=false, sleep_ms=0x7fffffffdc30) at runloop.c:969
#13 0x00000000004306a9 in runloop_iterate (sleep_ms=0x7fffffffdc30) at runloop.c:1101
#14 0x0000000000413674 in rarch_main (argc=4, argv=0x7fffffffddc8, data=0x0) at frontend/frontend.c:129
#15 0x000000000041370e in main (argc=4, argv=0x7fffffffddc8) at frontend/frontend.c:147
(gdb) up
#1  0x00007ffff4e5a277 in strlen () from /usr/lib/x86_64-linux-gnu/libasan.so.0
(gdb) 
#2  0x00007fffd1133ba6 in strpbrk_reverse (needles=0x7fffd11a8b18 "/", haystack=0x0) at mupen64plus-core/src/main/util.c:211
211	    size_t stringlength = strlen(haystack), counter;
(gdb) print haystack
$1 = 0x0
(gdb) up
#3  0x00007fffd1133c28 in namefrompath (path=0x0) at mupen64plus-core/src/main/util.c:227
227	    const char* last_separator_ptr = strpbrk_reverse(OSAL_DIR_SEPARATORS, path);
(gdb) print path
$2 = 0x0
(gdb) up
#4  0x00007fffd113c80f in savestates_save_m64p_work (work=0x600c00058418) at mupen64plus-core/src/main/savestates.c:1036
1036	    main_message(M64MSG_STATUS, OSD_BOTTOM_LEFT, "Saved state to: %s", namefrompath(save->filepath));
(gdb) print save
$3 = (struct savestate_work *) 0x600c00058400
(gdb) print save->filepath
$4 = 0x0
```
