### ISSUE TITLE
Config Memory Corruption

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#5175]
## Description

Running `make clean && make SANITIZER=address && ./retroarch` results in a memory corruption issue:
https://gist.github.com/RobLoach/55ee48d28fc197405248463c00ba569f

### Expected behavior

It shouldn't break at the config file.

### Actual behavior

It breaks when working on the config file:
```
0x612000225441 is located 0 bytes to the right of 257-byte region [0x612000225340,0x612000225441)
allocated by thread T0 here:
    #0 0x7f1dd7316961 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98961)
    #1 0x4c7b79 in getaline libretro-common/file/config_file.c:97
    #2 0x4c7b79 in config_file_new_internal libretro-common/file/config_file.c:406
```

### Steps to reproduce the bug

`make clean && make SANITIZER=address && ./retroarch`

### Bisect Results

Haven't had time to run one yet.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: `b75bb073292d5cd81c423d44f9dec9e7363ca779`

### Environment information

- OS: Linux
- Compiler: gcc

**Comment by RobLoach** [comment]
Fixed by https://github.com/libretro/libretro-super/pull/493 .
