### ISSUE TITLE
Segmentation Fault when entering quick menu

### ISSUE THREAD

**Issue by tuldok89** [libretro/RetroArch#5466]
## Description

RetroArch crashes when trying to open quick menu. Crashes with Parallel N64, Beetle PSX, Mednafen GBA.

### Expected behavior

Should be able to open the quick menu.

### Actual behavior

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000000004f69f4 in xmb_draw_items (video_info=0x4cbf910,
    menu_disp_info=..., xmb=0x7e29e40, list=0x7e25940, stack=0x7e258a0,
    current=5, cat_selection_ptr=0, color=0x4cbf540, width=2560, height=1440)
    at menu/drivers/xmb.c:2272
2272    menu/drivers/xmb.c: No such file or directory.
(gdb) bt
#0  0x00000000004f69f4 in xmb_draw_items (video_info=0x4cbf910,
    menu_disp_info=..., xmb=0x7e29e40, list=0x7e25940, stack=0x7e258a0,
    current=5, cat_selection_ptr=0, color=0x4cbf540, width=2560, height=1440)
    at menu/drivers/xmb.c:2272
#1  0x00000000004f9488 in xmb_frame (data=0x7e29e40, video_info=0x4cbf910)
    at menu/drivers/xmb.c:3018
#2  0x0000000000500eef in menu_driver_frame (video_info=0x4cbf910)
    at menu/menu_driver.c:1550
#3  0x000000000057ab74 in gl_frame (data=0x779d5e0, frame=0x0,
    frame_width=640, frame_height=480, frame_count=68, pitch=0,
    msg=0xaa92e0 <video_driver_msg> "", video_info=0x4cbf910)
    at gfx/drivers/gl.c:1241
#4  0x000000000044693b in video_driver_frame (data=0x0, width=640,
    height=480, pitch=0) at gfx/video_driver.c:2387
#5  0x0000000000444d47 in video_driver_cached_frame ()
    at gfx/video_driver.c:1386
#6  0x00000000004fcd7c in menu_display_libretro (is_idle=false,
    rarch_is_inited=true, rarch_is_dummy_core=false) at menu/menu_driver.c:397
#7  0x00000000005010ba in menu_driver_render (is_idle=false,
    rarch_is_inited=true, rarch_is_dummy_core=false)
    at menu/menu_driver.c:1591
#8  0x0000000000407329 in runloop_check_state (settings=0x772b8f0,
    input_nonblock_state=false, sleep_ms=0x4cbfdd0) at retroarch.c:2520
#9  0x00000000004081ba in runloop_iterate (sleep_ms=0x4cbfdd0)
    at retroarch.c:3023
#10 0x000000000040175f in rarch_main (argc=1, argv=0x5f3bf50, data=0x0)
    at frontend/frontend.c:131
#11 0x00000000004017bf in SDL_main (argc=1, argv=0x5f3bf50)
    at frontend/frontend.c:151
#12 0x00000000007043a8 in main_getcmdline ()
#13 0x00000000004013f8 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
#14 0x00000000004014eb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:184
```

### Steps to reproduce the bug

1. Run a game.
2. Press F1 while in-game.

### Version/Commit

- RetroArch: 1.6.7 / a235c0b

### Environment information

- OS: Windows 10 Version 1703

**Comment by bparker06** [comment]
Can you try the latest nightly?

**Comment by tuldok89** [comment]
Latest nightly does not have this issue. It's fixed, I think.

**Comment by orbea** [comment]
If its now working can you close this issue? Thanks.
