### ISSUE TITLE
Segmentation Fault when entering quick menu AFTER loading state

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#5486]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

RetroArch crashes when trying to open quick menu AFTER successfully loaded state. If I not going to quick menu after loading state, all goes fine.

### Expected behavior

RA should not crash.

### Actual behavior

RA segfault.

### Steps to reproduce the bug

1. Open Retroarch
2. Load the game (tested on FCEUmm).
3. Load previously saved state.
4. Go to Quick menu.
5. Segfault after 3-5 seconds.

Backtrace:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000000004f3fa2 in string_is_empty (
    data=0xc923ef0 <error: Cannot access memory at address 0xc923ef0>)
    at ./libretro-common/include/string/stdstring.h:39
39      ./libretro-common/include/string/stdstring.h: No such file or directory.
(gdb) bt
#0  0x00000000004f3fa2 in string_is_empty (
    data=0xc923ef0 <error: Cannot access memory at address 0xc923ef0>)
    at ./libretro-common/include/string/stdstring.h:39
#1  0x00000000004f6146 in xmb_update_savestate_thumbnail_image (
    data=0xbef6a80) at menu/drivers/xmb.c:1129
#2  0x00000000004f650e in xmb_selection_pointer_changed (xmb=0xbef6a80,
    allow_animations=true) at menu/drivers/xmb.c:1219
#3  0x00000000004fd6ee in xmb_navigation_set (data=0xbef6a80, scroll=true)
    at menu/drivers/xmb.c:3857
#4  0x00000000005037b8 in menu_driver_navigation_set (scroll=true)
    at menu/menu_driver.c:1752
#5  0x0000000000504998 in menu_driver_ctl (
    state=MENU_NAVIGATION_CTL_DECREMENT, data=0x23f954)
    at menu/menu_driver.c:2248
#6  0x0000000000549fde in action_bind_up_generic (type=0,
    label=0xc89a8a0 "state_slot") at menu/cbs/menu_cbs_up.c:37
#7  0x000000000051ecf4 in menu_entry_action (entry=0x23fa20, i=4,
    action=MENU_ACTION_UP) at menu/widgets/menu_entry.c:429
#8  0x000000000055ed59 in generic_menu_iterate (data=0xbef2640,
    userdata=0xbef6a80, action=MENU_ACTION_UP)
    at menu/drivers/menu_generic.c:232
#9  0x0000000000503570 in menu_driver_iterate (iterate=0x23fbf0)
    at menu/menu_driver.c:1682
#10 0x0000000000407379 in runloop_check_state (settings=0x6d0bc40,
    input_nonblock_state=false, sleep_ms=0x23fdd0) at retroarch.c:2539
#11 0x000000000040825a in runloop_iterate (sleep_ms=0x23fdd0)
    at retroarch.c:3046
#12 0x000000000040175f in rarch_main (argc=1, argv=0x559c3d0, data=0x0)
    at frontend/frontend.c:131
#13 0x00000000004017bf in SDL_main (argc=1, argv=0x559c3d0)
    at frontend/frontend.c:151
#14 0x000000000072ba58 in main_getcmdline ()
#15 0x00000000004013f8 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
#16 0x00000000004014eb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:184

```

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: dc2664a4

### Environment information

- OS: Windows 8.1 x64
- Compiler: [In case you are running local builds]

**Comment by ofry** [comment]
Maybe it's related too:

Retroarch aab154fadfe423b5446658640124075ee8ee0ccd
Compiler: MSYS2 toolchain

If I compile Retroarch myself and try to load more older savestate, next I going to quick menu, then going to main menu: I got crash.

warning: Critical error detected c0000374

Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffd2a0b1bc0 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
```
(gdb) bt
#0  0x00007ffd2a0b1bc0 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00007ffd2a0b4e42 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
#2  0x00007ffd2a0b5a40 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
#3  0x00007ffd2a06a810 in ntdll!memset () from C:\Windows\SYSTEM32\ntdll.dll
#4  0x00007ffd279f1cb3 in msvcrt!_setjmp ()
   from C:\Windows\system32\msvcrt.dll
#5  0x00000000004d0ebf in xmb_update_savestate_thumbnail_path (
    data=data@entry=0xd20d030, i=i@entry=0) at menu/drivers/xmb.c:1041
#6  0x00000000004d9cfa in xmb_selection_pointer_changed (
    allow_animations=true, xmb=0xd20d030) at menu/drivers/xmb.c:1218
#7  xmb_navigation_set (data=0xd20d030, scroll=<optimized out>)
    at menu/drivers/xmb.c:3857
#8  0x00000000004dd499 in menu_driver_navigation_set (scroll=true)
    at menu/menu_driver.c:1752
#9  menu_driver_ctl (state=state@entry=MENU_NAVIGATION_CTL_CLEAR,
    data=data@entry=0x23d8df) at menu/menu_driver.c:2186
#10 0x0000000000517ed4 in menu_displaylist_process (info=info@entry=0x23d960)
    at menu/menu_displaylist.c:4261
#11 0x00000000004f5401 in generic_action_ok_displaylist_push (
    path=path@entry=0xd23b240 "Quick Menu", new_path=new_path@entry=0x0,
    label=label@entry=0xd23a1b0 "quick_menu", type=type@entry=110,
    idx=idx@entry=0, entry_idx=entry_idx@entry=0,
    action_type=action_type@entry=19) at menu/cbs/menu_cbs_ok.c:884
#12 0x00000000004f7833 in action_ok_push_default (
    path=0xd23b240 "Quick Menu", label=0xd23a1b0 "quick_menu", type=110,
    idx=0, entry_idx=0) at menu/cbs/menu_cbs_ok.c:3858
#13 0x00000000004f1115 in menu_entry_action (entry=entry@entry=0x23fb50,
    i=<optimized out>, action=action@entry=MENU_ACTION_OK)
    at menu/widgets/menu_entry.c:449
#14 0x000000000052569e in generic_menu_iterate (data=0xd208bf0,
    userdata=<optimized out>, action=MENU_ACTION_OK)
    at menu/drivers/menu_generic.c:232
#15 0x00000000004dcccc in menu_driver_iterate (iterate=iterate@entry=0x23fc50)
    at menu/menu_driver.c:1682
#16 0x0000000000403883 in runloop_check_state (
    settings=settings@entry=0x62783a0,
    input_nonblock_state=input_nonblock_state@entry=false, sleep_ms=0x23fdd0)
    at retroarch.c:2539
#17 0x00000000004075af in runloop_iterate (sleep_ms=sleep_ms@entry=0x23fdd0)
    at retroarch.c:3046
#18 0x0000000000401680 in rarch_main (argc=<optimized out>,
    argv=<optimized out>, data=0x0) at frontend/frontend.c:131
#19 0x000000000073d278 in main_getcmdline ()
#20 0x00000000004013f7 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:341
#21 0x00000000004014fb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:191
(gdb)
```

**Comment by twinaphex** [comment]
@ofry Try to see if this fixes it -

https://github.com/libretro/RetroArch/commit/d6b385d0b8b64547e6823e58b3391f6ac05af04a

**Comment by ofry** [comment]
```
warning: Critical error detected c0000374

Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffd2a0b1bc0 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffd2a0b1bc0 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00007ffd2a0b4e42 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
#2  0x00007ffd2a0b5a40 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
#3  0x00007ffd2a06a810 in ntdll!memset () from C:\Windows\SYSTEM32\ntdll.dll
#4  0x00007ffd279f1cb3 in msvcrt!_setjmp ()
   from C:\Windows\system32\msvcrt.dll
#5  0x00000000004d0f25 in xmb_update_savestate_thumbnail_path (
    data=data@entry=0xcd6cba0, i=i@entry=7) at menu/drivers/xmb.c:1042
#6  0x00000000004d97da in xmb_selection_pointer_changed (
    allow_animations=true, xmb=0xcd6cba0) at menu/drivers/xmb.c:1219
#7  xmb_navigation_pointer_changed (data=0xcd6cba0) at menu/drivers/xmb.c:3852
#8  0x00000000004dd382 in menu_driver_ctl (
    state=state@entry=MENU_NAVIGATION_CTL_INCREMENT, data=data@entry=0x23fa64)
    at menu/menu_driver.c:2261
#9  0x0000000000515844 in action_bind_down_generic (type=<optimized out>,
    label=<optimized out>) at menu/cbs/menu_cbs_down.c:37
#10 0x00000000004f107c in menu_entry_action (entry=entry@entry=0x23fb50,
    i=<optimized out>, action=action@entry=MENU_ACTION_DOWN)
    at menu/widgets/menu_entry.c:466
#11 0x00000000005256ae in generic_menu_iterate (data=0xcd68760,
    userdata=<optimized out>, action=MENU_ACTION_DOWN)
    at menu/drivers/menu_generic.c:232
#12 0x00000000004dccdc in menu_driver_iterate (iterate=iterate@entry=0x23fc50)
    at menu/menu_driver.c:1682
#13 0x0000000000403883 in runloop_check_state (
    settings=settings@entry=0x7a483a0,
    input_nonblock_state=input_nonblock_state@entry=false, sleep_ms=0x23fdd0)
    at retroarch.c:2539
#14 0x00000000004075af in runloop_iterate (sleep_ms=sleep_ms@entry=0x23fdd0)
    at retroarch.c:3046
#15 0x0000000000401680 in rarch_main (argc=<optimized out>,
    argv=<optimized out>, data=0x0) at frontend/frontend.c:131
#16 0x000000000073d278 in main_getcmdline ()
#17 0x00000000004013f7 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:341
#18 0x00000000004014fb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:191
(gdb)

```

**Comment by twinaphex** [comment]
https://github.com/libretro/RetroArch/commit/638a441530bbb70699e104c293ceb2f1274cf838

See if this fixes it.

**Comment by ofry** [comment]
Retroarch 638a44153

```
warning: Critical error detected c0000374

Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffd2a0b1bc0 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffd2a0b1bc0 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00007ffd2a0b4e42 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
#2  0x00007ffd2a0b5a40 in ntdll!RtlpNtMakeTemporaryKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
#3  0x00007ffd2a06a810 in ntdll!memset () from C:\Windows\SYSTEM32\ntdll.dll
#4  0x00007ffd279f1cb3 in msvcrt!_setjmp ()
   from C:\Windows\system32\msvcrt.dll
#5  0x00000000004d0f55 in xmb_update_savestate_thumbnail_path (
    data=0xce9d030, i=4) at menu/drivers/xmb.c:1040
#6  0x00000000004dd5c7 in menu_driver_ctl (
    state=state@entry=RARCH_MENU_CTL_UPDATE_SAVESTATE_THUMBNAIL_PATH,
    data=data@entry=0x0) at menu/menu_driver.c:2171
#7  0x00000000004ed6f3 in setting_handler (action=<optimized out>,
    setting=0xcf6a1f0) at menu/menu_setting.c:728
#8  menu_action_handle_setting (wraparound=false, action=<optimized out>,
    type=0, setting=0xcf6a1f0) at menu/menu_setting.c:794
#9  menu_setting_set (type=0, label=<optimized out>, action=<optimized out>,
    wraparound=<optimized out>) at menu/menu_setting.c:925
#10 0x00000000004f1157 in menu_entry_action (entry=entry@entry=0x23fb50,
    i=<optimized out>, action=action@entry=MENU_ACTION_RIGHT)
    at menu/widgets/menu_entry.c:460
#11 0x000000000052573e in generic_menu_iterate (data=0xce98bf0,
    userdata=<optimized out>, action=MENU_ACTION_RIGHT)
    at menu/drivers/menu_generic.c:232
#12 0x00000000004dcd6c in menu_driver_iterate (iterate=iterate@entry=0x23fc50)
    at menu/menu_driver.c:1682
#13 0x0000000000403883 in runloop_check_state (
    settings=settings@entry=0x79783a0,
    input_nonblock_state=input_nonblock_state@entry=false, sleep_ms=0x23fdd0)
    at retroarch.c:2539
#14 0x00000000004075af in runloop_iterate (sleep_ms=sleep_ms@entry=0x23fdd0)
    at retroarch.c:3046
#15 0x0000000000401680 in rarch_main (argc=<optimized out>,
    argv=<optimized out>, data=0x0) at frontend/frontend.c:131
#16 0x000000000073d318 in main_getcmdline ()
#17 0x00000000004013f7 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:341
#18 0x00000000004014fb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:191
(gdb)

```

**Comment by ofry** [comment]
I just switched savestate number from 0 (with picture) to -1 and return it to 0 again.

**Comment by dvessel** [comment]
The same crash happens when browsing through the core updates. Disabling save state thumbnails prevents the crashing.

**Comment by ofry** [comment]
Yes, it fixed now.

**Comment by retro-wertz** [comment]
nice.....................
