### ISSUE TITLE
RetroArch crashes if video_driver is set to an incorrect value.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#5568]
## Description

If the `video_driver` config setting is incorrectly set in `~/.config/retroarch/retroarch.cfg` to something like `video_driver = "opengl"` instead of the correct `video_driver = "gl"` RetroArch will segfault.  Interestingly this only occurs if `deps/SPIRV-Cross` is present and can be avoided with `./configure --disable-vulkan`.

### Expected behavior

RetroArch should ignore the incorrect setting and fall back to a safe default. A warning could also be printed in the log.

### Actual behavior

RetroArch will segfault.
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00000000005b76c7 in vulkan_context_init (vk=0x163dcc0, type=VULKAN_WSI_XCB)
    at gfx/common/vulkan_common.c:1764
#2  0x00000000005877c1 in gfx_ctx_x_init (video_info=0x7fffffffd930,
    data=0x163be20) at gfx/drivers_context/x_ctx.c:509
#3  0x000000000045becb in video_context_driver_init (data=0x163be20,
    ctx=0xcafde0 <gfx_ctx_x>, ident=0x7fb048ac2ad9 "", api=GFX_CTX_VULKAN_API,
    major=1, minor=0, hw_render_ctx=false) at gfx/video_driver.c:2744
#4  0x000000000045c04f in video_context_driver_find_driver (data=0x163be20,
    ident=0x7fb048ac2ad9 "", api=GFX_CTX_VULKAN_API, major=1, minor=0,
    hw_render_ctx=false) at gfx/video_driver.c:2795
#5  0x000000000045c0d0 in video_context_driver_init_first (data=0x163be20,
    ident=0x7fb048ac2ad9 "", api=GFX_CTX_VULKAN_API, major=1, minor=0,
    hw_render_ctx=false) at gfx/video_driver.c:2824
#6  0x00000000005abdbf in vulkan_get_context (vk=0x163be20)
    at gfx/drivers/vulkan.c:69
#7  0x00000000005aeb92 in vulkan_init (video=0x7fffffffdbe0,
    input=0xcfa300 <current_input>, input_data=0xcfa308 <current_input_data>)
    at gfx/drivers/vulkan.c:1106
#8  0x0000000000458df5 in video_driver_init_internal (
    video_is_threaded=0x7fffffffdca7) at gfx/video_driver.c:1038
#9  0x000000000045a1df in video_driver_init (video_is_threaded=0x7fffffffdca7)
    at gfx/video_driver.c:1733
#10 0x000000000045e862 in drivers_init (flags=255) at driver.c:351
#11 0x00000000004188e0 in retroarch_main_init (argc=1, argv=0x7fffffffe278)
    at retroarch.c:1294
#12 0x000000000042ee8a in content_load (info=0x7fffffffe140)
    at tasks/task_content.c:276
#13 0x000000000042ffd8 in task_load_content (content_info=0x7fffffffe140,
    content_ctx=0x7fffffffe060, launched_from_menu=true, launched_from_cli=true,
    error_string=0x7fffffffe058) at tasks/task_content.c:862
#14 0x00000000004313c1 in task_load_content_callback (
    content_info=0x7fffffffe140, loading_from_menu=true, loading_from_cli=true)
    at tasks/task_content.c:1533
#15 0x0000000000431531 in task_push_load_content_from_cli (core_path=0x0,
    fullpath=0x0, content_info=0x7fffffffe140, type=CORE_TYPE_PLAIN, cb=0x0,
    user_data=0x0) at tasks/task_content.c:1597
#16 0x0000000000414da3 in rarch_main (argc=1, argv=0x7fffffffe278, data=0x0)
    at frontend/frontend.c:115
#17 0x0000000000414e26 in main (argc=1, argv=0x7fffffffe278)
    at frontend/frontend.c:151
```
Full GDB log. - https://pastebin.com/K4ZfRQkH

### Steps to reproduce the bug

1. Change `video_driver` in `~/.config/retroarch/retroarch.cfg` to `video_driver = "foo"`.
2. Start RetroArch.
3. It crashes.

### Bisect Results

This was introduced with the Vulkan implementation.
```
adbf9fed161e72a2976e2e6d37851c368090e099 is the first bad commit
commit adbf9fed161e72a2976e2e6d37851c368090e099
Author: Hans-Kristian Arntzen <maister@archlinux.us>
Date:   Tue Feb 16 20:24:00 2016 +0100

    Vulkan implementation.

:100644 100644 cd80974377cb8beca6c837b48e674b7324cc9b12 d93773a455f5cacb8c23c0126b3e25228827effe M	.gitignore
:000000 100644 0000000000000000000000000000000000000000 9a7de532c9611e13decfa8fd26593b25b39e0580 A	.gitmodules
:100644 100644 85cd55a8c14d2d981fa1fe23e1606ab1e4e56b09 bcf331d68c59971ae8d32faf609693c7fd916820 M	Makefile
:100644 100644 856fccda1330a98a99912017ca3d694c2d6720a8 6604e1a8685a120c2444deed20e035ccd0524ce4 M	Makefile.common
:100644 100644 9911a756ba09c20ba696f96db5d3812ed37b72b4 21d4bad62af96ee8c0cb0e962ce7f25c69f5df61 M	command.c
:100644 100644 ab489b6631e4954a3f50e312c770de98b027a93b 8195c17f4878ea2ccd25dcbe6ff2aeb3d41e1bfd M	config.def.h
:040000 040000 c5fd51dbf75802b69274200eb46325767941f01f 9aabba29b1ffc79b1d01468f7e31477e05f90b64 M	cores
:040000 040000 1d774508df2088c8a8b8ac53232563b1eeafa3f4 506fa596b50822162fef9b284da3506d9157d128 M	deps
:100644 100644 2d202372d89c81724f78bbfe6e451289cb5aed88 e02073d3414beaa0be68962811ba6d5373cdd692 M	dir_list_special.c
:100644 100644 ff41b824f809042e5d87d14b846ddcc0ea038404 5629317eec112c0897e1d3162f310f61498b44d8 M	dynamic.c
:040000 040000 c36a9bf0c97f8e0491d97fac21eb9270c9843380 6b4d68f3176cf7f3b1a7fb68c362543c07891f72 M	gfx
:100644 100644 5e927c42229f502bd81ea5e016484d4c598ea701 a2315480e979848bc21110babbb27683844dffb4 M	libretro.h
:000000 100644 0000000000000000000000000000000000000000 2e7486ed31cbdfce87fc1242c57e3bef962d32c2 A	libretro_vulkan.h
:040000 040000 29c7254325e634346eb290f2bd495814250b1622 295e4a2edae4ebcc9ccd4ddf5bd33caf5c3c3557 M	menu
:040000 040000 b64eed40e95e3048b4f386daf571905e392b2b9b 34072c2a3970eec16e60d136aec5ec6090faac85 M	qb
:040000 040000 03fc38d615bb6e752781cda78cde459c3c606a62 8d646ac06d02f42f492c262c28cc36ff93e9351f M	record
:100644 100644 0836ca9053fca0a9bf74f3dedbe0955676c23de8 aa1f5bfae9933fefaf365b11ab991d1dd77dc438 M	runloop.c
```
adbf9fed161e72a2976e2e6d37851c368090e099

### Version/Commit
You can find this information under Information/System Information

- RetroArch: `RetroArch-2017.10.19_b0f8a57_master-x86_64-1_git`

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-7.2.0`

**Comment by orbea** [comment]
@maister Can you please take a look at this issue?

**Comment by orbea** [comment]
@Themaister Can you please take a look at this issue?
