### ISSUE TITLE
Trying to get achievement list to modified ROM - segfault.

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#5768]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Trying to get achievement list for modified ROM - segfault.

### Expected behavior

Should be empty list of achievements.

### Actual behavior

Segfault.

### Steps to reproduce the bug

1. Load Retroarch.
2. Open any patched game with core which support achievements.
3. Open Quick Menu.
4. Select "Achievement List".
5. Segfault.

Backtrace:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000000718e4d in cheevos_populate_menu (data=0x23f8a0)
    at cheevos/cheevos.c:2197
2197    cheevos/cheevos.c: No such file or directory.
(gdb) bt
#0  0x0000000000718e4d in cheevos_populate_menu (data=0x23f8a0)
    at cheevos/cheevos.c:2197
#1  0x000000000055ecde in menu_displaylist_ctl (
    type=DISPLAYLIST_ACHIEVEMENT_LIST, data=0x23f8a0)
    at menu/menu_displaylist.c:4738
#2  0x000000000053a965 in deferred_push_dlist (info=0x23f8a0,
    state=DISPLAYLIST_ACHIEVEMENT_LIST)
    at menu/cbs/menu_cbs_deferred_push.c:55
#3  0x000000000053aa01 in deferred_push_achievement_list (info=0x23f8a0)
    at menu/cbs/menu_cbs_deferred_push.c:78
#4  0x000000000055d787 in menu_displaylist_push (entry=0x23f950)
    at menu/menu_displaylist.c:4153
#5  0x000000000053726a in action_refresh_default (list=0x6e4d030,
    menu_list=0x6e4d0d0) at menu/cbs/menu_cbs_refresh.c:34
#6  0x0000000000526d59 in menu_entry_action (entry=0x23fa20, i=16,
    action=MENU_ACTION_OK) at menu/widgets/menu_entry.c:499
#7  0x0000000000568187 in generic_menu_iterate (data=0xd29fe70,
    userdata=0xd2a42b0, action=MENU_ACTION_OK)
    at menu/drivers/menu_generic.c:234
#8  0x0000000000509fa4 in menu_driver_iterate (iterate=0x23fbf0)
    at menu/menu_driver.c:1682
#9  0x0000000000407333 in runloop_check_state (settings=0x6dabd70,
    input_nonblock_state=false, sleep_ms=0x23fdd0) at retroarch.c:2546
#10 0x000000000040825e in runloop_iterate (sleep_ms=0x23fdd0)
    at retroarch.c:3067
#11 0x000000000040175f in rarch_main (argc=1, argv=0x4c1c3d0, data=0x0)
    at frontend/frontend.c:131
#12 0x00000000004017bf in SDL_main (argc=1, argv=0x4c1c3d0)
    at frontend/frontend.c:151
#13 0x0000000000739128 in main_getcmdline ()
#14 0x00000000004013f8 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
#15 0x00000000004014eb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:184

```

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: d973a1eea

### Environment information

- OS: Windows 8.1 Enterprise x64
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
Fixed https://github.com/libretro/RetroArch/pull/5769

**Comment by ofry** [comment]
Big thank you. This bug is fixed.
