### ISSUE TITLE
Retroarch freezes when laptop lid is closed

### ISSUE THREAD

**Issue by Igetin** [libretro/RetroArch#5922]
## Description

When the laptop lid is closed*, Retroarch freezes completely. The menu's background animation stops and the application won't react to any button or keyboard inputs. The program only closes when a kill signal is sent to the process. This freezing happens *only* when the Retroarch menu is visible, and it does not matter if the program is running in full screen mode or if it is the active window.

While this seems to be related to the display being off, running the command `xset dpms force off` interestingly does **not** freeze the program.

\* Note: closing the lid on my system only turns the screen off, the system won't go into sleep mode. Triggering sleep mode won't freeze Retroarch on this system.

[Here](https://github.com/libretro/RetroArch/files/1565074/RA-log.txt) is a log file just in case, though it does not seem like anything related to this is written in it.

### Expected behavior

The program should continue to work normally when the laptop lid is closed and opened.

### Actual behavior

The program appears freezed when the lid is opened.

### Steps to reproduce the bug

1. Have Retroarch running with the menu visible
2. Close the lid of the laptop

### Bisect Results

This has been happening since I first installed Retroarch on this system about a year ago, so versions older than 1.6.9 are affected too.

### Version/Commit

- RetroArch: 1.6.9 (e8b10d3)

### Environment information

- OS: Xubuntu 16.04 xenial, 64-bit
- Hardware: HP 635

**Comment by bparker06** [comment]
Can you run a debug build of the latest git commit under gdb? Then hit Ctrl-C inside gdb after it freezes and paste the result of the `thread apply all backtrace` command... might tell us what it is stuck on.

**Comment by Igetin** [comment]
Running commit 659b32a, here's the backtrace:

```
Thread 4 (Thread 0x7fffd8fdd700 (LWP 3471)):
#0  0x00007ffff016d70d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff6fc8861 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007ffff6fb9e11 in pa_mainloop_poll () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007ffff6fba4ae in pa_mainloop_iterate () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007ffff6fba560 in pa_mainloop_run () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007ffff6fc87a9 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007fffef584078 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so
#7  0x00007ffff6ad66ba in start_thread (arg=0x7fffd8fdd700) at pthread_create.c:333
#8  0x00007ffff01793dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7fffd9c6a700 (LWP 3449)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fffdde4f74b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#2  0x00007fffdde4f477 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#3  0x00007ffff6ad66ba in start_thread (arg=0x7fffd9c6a700) at pthread_create.c:333
#4  0x00007ffff01793dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7fffdf023700 (LWP 3448)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000586efe in scond_wait (cond=0x16bed50, lock=0x16bed20) at libretro-common/rthreads/rthreads.c:666
#2  0x0000000000430e4e in threaded_worker (userdata=0x0) at libretro-common/queues/task_queue.c:452
#3  0x0000000000586bf9 in thread_wrap (data_=0x16f39c0) at libretro-common/rthreads/rthreads.c:142
#4  0x00007ffff6ad66ba in start_thread (arg=0x7fffdf023700) at pthread_create.c:333
#5  0x00007ffff01793dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7fffdf057980 (LWP 3441)):
#0  0x00007ffff016d70d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fffeeca2c62 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fffeeca4617 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fffeeca4721 in xcb_wait_for_reply () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#4  0x00007ffff4c850a4 in ?? () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#5  0x0000000000590ea2 in gfx_ctx_x_swap_buffers (data=0x16b4400, data2=0x7fffffffd6c0)
    at gfx/drivers_context/x_ctx.c:373
#6  0x00000000005a19a0 in gl_frame (data=0x16b3bc0, frame=0xd81740 <dummy_pixels>, frame_width=4, 
    frame_height=4, frame_count=1000, pitch=8, msg=0xd817a0 <video_driver_msg> "FPS:   53.4", 
    video_info=0x7fffffffd6c0) at gfx/drivers/gl.c:1204
#7  0x0000000000462cfb in video_driver_frame (data=0xd81740 <dummy_pixels>, width=4, height=4, pitch=8)
    at gfx/video_driver.c:2405
#8  0x00000000004611cb in video_driver_cached_frame () at gfx/video_driver.c:1392
#9  0x000000000051a64b in menu_display_libretro (is_idle=false, rarch_is_inited=true, rarch_is_dummy_core=true)
    at menu/menu_driver.c:404
#10 0x000000000051ef23 in menu_driver_render (is_idle=false, rarch_is_inited=true, rarch_is_dummy_core=true)
    at menu/menu_driver.c:1609
#11 0x000000000041f546 in runloop_check_state (settings=0x7fffdf024010, input_nonblock_state=false, 
    sleep_ms=0x7fffffffdb50) at retroarch.c:2557
#12 0x0000000000420480 in runloop_iterate (sleep_ms=0x7fffffffdb50) at retroarch.c:3072
#13 0x0000000000419d97 in rarch_main (argc=1, argv=0x7fffffffdc88, data=0x0) at frontend/frontend.c:131
#14 0x0000000000419e08 in main (argc=1, argv=0x7fffffffdc88) at frontend/frontend.c:151
```

**Comment by Igetin** [comment]
The freeze doesn’t occur on the same hardware after I upgraded to Xubuntu 18.04, when running on RetroArch 1.7.6.
