### ISSUE TITLE
Crash when running a game while scanning a directory

### ISSUE THREAD

**Issue by BPaden** [libretro/RetroArch#5944]
I've run into a weird edge case where scanning a directory and then running a game sometimes causes retroarch to segfault, and other times causes the scanning to halt and incorrectly report completion. I've noted this behavior in several cores. I so far haven't reproduced a crash using gl, but the scanning does halt. So far I've been able to reproduce one of these two behaviors every time I run a scan.

I've added a log and a backtrace. I'll try to bisect this later if nothing jumps out at anyone.

```
[INFO] RetroArch 1.6.9 (Git 05820677db)
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 
Built: Dec 20 2017
[INFO] Version: 1.6.9
[INFO] Git: 05820677db
[INFO] =================================================
[INFO] [Config]: Loading default config.
[INFO] [Config]: loading config from: (null).
[INFO] Looking for config in: "/home/aaron/.config/retroarch/retroarch.cfg".
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] Found shader "/home/aaron/.config/retroarch/shaders/retroarch.slangp"
[INFO] [Video]: Video @ fullscreen
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] Vulkan dynamic library loaded.
[INFO] [Vulkan]: Detecting screen resolution 1440x900.
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [GLX]: Using Xinerama on screen #0.
[INFO] [GLX]: X = 0, Y = 0, W = 1440, H = 900.
[INFO] [GLX]: Using windowed fullscreen.
WARNING: radv is not a conformant vulkan implementation, testing use only.
[INFO] [Vulkan]: Using GPU: AMD RADV OLAND
[INFO] [Vulkan]: Queue family 0 supports 1 sub-queues.
[INFO] [Vulkan]: Swapchain supports present mode: 0.
[INFO] [Vulkan]: Swapchain supports present mode: 1.
[INFO] [Vulkan]: Swapchain supports present mode: 2.
[INFO] [Vulkan]: Creating swapchain with present mode: 2
[INFO] [Vulkan]: Using swapchain size 1440 x 900.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 1440x900
[INFO] [Vulkan]: Using RGB565 format.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [slang]: Compiling shader "/home/aaron/.config/retroarch/shaders/shaders_slang/ntsc/shaders/mame-ntsc/mame-ntsc.slang".
[INFO] [slang]: Using render target format R8G8B8A8_UNORM for pass output #0.
[INFO] [slang]: Compiling shader "/home/aaron/.config/retroarch/shaders/shaders_slang/ntsc/shaders/mame-ntsc/mame-postproc.slang".
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [Vulkan filter chain]: Creating framebuffer 512 x 512 (max 1 level(s)).
[INFO] [slang]: Reflection
[INFO] [slang]:   Textures:
[INFO] [slang]:      Source (#0)
[INFO] [slang]:
[INFO] [slang]:   Uniforms (Vertex: yes, Fragment: yes):
[INFO] [slang]:   Push Constants (Vertex: yes, Fragment: yes):
[INFO] [slang]:      MVP (Offset: 0)
[INFO] [slang]:      SourceSize (#0) (PushOffset: 0)
[INFO] [slang]:
[INFO] [slang]:   Parameters:
[INFO] [Vulkan]: Push Constant Block: 52 bytes.
[INFO] [slang]: Building pass #1 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]:   Textures:
[INFO] [slang]:      Source (#0)
[INFO] [slang]:
[INFO] [slang]:   Uniforms (Vertex: yes, Fragment: yes):
[INFO] [slang]:   Push Constants (Vertex: yes, Fragment: yes):
[INFO] [slang]:      MVP (Offset: 0)
[INFO] [slang]:      FrameCount (PushOffset: 48)
[INFO] [slang]:      OriginalSize (#0) (PushOffset: 16)
[INFO] [slang]:      SourceSize (#0) (PushOffset: 0)
[INFO] [slang]:
[INFO] [slang]:   Parameters:
[INFO] [slang]:     #6 (PushOffset: 52)
[INFO] [slang]:     #7 (PushOffset: 56)
[INFO] [slang]:     #8 (PushOffset: 60)
[INFO] [slang]:     #9 (PushOffset: 64)
[INFO] [slang]:     #10 (PushOffset: 68)
[INFO] [Vulkan]: Push Constant Block: 72 bytes.
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[INFO] [udev]: Plugged pad: Microsoft X-Box 360 pad (1118:654) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event14) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event14) supports 16 force feedback effects.
[INFO] [Autoconf]: 187 profiles found.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Autoconf]: selected configuration: /home/aaron/.config/retroarch/autoconfig/udev/Microsoft_X-Box_360_pad.cfg
[INFO] [X11]: Suspending screensaver (X11, xdg-screensaver).
[INFO] [Video]: Found display server: x11
[INFO] [OpenAL]: Using 11 buffers of 1024 bytes.
[INFO] [Menu]: Found menu display driver: "menu_display_vulkan".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
Protocol error: bad 3 (Window); Sequence Number 11
 Opcode (20, 0) = GetProperty
 Bad resource 0 (0x0)
 at -e line 15.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/home/aaron/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/home/aaron/.config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/home/aaron/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/home/aaron/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/home/aaron/.config/retroarch/content_image_history.lpl].
[INFO] [Vulkan]: VSync => on
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [Vulkan filter chain]: Creating framebuffer 512 x 512 (max 1 level(s)).
[INFO] [slang]: Reflection
[INFO] [slang]:   Textures:
[INFO] [slang]:      Source (#0)
[INFO] [slang]:
[INFO] [slang]:   Uniforms (Vertex: yes, Fragment: yes):
[INFO] [slang]:   Push Constants (Vertex: yes, Fragment: yes):
[INFO] [slang]:      MVP (Offset: 0)
[INFO] [slang]:      SourceSize (#0) (PushOffset: 0)
[INFO] [slang]:
[INFO] [slang]:   Parameters:
[INFO] [Vulkan]: Push Constant Block: 52 bytes.
[INFO] [slang]: Building pass #1 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]:   Textures:
[INFO] [slang]:      Source (#0)
[INFO] [slang]:
[INFO] [slang]:   Uniforms (Vertex: yes, Fragment: yes):
[INFO] [slang]:   Push Constants (Vertex: yes, Fragment: yes):
[INFO] [slang]:      MVP (Offset: 0)
[INFO] [slang]:      FrameCount (PushOffset: 48)
[INFO] [slang]:      OriginalSize (#0) (PushOffset: 16)
[INFO] [slang]:      SourceSize (#0) (PushOffset: 0)
[INFO] [slang]:
[INFO] [slang]:   Parameters:
[INFO] [slang]:     #6 (PushOffset: 52)
[INFO] [slang]:     #7 (PushOffset: 56)
[INFO] [slang]:     #8 (PushOffset: 60)
[INFO] [slang]:     #9 (PushOffset: 64)
[INFO] [slang]:     #10 (PushOffset: 68)
[INFO] [Vulkan]: Push Constant Block: 72 bytes.
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[INFO] [Vulkan]: VSync => on
[INFO] [Vulkan filter chain]: Updating framebuffer size 4 x 4.
[INFO] [Vulkan]: Swapchain supports present mode: 0.
[INFO] [Vulkan]: Swapchain supports present mode: 1.
[INFO] [Vulkan]: Swapchain supports present mode: 2.
[INFO] [Vulkan]: Creating swapchain with present mode: 2
[INFO] [Vulkan]: Using swapchain size 1440 x 900.
[INFO] [Vulkan]: Recycled old swapchain.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [Vulkan filter chain]: Creating framebuffer 512 x 512 (max 1 level(s)).
[INFO] [slang]: Reflection
[INFO] [slang]:   Textures:
[INFO] [slang]:      Source (#0)
[INFO] [slang]:
[INFO] [slang]:   Uniforms (Vertex: yes, Fragment: yes):
[INFO] [slang]:   Push Constants (Vertex: yes, Fragment: yes):
[INFO] [slang]:      MVP (Offset: 0)
[INFO] [slang]:      SourceSize (#0) (PushOffset: 0)
[INFO] [slang]:
[INFO] [slang]:   Parameters:
[INFO] [Vulkan]: Push Constant Block: 52 bytes.
[INFO] [slang]: Building pass #1 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]:   Textures:
[INFO] [slang]:      Source (#0)
[INFO] [slang]:
[INFO] [slang]:   Uniforms (Vertex: yes, Fragment: yes):
[INFO] [slang]:   Push Constants (Vertex: yes, Fragment: yes):
[INFO] [slang]:      MVP (Offset: 0)
[INFO] [slang]:      FrameCount (PushOffset: 48)
[INFO] [slang]:      OriginalSize (#0) (PushOffset: 16)
[INFO] [slang]:      SourceSize (#0) (PushOffset: 0)
[INFO] [slang]:
[INFO] [slang]:   Parameters:
[INFO] [slang]:     #6 (PushOffset: 52)
[INFO] [slang]:     #7 (PushOffset: 56)
[INFO] [slang]:     #8 (PushOffset: 60)
[INFO] [slang]:     #9 (PushOffset: 64)
[INFO] [slang]:     #10 (PushOffset: 68)
[INFO] [Vulkan]: Push Constant Block: 72 bytes.
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[INFO] [Vulkan filter chain]: Updating framebuffer size 4 x 4.
[INFO] Using content: /data/roms/a5200/BerZerk (USA).7z.
[INFO] arg #0: retroarch
[INFO] arg #1: /data/roms/a5200/BerZerk (USA).7z
[INFO] arg #2: -c
[INFO] arg #3: /home/aaron/.config/retroarch/retroarch.cfg
[INFO] arg #4: -L
[INFO] arg #5: /home/aaron/.config/retroarch/cores/atari800_libretro.so
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [XINERAMA]: Saved monitor #0.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] Set config file to : /home/aaron/.config/retroarch/retroarch.cfg
[INFO] RetroArch 1.6.9 (Git 05820677db)
[INFO] Redirecting save file to "/data/roms/a5200/BerZerk (USA).srm".
[INFO] Redirecting savestate to "/data/roms/a5200/BerZerk (USA).state".
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 
Built: Dec 20 2017
[INFO] Version: 1.6.9
[INFO] Git: 05820677db
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/home/aaron/.config/retroarch/cores/atari800_libretro.so"
[INFO] [overrides] no core-specific overrides found at /home/aaron/.config/retroarch/config/Atari800/Atari800.cfg.
[INFO] [overrides] no game-specific overrides found at /home/aaron/.config/retroarch/config/Atari800/BerZerk (USA).cfg.
[INFO] Shaders: preset directory: /home/aaron/.config/retroarch/shaders/presets
[INFO] Shaders: no game-specific preset found at /home/aaron/.config/retroarch/shaders/presets/Atari800/BerZerk (USA).slangp.
[INFO] Shaders: no core-specific preset found at /home/aaron/.config/retroarch/shaders/presets/Atari800/Atari800.slangp.
[INFO] Environ SET_CONTROLLER_INFO.
[INFO] Controller port: 1
[INFO]    ATARI Joystick (ID: 513)
[INFO]    ATARI Keyboard (ID: 259)
[INFO] Controller port: 2
[INFO]    ATARI Joystick (ID: 513)
[INFO]    ATARI Keyboard (ID: 259)
[INFO] Environ SET_VARIABLES.
[INFO] Remaps: remap directory: /home/aaron/.config/retroarch/config/remaps
[INFO] Remaps: no game-specific remap found at /home/aaron/.config/retroarch/config/remaps/Atari800/BerZerk (USA).rmp.
[INFO] Remaps: no core-specific remap found at /home/aaron/.config/retroarch/config/remaps/Atari800/Atari800.rmp.
[INFO] Redirecting save file to "/data/roms/a5200/BerZerk (USA).srm".
[INFO] Redirecting savestate to "/data/roms/a5200/BerZerk (USA).state".
[INFO] Environ GET_LOG_INTERFACE.
[INFO] Environ SYSTEM_DIRECTORY: "/data/roms/bios".
[INFO] Environ CORE_ASSETS_DIRECTORY: "/home/aaron/.config/retroarch/downloads".
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, User 1, Button "B (bottom)" => "B"
[INFO] 	RetroPad, User 1, Button "Y (left)" => "Y"
[INFO] 	RetroPad, User 1, Button "Select" => "Select"
[INFO] 	RetroPad, User 1, Button "Start" => "Start"
[INFO] 	RetroPad, User 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, User 1, Button "A (right)" => "A"
[INFO] 	RetroPad, User 1, Button "X (up)" => "X"
[INFO] 	RetroPad, User 1, Button "L" => "L"
[INFO] 	RetroPad, User 1, Button "R" => "R"
[INFO] 	RetroPad, User 1, Button "L2" => "L2"
[INFO] 	RetroPad, User 1, Button "R2" => "R2"
[INFO] 	RetroPad, User 1, Button "L3" => "L3"
[INFO] 	RetroPad, User 1, Button "R3" => "R3"
[INFO] Environ GET_VARIABLE atari800_opt1:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_opt2:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_resolution:
[INFO] 	336x240
[libretro-atari800]: Got size: 336 x 240.
[INFO] Environ GET_VARIABLE atari800_system:
[INFO] 	5200
[INFO] Environ GET_VARIABLE atari800_ntscpal:
[INFO] 	NTSC
[INFO] Environ GET_VARIABLE atari800_internalbasic:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_sioaccel:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_cassboot:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_artifacting:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_keyboard:
[INFO] 	poll
[INFO] Content loading skipped. Implementation will load it on its own.
[INFO] Environ SET_KEYBOARD_CALLBACK.
[INFO] Environ GET_VARIABLE atari800_opt1:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_opt2:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_resolution:
[INFO] 	336x240
[libretro-atari800]: Got size: 336 x 240.
[INFO] Environ GET_VARIABLE atari800_system:
[INFO] 	5200
[INFO] Environ GET_VARIABLE atari800_ntscpal:
[INFO] 	NTSC
[INFO] Environ GET_VARIABLE atari800_internalbasic:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_sioaccel:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_cassboot:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_artifacting:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_keyboard:
[INFO] 	poll
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] Environ GET_VARIABLE atari800_opt1:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_opt2:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_resolution:
[INFO] 	336x240
[libretro-atari800]: Got size: 336 x 240.
[INFO] Environ GET_VARIABLE atari800_system:
[INFO] 	5200
[INFO] [CHEEVOS]: system RAM: (nil) 0
[INFO] [CHEEVOS]: save RAM:   (nil) 0
[INFO] [CHEEVOS]: video RAM:  (nil) 0
[INFO] [CHEEVOS]: RTC:        (nil) 0
[INFO] Environ GET_VARIABLE atari800_ntscpal:
[INFO] 	NTSC
[INFO] Environ GET_VARIABLE atari800_internalbasic:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_sioaccel:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_cassboot:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_artifacting:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE atari800_keyboard:
[INFO] 	poll
[libretro INFO] AV_INFO: width=336 height=240
[libretro INFO] AV_INFO: max_width=400 max_height=300
[libretro INFO] AV_INFO: aspect_ratio = 1.333333
[libretro INFO] AV_INFO: fps = 49.860760 sample_rate = 44100.000000
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Timings deviate too much. Will not adjust. (Display = 59.94 Hz, Game = 49.86 Hz)
[INFO] Found shader "/home/aaron/.config/retroarch/shaders/retroarch.slangp"
[INFO] [Video]: Video @ fullscreen
[ERROR] [Wayland]: Failed to connect to Wayland server.
[WARN] Failed to bind API (#6, version 1.0) on context driver "x-egl".
[WARN] Failed to bind API (#6, version 1.0) on context driver "kms".
[WARN] Failed to bind API (#6, version 1.0) on context driver "sdl_gl".
[INFO] Vulkan dynamic library loaded.
[ERROR] [Vulkan]: Could not find instance extensions. Will attempt without them.
[INFO] [Vulkan]: Detecting screen resolution 0x0.
WARNING: radv is not a conformant vulkan implementation, testing use only.
```

```
#0  0x0000000000000000 in ?? ()
#1  0x000055555570a00d in vulkan_create_display_surface (info=0x7fffffffb9a0, height=<synthetic pointer>, width=<synthetic pointer>, vk=0x555557643960)
    at gfx/common/vulkan_common.c:1877
#2  vulkan_surface_create (vk=vk@entry=0x555557643960, type=type@entry=VULKAN_WSI_DISPLAY, display=display@entry=0x7fffffffb9a0, surface=surface@entry=0x0, width=width@entry=0, 
    height=height@entry=0, swap_interval=1) at gfx/common/vulkan_common.c:2147
#3  0x00005555558890ea in gfx_ctx_khr_display_set_video_mode (data=0x555557643960, video_info=<optimized out>, width=<optimized out>, height=<optimized out>, 
    fullscreen=<optimized out>) at gfx/drivers_context/khr_display_ctx.c:130
#4  0x00005555555dbc85 in video_context_driver_set_video_mode (mode_info=mode_info@entry=0x7fffffffbbf4) at gfx/video_driver.c:3028
#5  0x00005555555e0aff in video_context_driver_set_video_mode (mode_info=mode_info@entry=0x7fffffffbbf4) at gfx/video_driver.c:3023
#6  0x000055555570442d in vulkan_init (video=video@entry=0x7fffffffbd30, input=0x555555d45270 <current_input>, input_data=input_data@entry=0x555555d45268 <current_input_data>)
    at gfx/drivers/vulkan.c:1152
#7  0x00005555555de20e in video_driver_init_internal (video_is_threaded=0x7fffffffbd57) at gfx/video_driver.c:1044
#8  video_driver_init (video_is_threaded=video_is_threaded@entry=0x7fffffffbdb7) at gfx/video_driver.c:1742
#9  0x00005555555e2d62 in drivers_init (flags=flags@entry=255) at driver.c:346
#10 0x000055555559c7ac in retroarch_main_init (argc=7, argv=argv@entry=0x7fffffffc3b0) at retroarch.c:1301
#11 0x00005555555abc17 in content_load (info=info@entry=0x7fffffffc660) at tasks/task_content.c:270
#12 0x00005555555ac14f in task_load_content (content_info=content_info@entry=0x7fffffffc660, content_ctx=content_ctx@entry=0x7fffffffc680, 
    launched_from_menu=launched_from_menu@entry=true, launched_from_cli=launched_from_cli@entry=false, error_string=error_string@entry=0x7fffffffc658) at tasks/task_content.c:856
#13 0x00005555555ae3db in command_event_cmd_exec (launched_from_cli=false, error_string=0x7fffffffc658, content_ctx=0x7fffffffc680, data=<optimized out>)
    at tasks/task_content.c:998
#14 task_push_load_content_from_playlist_from_menu (core_path=core_path@entry=0x7fffffffc7a0 "/home/aaron/.config/retroarch/cores/gambatte_libretro.so", 
    fullpath=0x555557135e00 "/data/roms/gb/Pac-Man (USA).gb.7z#Pac-Man (USA).gb", label=0x555557135e40 "Pac-Man (USA)", content_info=content_info@entry=0x7fffffffc780, 
    cb=cb@entry=0x0, user_data=user_data@entry=0x0) at tasks/task_content.c:1211
#15 0x000055555569bc9f in default_action_ok_load_content_from_playlist_from_menu (entry_label=<optimized out>, path=<optimized out>, 
    _path=0x7fffffffc7a0 "/home/aaron/.config/retroarch/cores/gambatte_libretro.so") at menu/cbs/menu_cbs_ok.c:1398
#16 action_ok_playlist_entry_collection (path=<optimized out>, label=<optimized out>, type=<optimized out>, idx=<optimized out>, entry_idx=663) at menu/cbs/menu_cbs_ok.c:1577
#17 0x000055555569459e in menu_entry_action (entry=entry@entry=0x7fffffffd850, i=0, action=action@entry=MENU_ACTION_OK) at menu/widgets/menu_entry.c:452
#18 0x00005555556c9ca7 in generic_menu_iterate (data=0x555556d3de70, userdata=<optimized out>, action=MENU_ACTION_OK) at menu/drivers/menu_generic.c:234
#19 0x000055555568014f in menu_driver_iterate (iterate=iterate@entry=0x7fffffffd8f0) at menu/menu_driver.c:1683
#20 0x0000555555598aed in runloop_check_state (settings=settings@entry=0x7ffff7fc7010, input_nonblock_state=input_nonblock_state@entry=false, sleep_ms=0x7fffffffdaac)
    at retroarch.c:2553
#21 0x000055555559cc69 in runloop_iterate (sleep_ms=0x7fffffffdaac) at retroarch.c:3072
#22 0x00005555555967e1 in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:131
#23 0x00007ffff0db8f4a in __libc_start_main () from /usr/lib/libc.so.6
#24 0x00005555555939da in _start ()
```

**Comment by orbea** [comment]
@BPaden Is this still an issue? If so can you please provide more info? The issue template will give a good idea of helpful info as will knowing if any specific roms are causing this.

**Comment by BPaden** [comment]
Looks like this is no longer an issue.
