### ISSUE TITLE
Cheat list buggy after 99th code

### ISSUE THREAD

**Issue by Subarasheese** [libretro/RetroArch#6060]
## Description

Retroarch (on both XMB and rgui) is displaying wrong toggles (displaying inputs) for cheats past the 99th cheat code from the loaded cheat file list. See the attached screenshot.

![image](https://user-images.githubusercontent.com/35178075/34644010-7ee014f2-f30d-11e7-8ddb-439da1b7df11.png)

### Expected behavior

Display the code and ON/OFF for each cheat code post the 99th.

See example:

https://github.com/libretro/libretro-database/blob/master/cht/Nintendo%20-%20Game%20Boy%20Advance/Pokemon%20-%20Emerald%20Version%20(USA%2C%20Europe)%20(Code%20Breaker).cht

### Steps to reproduce the bug

1. Open content
2. Select a big cheat file (with more than a hundred codes)
3. Scroll down the cheat list

### Version/Commit
Retroarch Version 1.7.0

### Environment information

- OS: Windows 10

Core affected: mGBA 0.6.1 05e2ff4
Game: Pokemon Emerald (USA)
Cheat file used: https://github.com/libretro/libretro-database/blob/master/cht/Nintendo%20-%20Game%20Boy%20Advance/Pokemon%20-%20Emerald%20Version%20(USA%2C%20Europe)%20(Code%20Breaker).cht

**Comment by retro-wertz** [comment]
to make troubleshooting faster, should just post core affected, and what
game and since cheat file is not illegal should best to provide it as wel..

**Comment by Subarasheese** [comment]
Core affected: mGBA 0.6.1 05e2ff4
Game: Pokemon Emerald (USA)
Cheat file used: https://github.com/libretro/libretro-database/blob/master/cht/Nintendo%20-%20Game%20Boy%20Advance/Pokemon%20-%20Emerald%20Version%20(USA%2C%20Europe)%20(Code%20Breaker).cht

**Comment by bparker06** [comment]
Just FYI that particular cheat file looks *very* corrupted. For example:

```
--- "Pokemon - Emerald Version (USA, Europe) (Code Breaker).cht"        2018-01-09 11:19:15.171785700 -0500
+++ "Pokemon - Emerald Version (USA, Europe) (Code Breaker) fixed.cht"  2018-01-09 11:46:02.729813400 -0500
@@ -1,15 +1,20 @@
 cheats = 148

+cheat0_desc = "Dummy Code, Don't Use"
+cheat0_code = "0"
+cheat0_enable = false
+
 cheat1_desc = "Master Code"
 cheat1_code = "9266FA6C+97BD+905B5ED3+5F81+B76A68E5+FAB1"
 cheat1_enable = false

 cheat2_desc = "Skip Intro"
-cheat_2code = "B0555789+8BBD+F95340E4+DFFD+B02FC0E0+7138+8027CBC0+8B39"
+cheat2_code = "B0555789+8BBD+F95340E4+DFFD+B02FC0E0+7138+8027CBC0+8B39"
+cheat2_enable = false

 cheat3_desc = "Change PLYR Name (View Trainer Card)"
 cheat3_code = "49B17DAD+4E7F+79C3E2C4+94FE+7AD8B975+DCC0+C04F4AC8+47FF+70D363C0+80BF+7AC1B975+F6C1"
-cheat_enable = false
+cheat3_enable = false

 cheat4_desc = "No Random Battles"
 cheat4_code = "32C96211+F488"
@@ -37,7 +42,7 @@

 cheat10_desc = "Maximum Hearts"
 cheat10_code = "A62154B3+792C+2FB8E027+164F"
-cheat_enable = false
+cheat10_enable = false

 cheat11_desc = "Max Coins from Pokies"
 cheat11_code = "30DAA34B+C79B+1FB97F95+4367"
@@ -83,8 +88,7 @@
 cheat21_code = "C2711CBA+6F6B+72EA7742+0E4D"
 cheat21_enable = false

-cheat22_desc = "Gain 5000 Exp (Press R+A whilst
-EXP Gained is displayed)
+cheat22_desc = "Gain 5000 Exp (Press R+A whilst EXP Gained is displayed)"
 cheat22_code = "A744170A+A996+9B540825+258E"
 cheat22_enable = false

@@ -174,14 +178,14 @@

 cheat44_desc = "Choose Latias/Latios [L+Sel]"
 cheat44_code = "AE45D79E+2DF6+06BCBD33+5902+3B3D7845+CC00"
-cheat544_enable = false
+cheat44_enable = false

 cheat45_desc = "Battle Latias/Latios [R+Sel]"
 cheat45_code = "AE45D69E+ADF6+06BC3C33+D902+BBBC7843+4C16"
 cheat45_enable = false

 cheat46_desc = "Receive Starter Info"
-cheat46_code = "Press L+R+Dwn.Use with 'Starter to Receive code'"
+cheat46_code = "Press L+R+Dwn. Use with Starter to Receive code"
 cheat46_enable = false

 cheat47_desc = "Receive Starter"
@@ -189,14 +193,14 @@
 cheat47_enable = false

 cheat48_desc = "Starter to Receive Info"
-cheat48_code = "Choose which starter you want. Use with 'Receive Starter Code'. Use one per load."
+cheat48_code = "Choose which starter you want. Use with Receive Starter Code. Use one per load."
 cheat48_enable = false

-cheat49 = "Starter to Receive - Cyndaquil"
+cheat49_desc = "Starter to Receive - Cyndaquil"
 cheat49_code = "A72554BA+6936+79C1E0A4+F3F3+A72554BA+6936+F073C3C8+3C3C"
 cheat49_enable = false

-cheater50_desc = "Starter to Receive - Totodile"
+cheat50_desc = "Starter to Receive - Totodile"
 cheat50_code = "A72554BA+6936+79C1E0A4+F3F3+A72554BA+6936+F919D4A5+C2F9"
 cheat50_enable = false

@@ -274,18 +278,22 @@

 cheat68_desc = "Max Lvl Gold (Smart)"
 cheat68_code = "DF5CCB07+4CC8+CF47DEDE+29E0"
-cheat_enable = false
+cheat68_enable = false

 cheat69_desc = "Max Lvl Gold (Tough)"
 cheat69_code = "DF5CCB07+4CC8+CF469F4E+29E0"
 cheat69_enable = false

 cheat70_desc = "Re-Battle Activator [Select+A+A]
-cheat70code = "10C6FC61+E2C9+F94A157D+DCD8+10C6FC61+E2C9+805D5CA1+C2B5"
+cheat70_code = "10C6FC61+E2C9+F94A157D+DCD8+10C6FC61+E2C9+805D5CA1+C2B5"
 cheat70_enable = false

-cheat71_desc = "Re-Battle Modifier Info"
-cheat71_code = "Use with Re-Battle Activator. Use one per load."
+cheat71_desc = "Re-Battle Modifier Info. Use with Re-Battle Activator. Use one per load."
+cheat71_code = "0"
+cheat71_enable = false
+
+cheat72_desc = "Dummy Code, Don't Use"
+cheat72_code = "0"
 cheat72_enable = false

 cheat73_desc = "Gym Leader Roxanne"
@@ -322,7 +330,7 @@

 cheat81_desc = "Elite Four Sidney"
 cheat81_code = "10C6FC61+E2C9+F4789681+D2F9"
-cheat_81_enable = false
+cheat81_enable = false

 cheat82_desc = "Elite Four Phoebe"
 cheat82_code = "10C6FC61+E2C9+F279D713+52C1"
@@ -372,8 +380,8 @@
 cheat93_code = "DE41DF9E+3DF6+79B83615+175A+DE41DF9E+3DF6+895C9D35+C6D5"
 cheat93_enable = false

-cheat94_desc ="Warp to Location"
-cheat94_code = "Hold L whilst entering/exiting."
+cheat94_desc = "Warp to Location. Hold L whilst entering/exiting."
+cheat94_code = "0"
 cheat94_enable = false

 cheat95_desc = "Faraway Island"
@@ -464,7 +472,6 @@
 cheat116_code = "19C67C65+6689+12B93E13+D64D"
 cheat116_enable = false

-
 cheat117_desc = "Purchase Items Info"
 cheat117_code = "Use at the MOD shop. Select only one item."
 cheat117_enable = false
@@ -551,7 +558,7 @@

 cheat138_desc = "Clone Box PKMN Part 1/2"
 cheat138_code = "F67A165B+E941+7F8A357F+AC8B+14882B81+FB31+B96CC0AC+C32F+8B5C1E8D+97FD+119DEA92+76CF+2FD2BFAD+8677+19CD7E87+648C"
-cheat138_enable =false
+cheat138_enable = false

 cheat139_desc = "Clone Box PKMN Part 2/2"
 cheat139_code = "F476D4E2+45F8+8251BA9B+B2BB+6089A790+F649+0D87A23D+ACC0+218CBF01+E60C+2E87AA2B+ACD0+E17A016A+AB22+8A8CD33F+1D8C+194B9F95+5D0C+7A40BD55+F6C9"
```

While it doesn't seem to fix the issue, it still needs to be fixed on its own. Unfortunately we don't really have any QA checks in place for these and a lot of them have mistakes like this or contain code formats that are incompatible with some cores.

**Comment by bparker06** [comment]
I was also able to get this crash under ASAN immediately after loading a cheat file:

```
==2568== ERROR: AddressSanitizer: unknown-crash on address 0x600e001b8f00 at pc 0x7ffff4e5a999 bp 0x7fffffffbba0 sp 0x7fffffffbb78
READ of size 18 at 0x600e001b8f00 thread T0
    #0 0x7ffff4e5a998 in index (/usr/lib/x86_64-linux-gnu/libasan.so.0+0xf998)
    #1 0x4fb4e4 in strip_comment /home/bp/RetroArch/libretro-common/file/config_file.c:81
    #2 0x4fc197 in parse_line /home/bp/RetroArch/libretro-common/file/config_file.c:260
    #3 0x4fc9eb in config_file_new_internal /home/bp/RetroArch/libretro-common/file/config_file.c:380
    #4 0x4fd408 in config_file_new /home/bp/RetroArch/libretro-common/file/config_file.c:527
    #5 0x4f5ca1 in cheat_manager_load /home/bp/RetroArch/managers/cheat_manager.c:228
    #6 0x626027 in generic_action_ok /home/bp/RetroArch/menu/cbs/menu_cbs_ok.c:1164
    #7 0x626735 in action_ok_cheat_file_load /home/bp/RetroArch/menu/cbs/menu_cbs_ok.c:1250
    #8 0x61f2a9 in menu_entry_action /home/bp/RetroArch/menu/widgets/menu_entry.c:452
    #9 0x6909ea in generic_menu_iterate /home/bp/RetroArch/menu/drivers/menu_generic.c:234
    #10 0x5eca8e in menu_driver_iterate /home/bp/RetroArch/menu/menu_driver.c:1683
    #11 0x41ebe6 in runloop_check_state /home/bp/RetroArch/retroarch.c:2554
    #12 0x4204e9 in runloop_iterate /home/bp/RetroArch/retroarch.c:3073
    #13 0x415473 in rarch_main /home/bp/RetroArch/frontend/frontend.c:131
    #14 0x415503 in main /home/bp/RetroArch/frontend/frontend.c:151
    #15 0x7ffff020bf44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
    #16 0x40e348 in _start (/home/bp/RetroArch/retroarch+0x40e348)
0x600e001b8f11 is located 0 bytes to the right of 65-byte region [0x600e001b8ed0,0x600e001b8f11)
allocated by thread T0 here:
    #0 0x7ffff4e6055f in __interceptor_realloc (/usr/lib/x86_64-linux-gnu/libasan.so.0+0x1555f)
    #1 0x453f5c in filestream_getline /home/bp/RetroArch/libretro-common/streams/file_stream.c:477
    #2 0x4fc975 in config_file_new_internal /home/bp/RetroArch/libretro-common/file/config_file.c:372
    #3 0x4fd408 in config_file_new /home/bp/RetroArch/libretro-common/file/config_file.c:527
    #4 0x4f5ca1 in cheat_manager_load /home/bp/RetroArch/managers/cheat_manager.c:228
    #5 0x626027 in generic_action_ok /home/bp/RetroArch/menu/cbs/menu_cbs_ok.c:1164
    #6 0x626735 in action_ok_cheat_file_load /home/bp/RetroArch/menu/cbs/menu_cbs_ok.c:1250
    #7 0x61f2a9 in menu_entry_action /home/bp/RetroArch/menu/widgets/menu_entry.c:452
    #8 0x6909ea in generic_menu_iterate /home/bp/RetroArch/menu/drivers/menu_generic.c:234
    #9 0x5eca8e in menu_driver_iterate /home/bp/RetroArch/menu/menu_driver.c:1683
    #10 0x41ebe6 in runloop_check_state /home/bp/RetroArch/retroarch.c:2554
    #11 0x4204e9 in runloop_iterate /home/bp/RetroArch/retroarch.c:3073
    #12 0x415473 in rarch_main /home/bp/RetroArch/frontend/frontend.c:131
    #13 0x415503 in main /home/bp/RetroArch/frontend/frontend.c:151
    #14 0x7ffff020bf44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
SUMMARY: AddressSanitizer: unknown-crash ??:0 index
Shadow bytes around the buggy address:
  0x0c024002f190: fa fa fa fa fd fd fd fd fd fd fd fd fd fa fa fa
  0x0c024002f1a0: fa fa fd fd fd fd fd fd fd fd fd fa fa fa fa fa
  0x0c024002f1b0: fd fd fd fd fd fd fd fd fd fa fa fa fa fa fd fd
  0x0c024002f1c0: fd fd fd fd fd fd fd fa fa fa fa fa fd fd fd fd
  0x0c024002f1d0: fd fd fd fd fd fa fa fa fa fa 00 00 00 00 00 00
=>0x0c024002f1e0:[00]00 01 fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c024002f1f0: fd fa fa fa fa fa fd fd fd fd fd fd fd fd fd fa
  0x0c024002f200: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c024002f210: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c024002f220: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c024002f230: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:     fa
  Heap righ redzone:     fb
  Freed Heap region:     fd
  Stack left redzone:    f1
  Stack mid redzone:     f2
  Stack right redzone:   f3
  Stack partial redzone: f4
  Stack after return:    f5
  Stack use after scope: f8
  Global redzone:        f9
  Global init order:     f6
  Poisoned by user:      f7
  ASan internal:         fe
==2568== ABORTING
```

**Comment by hyarsan** [comment]
The same thing happens with Pokémon Heart Gold :p

**Comment by twinaphex** [comment]
Can this issue be closed now @RetroSven? I believe you extended cheat lists to allow for more than 99 cheats now, right?

**Comment by RetroSven** [comment]
yes this should be fixed now - it may be worth getting at least one of the other people on this issue to confirm it's fixed for them before officially closing though.

**Comment by twinaphex** [comment]
Alright, to the participants in this thread - do you consider this issue fixed now with the latest RetroArch version?

**Comment by autofire372** [comment]
It IS fixed!
