### ISSUE TITLE
Segmentation fault when started in MinGW with core but without content

### ISSUE THREAD

**Issue by deltabeard** [libretro/RetroArch#6824]
## Description

Segmentation fault in RetroArch when starting it with a core in MSYS2-MinGW64 on Windows 8.1.
Works fine on Linux, and when RetroArch is started within MSYS2-MinGW64 without a core and file, where the core and file are both loaded without error when selected within the RetroArch interface.

### Expected behavior

RetroArch should start normally, with the core loaded, but no file loaded.

### Actual behavior

The following segmentation fault occurs.
```
#0  0x00007fff75f611f1 in strlen () from C:\Windows\system32\msvcrt.dll
#1  0x00000000004aa00c in strcpy_alloc (
    sourceStr=0xababababababab00 <error: Cannot access memory at address 0xababababababab00>) at runahead/mem_util.c:11
#2  0x00000000004a9730 in clone_retro_game_info (src=0x5d46030)
    at runahead/copy_load_info.c:38
#3  0x00000000004a9ab0 in clone_retro_ctx_load_content_info (src=0x23f330)
    at runahead/copy_load_info.c:241
#4  0x00000000004a9b3d in set_load_content_info (ctx=0x23f330)
    at runahead/copy_load_info.c:257
#5  0x0000000000402bde in core_load_game (load_info=0x23f330)
    at core_impl.c:294
#6  0x000000000041ddfc in content_file_load (info=0x5d46030,
    content=0x5d6d8a0, content_ctx=0x23f430, error_string=0x23f428,
    special=0x0, additional_path_allocs=0x5d6db20) at tasks/task_content.c:626
#7  0x000000000041e3bf in content_file_init (content_ctx=0x23f430,
    content=0x5d6d8a0, error_string=0x23f428) at tasks/task_content.c:807
#8  0x0000000000420389 in content_init () at tasks/task_content.c:1926
#9  0x000000000040c90f in event_init_content () at command.c:1214
#10 0x000000000040ca5e in command_event_init_core (
    data=0xc56160 <current_core_type>) at command.c:1272
#11 0x000000000040e5dd in command_event (cmd=CMD_EVENT_CORE_INIT,
    data=0xc56160 <current_core_type>) at command.c:2239
#12 0x00000000004055ff in retroarch_main_init (argc=3, argv=0x5e6af60)
    at retroarch.c:1336
#13 0x000000000041d426 in content_load (info=0x23fda0)
    at tasks/task_content.c:279
#14 0x000000000041e5d8 in task_load_content (content_info=0x23fda0,
    content_ctx=0x23fcb0, launched_from_menu=true, launched_from_cli=true,
    error_string=0x23fca8) at tasks/task_content.c:874
#15 0x000000000041fa25 in task_load_content_callback (content_info=0x23fda0,
    loading_from_menu=true, loading_from_cli=true)
    at tasks/task_content.c:1560
#16 0x000000000041fba4 in task_push_load_content_from_cli (core_path=0x0,
    fullpath=0x0, content_info=0x23fda0, type=CORE_TYPE_PLAIN, cb=0x0,
    user_data=0x0) at tasks/task_content.c:1624
#17 0x00000000004016e9 in rarch_main (argc=3, argv=0x5e6af60, data=0x0)
    at frontend/frontend.c:125
#18 0x000000000040176f in SDL_main (argc=3, argv=0x5e6af60)
    at frontend/frontend.c:169
#19 0x0000000000802428 in main_getcmdline ()
#20 0x00000000004013c7 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:331
#21 0x00000000004014cb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:187
```

### Steps to reproduce the bug

1. Compile RetroArch with `./configure --disable-ffmpeg --enable-opengl`.
2. Compile [libretro-mpv](https://github.com/libretro/libretro-mpv/tree/path_fix).
3. In MSYS2-MinGW64 run the command `../RetroArch/retroarch.exe -L ./mpv_libretro.dll`

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 2771f8cc415a0615ae7d7c594c0a498595cfb514

### Environment information

```
$ retroarch --version
 -- 2771f8cc41 --
Compiler: MinGW (7.3.0) 64-bitBuilt: May 24 2018
RetroArch: Frontend for libretro -- v1.7.3
```
- OS: Windows 8.1 MSYS2-MinGW64
- Compiler: `cc.exe (Rev2, Built by MSYS2 project) 7.3.0`

**Comment by LibretroAdmin** [comment]
Issue resolved by now
