### ISSUE TITLE
Failure with "Enable menu audio" when closing running content with some drivers.

### ISSUE THREAD

**Issue by Celti** [libretro/RetroArch#6857]
## Description

RetroArch with the `pulse` and `sdl2` drivers will hang or segfault, respectively, when selecting `Close Content` from the quick menu while `Enable menu audio` is enabled.

### Expected behavior

The content should close and the menu resume as normal.

### Actual behavior

With `pulse`: the menu hangs, darkened significantly and unresponsive. A single SIGKILL or two SIGINT/SIGTERM will end the process. Backtrace from hung state:
```
(gdb) bt
#0  0x00007ffff58d3ffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007ffff56a9d89 in pa_threaded_mainloop_wait () from /usr/lib/libpulse.so.0
#2  0x00005555556c76cc in pulse_write ()
#3  0x00005555555f08ba in audio_driver_flush ()
#4  0x00005555555cb57c in runloop_check_state.constprop ()
#5  0x00005555555cdef8 in runloop_iterate ()
#6  0x000055555569e351 in ui_application_qt_run(void*) ()
#7  0x00005555555c807a in rarch_main ()
#8  0x00007fffef46c06b in __libc_start_main () from /usr/lib/libc.so.6
#9  0x00005555555c4c7a in _start ()
```

With `sdl2`: a segfault happens immediately after selecting `Close Content`. Backtrace:
```
[over eighteen thousand lines in the same repeating pattern skipped]
#18056 0x00007ffff2dc3830 in ?? () from /usr/lib/libSDL2-2.0.so.0
#18057 0x00007ffff2e0a481 in ?? () from /usr/lib/libSDL2-2.0.so.0
#18058 0x00007ffff2e0a700 in ?? () from /usr/lib/libSDL2-2.0.so.0
#18059 0x00007ffff2dc3830 in ?? () from /usr/lib/libSDL2-2.0.so.0
#18060 0x00007ffff2e0a481 in ?? () from /usr/lib/libSDL2-2.0.so.0
#18061 0x00007ffff2e0a700 in ?? () from /usr/lib/libSDL2-2.0.so.0
#18062 0x00007ffff2dc3830 in ?? () from /usr/lib/libSDL2-2.0.so.0
#18063 0x00007ffff2e0a481 in ?? () from /usr/lib/libSDL2-2.0.so.0
#18064 0x00007ffff2e0a700 in ?? () from /usr/lib/libSDL2-2.0.so.0
#18065 0x00007ffff2dc3b5a in ?? () from /usr/lib/libSDL2-2.0.so.0
#18066 0x00007ffff2dc2157 in ?? () from /usr/lib/libSDL2-2.0.so.0
#18067 0x000055555576139a in sdl_audio_init ()
#18068 0x00005555555f28d8 in audio_driver_init ()
#18069 0x000055555561fe7d in drivers_init ()
#18070 0x00005555555cdc41 in retroarch_main_init ()
#18071 0x00005555555df335 in content_load ()
#18072 0x00005555555df719 in task_load_content ()
#18073 0x00005555555dfb07 in task_push_start_dummy_core ()
#18074 0x00005555555d1351 in command_event.localalias ()
#18075 0x00005555556f7637 in action_ok_close_content ()
#18076 0x00005555556f435e in menu_entry_action ()
#18077 0x000055555572bb57 in generic_menu_iterate ()
#18078 0x00005555556e0c4f in menu_driver_iterate ()
#18079 0x00005555555ca7ba in runloop_check_state.constprop ()
#18080 0x00005555555cdef8 in runloop_iterate ()
#18081 0x000055555569e351 in ui_application_qt_run(void*) ()
#18082 0x00005555555c807a in rarch_main ()
#18083 0x00007fffef46c06b in __libc_start_main () from /usr/lib/libc.so.6
#18084 0x00005555555c4c7a in _start ()
```

With both drivers, everything works just fine when `Enable menu audio` is turned off.

### Steps to reproduce the bug

1. Configure RetroArch with `Enable menu audio` enabled and either the `pulse` or `sdl2` audio drivers.
2. Load content for any core.
3. Bring up the Quick Menu from the running content and select `Close Content`.
4. RetroArch will either crash or hang.

### Bisect Results

I am not really familiar with bisecting, especially with the mostly-automated build system RetroArch has on Linux. Is there a guide to doing so?

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.3 (6ecf64d)

### Environment information

- OS: Arch Linux x86_64 (up-to-date, non-testing)
- Compiler: GCC 8.1.0

**Comment by lily-mayfield** [comment]
My retro arch 1.7.3 on lubuntu bionic is unresponsive simply when i turn enable menu audio on in the interface...

**Comment by orbea** [comment]
I can't reproduce this with the alsa driver.

**Comment by orbea** [comment]
Okay, I can reproduce this with SDL2.

**Comment by LibretroAdmin** [comment]
Should be resolved now
