### ISSUE TITLE
RetroArch leaks memory when exiting.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#7128]
## Description

RetroArch will leak memory when closing content.

### Expected behavior

RetroArch should not leak memory.

### Actual behavior

Memory leaks like this.

```
    ==3948==ERROR: LeakSanitizer: detected memory leaks
    
    Direct leak of 13 byte(s) in 1 object(s) allocated from:
        #0 0x7f2b30fca840 in strdup (/usr/lib64/libasan.so.5+0x3a840)
        #1 0x53bf26 in libretro_get_system_info dynamic.c:380
        #2 0x42de12 in command_event command.c:1841
        #3 0x77832c in menu_update_libretro_info menu/menu_driver.c:1947
        #4 0x77834a in menu_driver_init_internal menu/menu_driver.c:1953
        #5 0x778562 in menu_driver_init menu/menu_driver.c:1988
        #6 0x50e523 in drivers_init driver.c:391
        #7 0x41e882 in retroarch_main_init retroarch.c:1395
        #8 0x444133 in content_load tasks/task_content.c:279
        #9 0x446f2d in task_load_content tasks/task_content.c:880
        #10 0x44b1d1 in task_load_content_callback tasks/task_content.c:1565
        #11 0x44b557 in task_push_load_content_from_cli tasks/task_content.c:1633
        #12 0x417e0f in rarch_main frontend/frontend.c:125
        #13 0x417fd3 in main frontend/frontend.c:169
        #14 0x7f2b2dbd9ba6 in __libc_start_main (/lib64/libc.so.6+0x21ba6)
    
    Direct leak of 5 byte(s) in 1 object(s) allocated from:
        #0 0x7f2b30fca840 in strdup (/usr/lib64/libasan.so.5+0x3a840)
        #1 0x53be82 in libretro_get_system_info dynamic.c:375
        #2 0x42de12 in command_event command.c:1841
        #3 0x77832c in menu_update_libretro_info menu/menu_driver.c:1947
        #4 0x77834a in menu_driver_init_internal menu/menu_driver.c:1953
        #5 0x778562 in menu_driver_init menu/menu_driver.c:1988
        #6 0x50e523 in drivers_init driver.c:391
        #7 0x41e882 in retroarch_main_init retroarch.c:1395
        #8 0x444133 in content_load tasks/task_content.c:279
        #9 0x446f2d in task_load_content tasks/task_content.c:880
        #10 0x44b1d1 in task_load_content_callback tasks/task_content.c:1565
        #11 0x44b557 in task_push_load_content_from_cli tasks/task_content.c:1633
        #12 0x417e0f in rarch_main frontend/frontend.c:125
        #13 0x417fd3 in main frontend/frontend.c:169
        #14 0x7f2b2dbd9ba6 in __libc_start_main (/lib64/libc.so.6+0x21ba6)
```

### Steps to reproduce the bug

1. Build RetroArch with asan.
2. Start RetroArch
3. Load content.
4. Exit

### Bisect Results

The further back I went the worse it got...

### Version/Commit

- RetroArch: a6d5931412253bc8f5f611e7de7af73f9e56c06

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-8.2.0`, `clang-6.0.1`

**Comment by twinaphex** [comment]
@bparker06 Do these leaks still exist?

**Comment by orbea** [comment]
I think they do, I talked with bparker about this a while ago on irc and there were problems with the approach in the above patch.

If I recall the problem is that in some cases the memory is static and RA will crash when trying to free it.
