### ISSUE TITLE
Discord Overlay Crashes RA on D3D10

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#7412]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When starting RA with the discord overlay enabled in D3D10 you get a crash after a few seconds

### Expected behavior

Should work, business as usual

### Actual behavior

```
warning: [00:00:00.002][PID22496] Process name: D:\GameData\Emulators\RetroArch\retroarch.exe
[INFO] [Discord] connected to user: radius#5870 - avatar id: 155390707853557760
warning: [22:04:30.980][PID22496] Starting graphics hook in process D:\GameData\Emulators\RetroArch\retroarch.exe
warning: [22:04:31.037][PID22496] Hooked DXGI
warning: [22:04:31.037][PID22496] Hooked OpenGL
warning: [22:04:31.046][PID22496] D3D1XState::InitDevice10: dev->CreateTexture2D(&desc, nullptr, tex.tex.Receive()) failed: 0x80070057
warning: [22:04:31.047][PID22496] D3D1XState::InitDevice10: initialized to 00000000000B19F0 (D3D10, window 00000000007F0B4E: 1920x1080)
[New Thread 22496.0x5fe8]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffed80fbe86 in dummy_debug_proc ()
   from C:\Users\Andres\AppData\Roaming\discord\0.0.301\modules\discord_hook\14\DiscordHook64.dll
(gdb) bt
#0  0x00007ffed80fbe86 in dummy_debug_proc ()
   from C:\Users\Andres\AppData\Roaming\discord\0.0.301\modules\discord_hook\14\DiscordHook64.dll
#1  0x00007ffed8107eb2 in dummy_debug_proc ()
   from C:\Users\Andres\AppData\Roaming\discord\0.0.301\modules\discord_hook\14\DiscordHook64.dll
#2  0x00007ffed8107f84 in dummy_debug_proc ()
   from C:\Users\Andres\AppData\Roaming\discord\0.0.301\modules\discord_hook\14\DiscordHook64.dll
#3  0x00007ffed80f338a in dummy_debug_proc ()
   from C:\Users\Andres\AppData\Roaming\discord\0.0.301\modules\discord_hook\14\DiscordHook64.dll
#4  0x00007ffed80ff2a2 in dummy_debug_proc ()
   from C:\Users\Andres\AppData\Roaming\discord\0.0.301\modules\discord_hook\14\DiscordHook64.dll
#5  0x0000000000642c4a in d3d10_gfx_frame ()
#6  0x0000000000463530 in video_driver_frame ()
#7  0x000000000046068d in video_driver_cached_frame ()
#8  0x000000000058a415 in menu_driver_render ()
#9  0x000000000040405d in runloop_check_state.constprop ()
#10 0x0000000000407e65 in runloop_iterate ()
#11 0x0000000000401670 in rarch_main ()
#12 0x00000000009283b8 in main_getcmdline ()
#13 0x00000000004013c7 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:331
#14 0x00000000004014cb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:187
(gdb)
```

### Steps to reproduce the bug

1. Enable discord overlay

![image](https://user-images.githubusercontent.com/1721040/46774718-79472a80-ccc9-11e8-92f8-fb6f3e4a73c0.png)

2. Add RetroArch

![image](https://user-images.githubusercontent.com/1721040/46774747-92e87200-ccc9-11e8-81e4-41eaf30ecc44.png)

3. Change RA driver to D3D10
4. Restart 
5. Wait for it

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by zoltanvb** [comment]
I don't think there is a discord overlay nowadays, this can probably be closed.
