### ISSUE TITLE
Leak when taking multiple screenshots

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#8125]
The whole screenshot task leaks if you take multiple screenshots simultaneously. The best way to reproduce this is to spam the screenshot hotkey.

This is an issue because if you press the screenshot button for _slightly_ too long, RetroArch will take multiple screenshots, leading to a leak.

The thing is, we can't just disable taking a screenshot if a screenshot is already being saved because cheevos uses screenshots for achievements - if an achievement occurs while a screenshot is saving, we can't just discard or delay the achievement screenshot.

Leak summary (basically the whole task) :

```
Direct leak of 2704 byte(s) in 26 object(s) allocated from:
    #0 0x7fb856c10d38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
    #1 0x5633eb2130ed in screenshot_dump tasks/task_screenshot.c:193
    #2 0x5633eb213e54 in take_screenshot_viewport tasks/task_screenshot.c:322
    #3 0x5633eb21441b in take_screenshot_choice tasks/task_screenshot.c:381
    #4 0x5633eb21493f in take_screenshot tasks/task_screenshot.c:420
    #5 0x5633eb0c4155 in command_event /home/natinusala/Documents/RetroArch/command.c:1948
    #6 0x5633eb0b6b9a in runloop_check_state /home/natinusala/Documents/RetroArch/retroarch.c:3021
    #7 0x5633eb0b888a in runloop_iterate /home/natinusala/Documents/RetroArch/retroarch.c:3580
    #8 0x5633eb0aaf90 in rarch_main frontend/frontend.c:157
    #9 0x5633eb0ab0e6 in main frontend/frontend.c:185
    #10 0x7fb853431b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

Indirect leak of 60652800 byte(s) in 26 object(s) allocated from:
    #0 0x7fb856c10b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x5633eb213d41 in take_screenshot_viewport tasks/task_screenshot.c:313
    #2 0x5633eb21441b in take_screenshot_choice tasks/task_screenshot.c:381
    #3 0x5633eb21493f in take_screenshot tasks/task_screenshot.c:420
    #4 0x5633eb0c4155 in command_event /home/natinusala/Documents/RetroArch/command.c:1948
    #5 0x5633eb0b6b9a in runloop_check_state /home/natinusala/Documents/RetroArch/retroarch.c:3021
    #6 0x5633eb0b888a in runloop_iterate /home/natinusala/Documents/RetroArch/retroarch.c:3580
    #7 0x5633eb0aaf90 in rarch_main frontend/frontend.c:157
    #8 0x5633eb0ab0e6 in main frontend/frontend.c:185
    #9 0x7fb853431b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

Indirect leak of 60652800 byte(s) in 26 object(s) allocated from:
    #0 0x7fb856c10b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x5633eb2137a9 in screenshot_dump tasks/task_screenshot.c:265
    #2 0x5633eb213e54 in take_screenshot_viewport tasks/task_screenshot.c:322
    #3 0x5633eb21441b in take_screenshot_choice tasks/task_screenshot.c:381
    #4 0x5633eb21493f in take_screenshot tasks/task_screenshot.c:420
    #5 0x5633eb0c4155 in command_event /home/natinusala/Documents/RetroArch/command.c:1948
    #6 0x5633eb0b6b9a in runloop_check_state /home/natinusala/Documents/RetroArch/retroarch.c:3021
    #7 0x5633eb0b888a in runloop_iterate /home/natinusala/Documents/RetroArch/retroarch.c:3580
    #8 0x5633eb0aaf90 in rarch_main frontend/frontend.c:157
    #9 0x5633eb0ab0e6 in main frontend/frontend.c:185
    #10 0x7fb853431b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

Indirect leak of 112944 byte(s) in 26 object(s) allocated from:
    #0 0x7fb856c10d38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
    #1 0x5633eb213103 in screenshot_dump tasks/task_screenshot.c:194
    #2 0x5633eb213e54 in take_screenshot_viewport tasks/task_screenshot.c:322
    #3 0x5633eb21441b in take_screenshot_choice tasks/task_screenshot.c:381
    #4 0x5633eb21493f in take_screenshot tasks/task_screenshot.c:420
    #5 0x5633eb0c4155 in command_event /home/natinusala/Documents/RetroArch/command.c:1948
    #6 0x5633eb0b6b9a in runloop_check_state /home/natinusala/Documents/RetroArch/retroarch.c:3021
    #7 0x5633eb0b888a in runloop_iterate /home/natinusala/Documents/RetroArch/retroarch.c:3580
    #8 0x5633eb0aaf90 in rarch_main frontend/frontend.c:157
    #9 0x5633eb0ab0e6 in main frontend/frontend.c:185
    #10 0x7fb853431b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

Indirect leak of 494 byte(s) in 26 object(s) allocated from:
    #0 0x7fb856ba9538 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x77538)
    #1 0x5633eb213902 in screenshot_dump tasks/task_screenshot.c:283
    #2 0x5633eb213e54 in take_screenshot_viewport tasks/task_screenshot.c:322
    #3 0x5633eb21441b in take_screenshot_choice tasks/task_screenshot.c:381
    #4 0x5633eb21493f in take_screenshot tasks/task_screenshot.c:420
    #5 0x5633eb0c4155 in command_event /home/natinusala/Documents/RetroArch/command.c:1948
    #6 0x5633eb0b6b9a in runloop_check_state /home/natinusala/Documents/RetroArch/retroarch.c:3021
    #7 0x5633eb0b888a in runloop_iterate /home/natinusala/Documents/RetroArch/retroarch.c:3580
    #8 0x5633eb0aaf90 in rarch_main frontend/frontend.c:157
    #9 0x5633eb0ab0e6 in main frontend/frontend.c:185
    #10 0x7fb853431b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
```

**Comment by bparker06** [comment]
I think the screenshot task used to be blocking for this reason... but someone must have changed it. Maybe when adding cheevos screenshots or something?

**Comment by meleu** [comment]
> I think the screenshot task used to be blocking for this reason... but someone must have changed it. Maybe when adding cheevos screenshots or something?

I submitted that PR, and I think it was changed before.
