### ISSUE TITLE
Start Netplay host gives crash

### ISSUE THREAD

**Issue by gouchi** [libretro/RetroArch#9067]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Start Netplay host gives crash

### Expected behavior

Start Netplay host to start normally

### Actual behavior

Start Netplay host gives crash

### Steps to reproduce the bug

1. Start RetroArch
2. Start netplay host

### Bisect Results

commit 4f7f5d25239ddd78b232dfbf5db5eb710132cf69
```

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
video_frame_net (data=0x5555562341e0 <dummy_pixels>, width=4, height=4, pitch=8) at network/netplay/netplay_frontend.c:545
545	      netplay_data->cbs.frame_cb(data, width, height, pitch);
(gdb) bt full
#0  video_frame_net (data=0x5555562341e0 <dummy_pixels>, width=4, height=4, pitch=8) at network/netplay/netplay_frontend.c:545
No locals.
#1  0x00005555555c8221 in video_driver_cached_frame () at retroarch.c:9171
        recording = 0x0
#2  0x00005555557e4b70 in menu_display_libretro (is_idle=false, rarch_is_inited=true, rarch_is_dummy_core=true) at menu/menu_driver.c:644
No locals.
#3  0x00005555557e9ee9 in menu_driver_render (is_idle=false, rarch_is_inited=true, rarch_is_dummy_core=true) at menu/menu_driver.c:2053
No locals.
#4  0x00005555555d4907 in runloop_check_state (settings=0x7fffedd8d010, input_nonblock_state=false, runloop_is_paused=false, fastforward_ratio=0, sleep_ms=0x7fffffffe190) at retroarch.c:16109
        core_type_is_dummy = true
        libretro_running = false
        action = MENU_ACTION_NOOP
        old_action = MENU_ACTION_OK
        focused = true
        trigger_input = {data = {0, 0, 0, 0, 0, 0, 0, 0}, analogs = {0, 0, 0, 0, 0, 0, 0, 0}, analog_buttons = {0 <repeats 16 times>}}
        iter = {action = MENU_ACTION_NOOP, pointer = {x = 32767, y = 0, touch = 176}, mouse = {x = 21851, y = 21845, buttons = {left = false, right = false}, wheel = {up = 192, down = 226}}}
        old_input = {data = {256, 0, 0, 0, 0, 0, 0, 0}, analogs = {0, 0, 0, 0, 0, 0, 0, 0}, analog_buttons = {0 <repeats 16 times>}}
        global = 0x555556207220 <g_extern>
        current_bits = {data = {0, 0, 0, 0, 0, 0, 0, 0}, analogs = {0, 0, 0, 0, 0, 0, 0, 0}, analog_buttons = {0 <repeats 16 times>}}
        last_input = {data = {256, 0, 0, 0, 0, 0, 0, 0}, analogs = {0, 0, 0, 0, 0, 0, 0, 0}, analog_buttons = {0 <repeats 16 times>}}
        old_focus = true
        is_focused = true
        is_alive = true
        frame_count = 224
        focused = true
        pause_nonactive = true
        rarch_is_initialized = true
        menu_driver_binding_state = false
        menu_is_alive = true
        menu_toggle_gamepad_combo = 4
        seq = 9259542123273781248
#5  0x00005555555d5f78 in runloop_iterate (sleep_ms=0x7fffffffe190) at retroarch.c:16688
        i = 4294959296
        runloop_is_paused = false
        input_nonblock_state = false
        settings = 0x7fffedd8d010
        fastforward_ratio = 0
        video_frame_delay = 0
        vrr_runloop_enable = false
        max_users = 5
#6  0x00005555555b721c in rarch_main (argc=1, argv=0x7fffffffe2c8, data=0x0) at frontend/frontend.c:155
        sleep_ms = 0
        ret = 1
        args = 0x0
#7  0x00005555555b728d in main (argc=1, argv=0x7fffffffe2c8) at frontend/frontend.c:183
No locals.
```

### Version/Commit
- RetroArch: [3ffc5fc3433cbe539a16d0e75be55bef94d2d1f1]

### Environment information

- OS: Linux
- Compiler: gcc version 8.3.0

**Comment by twinaphex** [comment]
OK, this should fix it I hope -

https://github.com/libretro/RetroArch/commit/614674f43672c0bdd0a10f85dead46890fa056e6

Let me know if you run into any further issues.

**Comment by gouchi** [comment]
Thank you the issue is now fixed !
